import { useEffect,useMemo,useState } from 'react'
import type { CSSProperties } from 'react'
import { evaluateMotionExpertAtTickV1,instantiateMotionExpertRecipeV1,runMotionExpertQaV1,type MotionExpertRuntimeFrameV1 } from '@sanverse/motion-expert-runtime'
import { createMotionScene,deriveNodeGraphProjection,evaluateScene,nodeBase,projectMotionLayers,type MotionExpertNodeV1,type MotionSceneV1,type ResolvedMotionExpertNodeV1 } from '@sanverse/motion-graph'
import { MotionExpertNodeSurface } from '@sanverse/motion-native-runtime'
import { SANVERSE_TICKS_PER_SECOND } from '@sanverse/motion-primitives'

const durationTicks=5*SANVERSE_TICKS_PER_SECOND
const composition=Object.freeze({width:960,height:540,fpsNumerator:30,fpsDenominator:1})
const page:CSSProperties={minHeight:'100vh',boxSizing:'border-box',padding:22,background:'#07080a',color:'#f6f6f6',fontFamily:'Inter,ui-sans-serif,system-ui,sans-serif'}
const panel:CSSProperties={border:'1px solid #2a2d34',borderRadius:16,background:'#101217',padding:14}
const badge:CSSProperties={display:'inline-flex',border:'1px solid #353942',borderRadius:999,padding:'5px 9px',fontSize:11,color:'#d9dce3',background:'#181b21'}
const label:CSSProperties={fontSize:11,textTransform:'uppercase',letterSpacing:'.12em',color:'#8e94a2'}
const makeSpec=(recipeId:'expert.orbital-accent'|'expert.radial-payoff'|'expert.plasma-backdrop',seed:number)=>{const result=instantiateMotionExpertRecipeV1({recipeId,width:composition.width,height:composition.height,seed});if(!result.ok)throw new RangeError(result.refusal.message);return result.value}
const proceduralSpec=makeSpec('expert.orbital-accent',101),particleSpec=makeSpec('expert.radial-payoff',202),shaderSpec=makeSpec('expert.plasma-backdrop',303)
const expertNode=(id:string,name:string,spec:typeof proceduralSpec|typeof particleSpec|typeof shaderSpec):MotionExpertNodeV1=>Object.freeze({...nodeBase(id,name,'expert.root'),type:'expert',expert:spec})
const expertScene:MotionSceneV1=(()=>{const root=nodeBase('expert.root','Expert Motion Root',null),procedural=expertNode('expert.procedural','Orbital Accent',proceduralSpec),particles=expertNode('expert.particles','Radial Payoff',particleSpec),shader=expertNode('expert.shader','Plasma Backdrop',shaderSpec);return createMotionScene({componentId:'sanverse.expert-motion-review',componentVersion:1,rootNodeId:'expert.root',nodes:Object.freeze({'expert.root':Object.freeze({...root,type:'group' as const,childIds:Object.freeze([procedural.id,particles.id,shader.id])}),[procedural.id]:procedural,[particles.id]:particles,[shader.id]:shader}),semanticParts:Object.freeze([{id:'expert-procedural',label:'Procedural',role:'decoration' as const,nodeIds:Object.freeze([procedural.id])},{id:'expert-particles',label:'Particles',role:'decoration' as const,nodeIds:Object.freeze([particles.id])},{id:'expert-shader',label:'Shader',role:'surface' as const,nodeIds:Object.freeze([shader.id])}]),exposures:Object.freeze([]),layout:Object.freeze({mode:'manual' as const,ownership:Object.freeze([]),formatOverrides:Object.freeze([])}),supportedAspectRatios:Object.freeze(['16:9'])})})()
const c6=deriveNodeGraphProjection(expertScene),c3=projectMotionLayers({scene:expertScene})
const qa=Object.freeze({procedural:runMotionExpertQaV1(proceduralSpec),particles:runMotionExpertQaV1(particleSpec),shader:runMotionExpertQaV1(shaderSpec)})
const allQaPass=Object.values(qa).every((report)=>report.status==='PASS')
const context=(tick:number)=>Object.freeze({localTicks:tick,durationTicks,ticksPerSecond:SANVERSE_TICKS_PER_SECOND,composition,reducedMotion:false})

export interface ExpertMotionReviewFrameV1{readonly tick:number;readonly resolvedNodes:Readonly<Record<string,ResolvedMotionExpertNodeV1>>;readonly runtimeFrames:Readonly<Record<string,MotionExpertRuntimeFrameV1>>;readonly qaStatus:'PASS'|'FAIL';readonly c3ExpertNodeIds:readonly string[];readonly c6ExpertNodeIds:readonly string[]}
export const buildExpertMotionReviewFrame=(tick:number):ExpertMotionReviewFrameV1=>{const safeTick=Math.max(0,Math.min(durationTicks,Math.round(tick))),resolved=evaluateScene(expertScene,context(safeTick)),ids=['expert.procedural','expert.particles','expert.shader'] as const,resolvedNodes=Object.fromEntries(ids.map((id)=>[id,resolved.nodes[id] as ResolvedMotionExpertNodeV1])),runtimeFrames=Object.fromEntries(ids.map((id)=>{const node=resolvedNodes[id]!,frame=evaluateMotionExpertAtTickV1({spec:node.expert,tick:safeTick});if(!frame.ok)throw new RangeError(frame.refusal.message);return[id,frame.value]}));return Object.freeze({tick:safeTick,resolvedNodes:Object.freeze(resolvedNodes),runtimeFrames:Object.freeze(runtimeFrames),qaStatus:allQaPass?'PASS':'FAIL',c3ExpertNodeIds:Object.freeze(c3.preorderNodeIds.filter((id)=>c3.layersById[id]?.nodeType==='expert')),c6ExpertNodeIds:Object.freeze(c6.nodes.filter((node)=>node.type==='expert').map((node)=>node.nodeId))})}
const directSeekProof=(()=>{for(const tick of [720_000,2_340_000,6_600_000]){const a=buildExpertMotionReviewFrame(tick);buildExpertMotionReviewFrame(durationTicks);const b=buildExpertMotionReviewFrame(tick);if(JSON.stringify(a.runtimeFrames)!==JSON.stringify(b.runtimeFrames))return false}return true})()
const Surface=({node,tick}:{node:ResolvedMotionExpertNodeV1;tick:number})=><div style={{height:250,aspectRatio:'16/9',maxWidth:'100%',margin:'0 auto',borderRadius:12,overflow:'hidden',background:'#090b10',border:'1px solid #2a2e38'}}><MotionExpertNodeSurface node={node} context={context(tick)}/></div>

export function ExpertMotionReviewLab(){
  const [tick,setTick]=useState(0),[full,setFull]=useState(false)
  useEffect(()=>{let raf=0,cancelled=false;const anchor=performance.now();const loop=(now:number)=>{if(cancelled)return;const next=Math.max(0,Math.min(durationTicks,Math.round((now-anchor)/1000*SANVERSE_TICKS_PER_SECOND)));setTick(next);if(next>=durationTicks){setTick(durationTicks);setFull(true);return}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>{cancelled=true;cancelAnimationFrame(raf)}},[])
  const frame=useMemo(()=>buildExpertMotionReviewFrame(tick),[tick]),seconds=(frame.tick/SANVERSE_TICKS_PER_SECOND).toFixed(2),procedural=frame.runtimeFrames['expert.procedural']!,particles=frame.runtimeFrames['expert.particles']!,shader=frame.runtimeFrames['expert.shader']!
  return <main style={page} data-expert-motion-review="true" data-expert-current-tick={frame.tick} data-expert-duration-ticks={durationTicks} data-expert-full-playback={full?'true':'false'} data-expert-playback-rate="1" data-expert-graph-backed="true" data-expert-c3-count={frame.c3ExpertNodeIds.length} data-expert-c6-count={frame.c6ExpertNodeIds.length} data-expert-direct-seek={directSeekProof?'true':'false'} data-expert-qa={frame.qaStatus}>
    <header style={{maxWidth:1450,margin:'0 auto 14px',display:'flex',justifyContent:'space-between',alignItems:'end',gap:14}}><div><div style={label}>Sanverse Creative Engine V1.4</div><h1 style={{margin:'5px 0 4px'}}>C11/C12 Expert Motion · deterministic by exact tick</h1><p style={{margin:0,color:'#9ba1af',fontSize:13}}>One canonical Motion Scene. Three bounded expert nodes. No autonomous clocks, arbitrary code, filesystem/network authority, or parallel Expert/Particle/Shader graph.</p></div><span style={badge}>{full?'✓ full 1× playback':'▶ playing at 1×'} · {seconds}/5.00s</span></header>
    <div style={{maxWidth:1450,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:14}}>
      <section style={panel} data-expert-proof="procedural"><div style={{display:'flex',justifyContent:'space-between',gap:8,marginBottom:10}}><div><div style={label}>C12 procedural</div><h3 style={{margin:'5px 0'}}>Orbital Accent</h3></div><span style={badge}>{procedural.resourceUsage.primitiveCount}/{proceduralSpec.maxPrimitives} primitives</span></div><Surface node={frame.resolvedNodes['expert.procedural']!} tick={frame.tick}/><p style={{fontSize:12,color:'#a8aeba',lineHeight:1.5}}>Fixed <code>orbital-rings</code> program. Ring geometry is recomputed from canonical tick + seed 101.</p></section>
      <section style={panel} data-expert-proof="particles"><div style={{display:'flex',justifyContent:'space-between',gap:8,marginBottom:10}}><div><div style={label}>C11 particles</div><h3 style={{margin:'5px 0'}}>Radial Payoff</h3></div><span style={badge}>{particles.resourceUsage.primitiveCount}/{particleSpec.maxPrimitives} particles</span></div><Surface node={frame.resolvedNodes['expert.particles']!} tick={frame.tick}/><p style={{fontSize:12,color:'#a8aeba',lineHeight:1.5}}>72 particles are analytically reconstructed from tick + seed 202. There is no retained particle simulation state.</p></section>
      <section style={panel} data-expert-proof="shader"><div style={{display:'flex',justifyContent:'space-between',gap:8,marginBottom:10}}><div><div style={label}>C12 shader</div><h3 style={{margin:'5px 0'}}>Plasma Backdrop</h3></div><span style={badge}>tick {shader.shader?.uniforms.canonicalTick}</span></div><Surface node={frame.resolvedNodes['expert.shader']!} tick={frame.tick}/><p style={{fontSize:12,color:'#a8aeba',lineHeight:1.5}}>Fixed <code>plasma-field</code> program. Its uniforms expose canonical tick + seed 303; arbitrary GLSL/WGSL is refused.</p></section>
    </div>
    <div style={{maxWidth:1450,margin:'14px auto 0',display:'grid',gridTemplateColumns:'1.3fr 1fr',gap:14}}>
      <section style={panel}><div style={label}>Canonical authority proof</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8,marginTop:10}}><span style={badge}>MotionScene expert nodes: 3</span><span style={badge}>C3 Layers expert IDs: {frame.c3ExpertNodeIds.length}</span><span style={badge}>C6 Node Graph expert IDs: {frame.c6ExpertNodeIds.length}</span></div><div style={{fontSize:12,color:'#aeb4c0',marginTop:10}}>Semantic IDs: {frame.c3ExpertNodeIds.join(' · ')}. C3 and C6 see the same nodes; neither stores a second expert document.</div></section>
      <section style={panel}><div style={label}>Resource + determinism QA</div><h3 style={{margin:'7px 0'}}>{frame.qaStatus} · direct/back/random seek {directSeekProof?'PASS':'FAIL'}</h3><div style={{fontSize:12,color:'#aeb4c0'}}>Procedural max {qa.procedural.maximumObservedPrimitives}/{qa.procedural.maximumAllowedPrimitives} · particles {qa.particles.maximumObservedPrimitives}/{qa.particles.maximumAllowedPrimitives} · shader {qa.shader.maximumObservedPrimitives}/{qa.shader.maximumAllowedPrimitives}. All outputs are bounded and reconstructed at the requested tick.</div></section>
    </div>
    <footer style={{maxWidth:1450,margin:'14px auto 0',...panel,fontSize:12,color:'#a6acb8'}}>Authority chain: typed recipe/external subset → canonical Motion expert node → exact-tick Expert Runtime → native preview adapter. Internal tools own no project/approval/Undo state; MCP only delegates the same registry.</footer>
  </main>
}
