import { useEffect,useMemo,useRef,useState } from 'react'
import type { CSSProperties } from 'react'
import type { MotionPlanV1 } from '@sanverse/creative-direction'
import { applyMotionPlanV1 } from '@sanverse/motion-agent-tools'
import { constant,type MotionGraphOperationV1 } from '@sanverse/motion-graph'
import { CostValueCardModule,DEFAULT_COST_VALUE_CARD_PROPS,DEFAULT_COST_VALUE_CARD_STYLE,MOTION_REFERENCE_COMPOSITIONS,promotedCapabilityToLibraryDetailV1 } from '@sanverse/motion-library'
import { MotionComponentHost,MotionCompositionFrame } from '@sanverse/motion-native-runtime'
import { SANVERSE_TICKS_PER_SECOND } from '@sanverse/motion-primitives'
import { classifyPromotionCandidateV1,createPromotionCandidateV1,createPromotionRegistryV1,instantiateReusableMotionTemplateV1,productizePromotionCandidateV1,proposeParameterizationPlanV1,registerPromotedCapabilityV1,runPromotionQaV1,type PromotionSourceV1 } from '@sanverse/motion-promotion'
import { advancePlaybackTicks } from './transport.ts'

const composition=MOTION_REFERENCE_COMPOSITIONS['16:9']
const durationTicks=5*SANVERSE_TICKS_PER_SECOND
const reviewPlan:MotionPlanV1=Object.freeze({id:'motion-plan:promotion-review',storyboardId:'storyboard:promotion-review',storyboardApprovedRevision:2,animaticId:'animatic:promotion-review',animaticApprovedRevision:2,beats:Object.freeze([Object.freeze({id:'beat:metric-payoff',purpose:'payoff' as const,startTick:720_000,endTick:3_600_000,nodeIds:Object.freeze(['cost-card.value']),operationIntents:Object.freeze([Object.freeze({id:'intent:value-scale',type:'motion.scale' as const,nodeIds:Object.freeze(['cost-card.value']),startTick:720_000,endTick:2_160_000,parameters:Object.freeze({from:.78,to:1})}),Object.freeze({id:'intent:value-move',type:'motion.move' as const,nodeIds:Object.freeze(['cost-card.value']),startTick:720_000,endTick:2_160_000,parameters:Object.freeze({fromX:84,toX:0,fromY:20,toY:0})})])})]),revision:1})

const page:CSSProperties={minHeight:'100vh',boxSizing:'border-box',padding:24,background:'#090909',color:'#f5f5f5',fontFamily:'Inter,ui-sans-serif,system-ui,sans-serif'}
const panel:CSSProperties={border:'1px solid #303030',borderRadius:14,background:'#111',padding:14}
const badge:CSSProperties={display:'inline-flex',alignItems:'center',border:'1px solid #383838',borderRadius:999,padding:'4px 8px',fontSize:11,color:'#ddd',background:'#171717'}
const label:CSSProperties={fontSize:11,textTransform:'uppercase',letterSpacing:'.12em',color:'#888'}

const setText=(operationId:string,nodeId:string,text:string):MotionGraphOperationV1=>Object.freeze({operationId,type:'set-property',target:{nodeId,property:'text.text' as const},value:constant(text)})
const setColor=(operationId:string,nodeId:string,color:string):MotionGraphOperationV1=>Object.freeze({operationId,type:'set-property',target:{nodeId,property:'text.fillColor' as const},value:constant(color)})

export const buildPromotionReviewModel=()=>{
  const baseContext=Object.freeze({localTicks:0,durationTicks,ticksPerSecond:SANVERSE_TICKS_PER_SECOND,composition,reducedMotion:false})
  const base=CostValueCardModule.createScene(DEFAULT_COST_VALUE_CARD_PROPS,DEFAULT_COST_VALUE_CARD_STYLE,baseContext)
  const compiled=applyMotionPlanV1(base,reviewPlan);if(!compiled.ok)throw new RangeError(`${compiled.refusal.code}: ${compiled.refusal.message}`)
  const generatedScene=Object.freeze({...compiled.value.scene,componentId:'generated.project-a.cost-value-story'})
  const source:PromotionSourceV1=Object.freeze({schemaVersion:'sanverse.promotion-source/v1',sourceProjectId:'project:a:promotion-review',sourceProjectRevision:12,sourceSceneId:'motion-draft:promotion-review',sourceSceneRevision:3,scene:generatedScene,sourceStoryboardId:'storyboard:promotion-review',sourceStoryboardRevision:2,sourceAnimaticId:'animatic:promotion-review',sourceAnimaticRevision:2,sourceMotionPlanId:reviewPlan.id,sourceMotionPlanRevision:reviewPlan.revision,motionPlan:reviewPlan,motionApproval:Object.freeze({schemaVersion:'sanverse.owner-approval/v1',id:'approval:promotion-review:r3',scope:'motion',subjectId:'motion-draft:promotion-review',subjectRevision:3,status:'owner-approved',approvedAt:'2026-08-26T09:00:00.000Z'}),structuralQaPassed:true,visualReviewEvidence:Object.freeze({canonicalReviewRef:'review://promotion-review/project-a/1x',posterRef:'frame://promotion-review/project-a/poster',criticalFrameRefs:Object.freeze(['frame://promotion-review/a/entrance','frame://promotion-review/a/payoff','frame://promotion-review/a/exit'])}),origin:'generated',dependencies:Object.freeze([])})
  const candidateResult=createPromotionCandidateV1(source,['scene','motion-recipe'],'promotion:cost-value-story');if(!candidateResult.ok)throw new RangeError(candidateResult.refusal.message)
  const candidate=candidateResult.value,parameterResult=proposeParameterizationPlanV1(candidate,source.scene,'parameters:cost-value-story');if(!parameterResult.ok)throw new RangeError(parameterResult.refusal.message)
  const parameterization=parameterResult.value,classification=classifyPromotionCandidateV1(candidate,source.scene,source.motionPlan)
  const productResult=productizePromotionCandidateV1({id:'promoted.cost-value-story',title:'Reusable Cost → Value Story',description:'Generated Project-A cost/value scene productized into a reusable metric-story capability.',candidate,source,parameterization,classification,targetKind:'scene',registrationVersion:1});if(!productResult.ok)throw new RangeError(productResult.refusal.message)
  const product=productResult.value,defaultInstance=instantiateReusableMotionTemplateV1(product.template,product.canonicalFixture.values,{instanceId:'promotion-review:default'});if(!defaultInstance.ok)throw new RangeError(defaultInstance.refusal.message)
  const replacementValues:Record<string,unknown>={}
  if(product.template.parameters.some(item=>item.publicPath==='content.headline'))replacementValues['content.headline']='Retention compounds faster'
  if(product.template.parameters.some(item=>item.publicPath==='content.metric'))replacementValues['content.metric']='82%'
  if(product.template.parameters.some(item=>item.publicPath==='content.supporting-label'))replacementValues['content.supporting-label']='Customer retention'
  if(product.template.parameters.some(item=>item.publicPath==='style.accent'))replacementValues['style.accent']='#FF7A1A'
  if(product.template.parameters.some(item=>item.publicPath==='motion.intensity'))replacementValues['motion.intensity']=1
  const replacement=instantiateReusableMotionTemplateV1(product.template,replacementValues,{instanceId:'promotion-review:project-b'});if(!replacement.ok)throw new RangeError(replacement.refusal.message)
  const qa=runPromotionQaV1({source,capability:product,defaultInstance:defaultInstance.value.scene,replacementInstance:replacement.value.scene,durationTicks,ticksPerSecond:SANVERSE_TICKS_PER_SECOND,composition,sampleTicks:Object.freeze([0,720_000,2_160_000,3_600_000,durationTicks])})
  const registered=registerPromotedCapabilityV1(createPromotionRegistryV1(),product,qa,Object.freeze({schemaVersion:'sanverse.promotion-registration-confirmation/v1',id:'confirmation:promotion-review',candidateId:candidate.id,candidateRevision:candidate.revision,authority:'system-policy',confirmedAt:'2026-08-26T09:10:00.000Z'}),Object.freeze({posterRef:'frame://promotion-review/promoted/poster',reviewRef:'review://promotion-review/promoted/1x'}));if(!registered.ok)throw new RangeError(registered.refusal.message)
  return Object.freeze({source,candidate,parameterization,classification,product,qa,registered:registered.value.entry,libraryDetail:promotedCapabilityToLibraryDetailV1(registered.value.entry),sourceOperations:compiled.value.operations})
}

export function PromotionReviewLab(){
  const [tick,setTick]=useState(0),[fullPlayback,setFullPlayback]=useState(false);const playback=useRef({anchorTime:0,anchorTicks:0})
  const model=useMemo(()=>buildPromotionReviewModel(),[])
  const context=useMemo(()=>Object.freeze({localTicks:tick,durationTicks,ticksPerSecond:SANVERSE_TICKS_PER_SECOND,composition,reducedMotion:false}),[tick])
  const projectBOps=useMemo(()=>Object.freeze<MotionGraphOperationV1[]>([...model.sourceOperations,setText('reuse:title','cost-card.title','Retention compounds faster'),setText('reuse:value-label','cost-card.value.label','Retention value created'),setText('reuse:value-number','cost-card.value.number','82%'),setText('reuse:footer','cost-card.footer','Same design language · different business story'),setColor('reuse:accent-number','cost-card.value.number','#FF7A1A'),setColor('reuse:accent-label','cost-card.value.label','#FF7A1A')]),[model])
  useEffect(()=>{playback.current={anchorTime:performance.now(),anchorTicks:0};let frame=0;const animate=(now:number)=>{const next=advancePlaybackTicks({anchorTicks:playback.current.anchorTicks,elapsedMilliseconds:Math.max(0,now-playback.current.anchorTime),speed:1,durationTicks,loop:false});setTick(next.ticks);if(next.ended){setFullPlayback(true);return}frame=requestAnimationFrame(animate)};frame=requestAnimationFrame(animate);return()=>cancelAnimationFrame(frame)},[])
  const parity=model.qa.findings.every(item=>item.code!=='PROMOTION_VISUAL_REAPPROVAL_REQUIRED'),seconds=tick/SANVERSE_TICKS_PER_SECOND
  const Preview=({title,ops,marker}:{title:string;ops:readonly MotionGraphOperationV1[];marker:string})=><div style={panel} data-promotion-preview={marker}><div style={{display:'flex',justifyContent:'space-between',marginBottom:8}}><strong>{title}</strong><span style={badge}>{(seconds).toFixed(2)} / 5.00s</span></div><div style={{borderRadius:9,overflow:'hidden',border:'1px solid #292929',aspectRatio:'16 / 9',background:'#050505'}}><MotionCompositionFrame composition={composition} displayScale={.28} background="#050505"><MotionComponentHost module={CostValueCardModule} props={DEFAULT_COST_VALUE_CARD_PROPS} style={DEFAULT_COST_VALUE_CARD_STYLE} context={context} graphOperations={ops} selectedGraphNodeId="cost-card.value" /></MotionCompositionFrame></div></div>
  return <main style={page} data-promotion-review="true" data-promotion-current-tick={tick} data-promotion-duration-ticks={durationTicks} data-promotion-full-playback={fullPlayback?'true':'false'} data-promotion-qa={model.qa.ok?'passed':'failed'} data-default-parity={parity?'true':'false'} data-project-b-reuse="true" data-origin={model.libraryDetail.origin} data-reuse-status={model.libraryDetail.reuseStatus} data-deep-editability="true">
    <header style={{maxWidth:1240,margin:'0 auto 16px',display:'flex',justifyContent:'space-between',gap:16,alignItems:'end',flexWrap:'wrap'}}><div><div style={label}>Sanverse Creative Engine V1.1</div><h1 style={{margin:'6px 0 4px',fontSize:28}}>Promotion → Parameterization → Reuse</h1><p style={{margin:0,color:'#999',fontSize:13}}>Approved Project A becomes a reusable generated capability; Project B changes the content and accent while keeping the graph editable.</p></div><span style={badge}>{fullPlayback?'✓ Project B full 1× playback':'▶ Project B playing at 1×'}</span></header>
    <section style={{maxWidth:1240,margin:'0 auto',display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><Preview title="Project A · approved source" ops={model.sourceOperations} marker="source"/><Preview title="Promoted default · parity fixture" ops={model.sourceOperations} marker="promoted-default"/></section>
    <section style={{maxWidth:1240,margin:'12px auto 0',display:'grid',gridTemplateColumns:'minmax(0,1fr) 350px',gap:12}}><Preview title="Project B · reused + adapted" ops={projectBOps} marker="project-b"/><aside style={{display:'grid',gap:10,alignContent:'start'}}>
      <div style={panel}><div style={label}>Library status</div><div style={{display:'flex',gap:7,flexWrap:'wrap',marginTop:8}}><span style={badge}>REUSABLE</span><span style={badge}>origin: GENERATED</span><span style={badge}>QA: PASSED</span><span style={badge}>editability: FULL</span></div></div>
      <div style={panel}><div style={label}>Parameterization</div><div data-promotion-parameter-count={model.parameterization.parameters.length} style={{marginTop:8,display:'grid',gap:5}}>{model.parameterization.parameters.map(item=><div key={item.id} style={{display:'grid',gridTemplateColumns:'18px 1fr auto',gap:6,fontSize:11,alignItems:'center'}}><span>{item.status==='rejected'?'×':'✓'}</span><span>{item.proposedPublicPath}</span><span style={{color:'#777'}}>{item.confidence}</span></div>)}</div><div style={{marginTop:8,fontSize:11,color:'#777'}}>{model.parameterization.frozenDesignProperties.length} design properties explicitly frozen.</div></div>
      <div style={panel}><div style={label}>Classification + recipe</div><div style={{marginTop:8,fontSize:12,lineHeight:1.55}}><strong>{model.classification.recommendedKind.toUpperCase()}</strong><br/><span style={{color:'#999'}}>Motion Recipe extracted from {model.source.sourceMotionPlanId} and remains role-based.</span></div></div>
      <div style={panel} data-library-promoted-detail="true"><div style={label}>Lineage</div><div style={{marginTop:8,fontSize:11,lineHeight:1.6,color:'#aaa'}}>Generated from <strong style={{color:'#eee'}}>{model.libraryDetail.lineage.sourceSceneId}</strong><br/>Project {model.libraryDetail.lineage.sourceProjectId}<br/>Approval {model.libraryDetail.lineage.motionApprovalId}<br/>Promotion {model.libraryDetail.lineage.promotionCandidateId} r{model.libraryDetail.lineage.promotionRevision}<br/>Evidence: poster + canonical 1× review</div></div>
      <div style={panel}><div style={label}>Deep editability</div><div style={{marginTop:8,fontSize:11,lineHeight:1.6,color:'#aaa'}}>C3 Layers · C4 Timeline · C5 Curves · C6 Nodes<br/>semantic node: <strong style={{color:'#eee'}}>cost-card.value</strong><br/>No opaque promoted runtime.</div></div>
    </aside></section>
  </main>
}
