import { describe,expect,it } from 'vitest'
import { createSanverseToolRegistryV1,registerCreativeEngineV12ToolsV1,registerCreativeEngineV13ToolsV1,SOURCE_AWARE_TOOL_IDS_V12,CREATIVE_ENGINE_V13_TOOL_IDS } from '@sanverse/motion-agent-tools'
import { createSanverseMcpServerV1,MCP_PROTOCOL_VERSION_META_KEY,MCP_PROTOCOL_VERSION_V1,SANVERSE_SANDBOX_META_KEY,type McpJsonRpcResponseV1 } from './server.ts'

const meta=(sandboxId?:string)=>Object.freeze({[MCP_PROTOCOL_VERSION_META_KEY]:MCP_PROTOCOL_VERSION_V1,...(sandboxId?{[SANVERSE_SANDBOX_META_KEY]:sandboxId}:{})})
const resultOf=(response:McpJsonRpcResponseV1):Record<string,unknown>=>('result'in response&&response.result&&typeof response.result==='object'?response.result as Record<string,unknown>:{})
const structured=(response:McpJsonRpcResponseV1):Record<string,unknown>=>{const result=resultOf(response);return result.structuredContent&&typeof result.structuredContent==='object'?result.structuredContent as Record<string,unknown>:result}
const state={schemaVersion:'sanverse.camera-depth-control-state/v1',rig:{schemaVersion:'sanverse.camera-rig/v1',id:'camera:main',durationTicks:1_440_000,positionX:{kind:'constant',value:0},positionY:{kind:'constant',value:0},zoom:{kind:'constant',value:1}},bindings:[]}

describe('Creative Engine V1.3 thin MCP exposure',()=>{
  it('lists the already-registered V1.2 + V1.3 tools with no MCP-owned duplicate surface',async()=>{const registry=registerCreativeEngineV13ToolsV1(registerCreativeEngineV12ToolsV1(createSanverseToolRegistryV1())),server=createSanverseMcpServerV1(registry,{version:'1.3.0'}),response=await server.handle({jsonrpc:'2.0',id:1,method:'tools/list',params:{_meta:meta()}}),tools=Array.isArray(resultOf(response).tools)?resultOf(response).tools as Array<Record<string,unknown>>:[];const expected=[...SOURCE_AWARE_TOOL_IDS_V12,...CREATIVE_ENGINE_V13_TOOL_IDS].sort();expect(tools.map(tool=>String(tool.name)).sort()).toEqual(expected);expect(registry.list().map(tool=>tool.id).sort()).toEqual(expected)})
  it('preserves the internal camera sandbox fence through generic tools/call',async()=>{const registry=registerCreativeEngineV13ToolsV1(registerCreativeEngineV12ToolsV1(createSanverseToolRegistryV1())),server=createSanverseMcpServerV1(registry,{version:'1.3.0'});const refused=await server.handle({jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'camera.set-zoom',arguments:{state,zoom:1.25},_meta:meta()}});expect(structured(refused)).toMatchObject({ok:false,refusal:{code:'SANDBOX_CONTEXT_REQUIRED'}});const accepted=await server.handle({jsonrpc:'2.0',id:3,method:'tools/call',params:{name:'camera.set-zoom',arguments:{state,zoom:1.25},_meta:meta('sandbox:v13')}});expect(structured(accepted)).toMatchObject({ok:true,value:{rig:{zoom:{kind:'constant',value:1.25}}}})})
  it('returns B8 evidence intelligence through the same generic adapter without project mutation authority',async()=>{const registry=registerCreativeEngineV13ToolsV1(registerCreativeEngineV12ToolsV1(createSanverseToolRegistryV1())),server=createSanverseMcpServerV1(registry,{version:'1.3.0'}),preferences=[['p1','a'],['p2','b'],['p3','b']].map(([id,projectId])=>({schemaVersion:'sanverse.creative-preference-evidence/v1',id,projectId,kind:'owner-accepted',dimension:'camera-policy',value:'restrained',contextTags:['talking-head']})),response=await server.handle({jsonrpc:'2.0',id:4,method:'tools/call',params:{name:'preference.build-intelligence',arguments:{preferences,failures:[]},_meta:meta()}});expect(structured(response)).toMatchObject({ok:true,value:{promoted:[{dimension:'camera-policy',value:'restrained'}],policy:{automaticMutation:false}}})})
})
