import { describe, expect, it } from 'vitest'
import { createSanverseToolRegistryV1, registerCreativeEngineV13ToolsV1, registerCreativeEngineV14ToolsV1, CREATIVE_ENGINE_V13_TOOL_IDS, CREATIVE_ENGINE_V14_TOOL_IDS } from '@sanverse/motion-agent-tools'
import { createSanverseMcpServerV1, MCP_PROTOCOL_VERSION_META_KEY, MCP_PROTOCOL_VERSION_V1, SANVERSE_SANDBOX_META_KEY, type McpJsonRpcResponseV1 } from './server.ts'

const meta=(sandboxId?:string)=>Object.freeze({[MCP_PROTOCOL_VERSION_META_KEY]:MCP_PROTOCOL_VERSION_V1,...(sandboxId?{[SANVERSE_SANDBOX_META_KEY]:sandboxId}:{})})
const resultOf=(response:McpJsonRpcResponseV1):Record<string,unknown>=>('result'in response&&response.result&&typeof response.result==='object'?response.result as Record<string,unknown>:{})
const structured=(response:McpJsonRpcResponseV1):Record<string,unknown>=>{const result=resultOf(response);return result.structuredContent&&typeof result.structuredContent==='object'?result.structuredContent as Record<string,unknown>:result}
const registry=()=>registerCreativeEngineV14ToolsV1(registerCreativeEngineV13ToolsV1(createSanverseToolRegistryV1()))

describe('Creative Engine V1.4 thin MCP Expert Motion exposure',()=>{
  it('lists the proven V1.3 + V1.4 internal registry without an MCP-owned duplicate surface',async()=>{const toolsRegistry=registry(),server=createSanverseMcpServerV1(toolsRegistry,{version:'1.4.0'}),response=await server.handle({jsonrpc:'2.0',id:1,method:'tools/list',params:{_meta:meta()}}),tools=Array.isArray(resultOf(response).tools)?resultOf(response).tools as Array<Record<string,unknown>>:[],expected=[...CREATIVE_ENGINE_V13_TOOL_IDS,...CREATIVE_ENGINE_V14_TOOL_IDS].sort();expect(tools.map(tool=>String(tool.name)).sort()).toEqual(expected);expect(toolsRegistry.list().map(tool=>tool.id).sort()).toEqual(expected)})
  it('preserves the internal Expert Motion sandbox fence through generic tools/call',async()=>{const server=createSanverseMcpServerV1(registry(),{version:'1.4.0'});const refused=await server.handle({jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'expert.instantiate-recipe',arguments:{recipeId:'expert.radial-payoff',width:960,height:540,seed:77},_meta:meta()}});expect(structured(refused)).toMatchObject({ok:false,refusal:{code:'SANDBOX_CONTEXT_REQUIRED'}});const accepted=await server.handle({jsonrpc:'2.0',id:3,method:'tools/call',params:{name:'expert.instantiate-recipe',arguments:{recipeId:'expert.radial-payoff',width:960,height:540,seed:77},_meta:meta('sandbox:v14')}});expect(structured(accepted)).toMatchObject({ok:true,value:{kind:'particles',program:'radial-burst',seed:77}})})
  it('cannot turn arbitrary shader source into an expert runtime through MCP',async()=>{const server=createSanverseMcpServerV1(registry(),{version:'1.4.0'}),provenance={schemaVersion:'sanverse.external-motion-provenance/v1',sourceKind:'shader',sourceName:'owner shader',rightsClass:'owner-authored',attributionRequired:false,reusableLibraryAllowed:true,projectUseAllowed:true,aiModificationAllowed:true,restrictions:[]},source=JSON.stringify({schemaVersion:'sanverse.shader-subset/v1',program:'user-glsl',width:960,height:540,seed:1,parameters:{frequency:1,amplitude:1,hueShift:0,scale:1},glsl:'void main(){}'}),response=await server.handle({jsonrpc:'2.0',id:4,method:'tools/call',params:{name:'external.inspect-shader',arguments:{assetId:'shader:unsafe',source,provenance},_meta:meta()}});expect(structured(response)).toMatchObject({ok:false,refusal:{code:'EXPERT_SOURCE_UNSAFE'}})})
})
