import { creativeRefusal,creativeValidationOk,type CreativeValidationResultV1 } from '@sanverse/motion-contract'
import { keyframed,type MotionKeyframeV1,type MotionMaskInstanceV1 } from '@sanverse/motion-graph'
import { lerp } from '@sanverse/motion-primitives'
export interface SubjectMatteSampleV1 { readonly tick:number; readonly x:number; readonly y:number; readonly width:number; readonly height:number; readonly confidence:number }
export interface CanonicalSubjectMatteV1 { readonly schemaVersion:'sanverse.subject-matte/v1'; readonly id:string; readonly sourceId:string; readonly provider:'imported'|'local'; readonly samples:readonly SubjectMatteSampleV1[] }
const record=(v:unknown):v is Record<string,unknown>=>Boolean(v)&&typeof v==='object'&&!Array.isArray(v)
const finite=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v)
const boundedId=(v:unknown):v is string=>typeof v==='string'&&v.trim().length>0&&v.length<=240
export const validateCanonicalSubjectMatteV1=(input:unknown):CreativeValidationResultV1<CanonicalSubjectMatteV1>=>{
  if(!record(input)||input.schemaVersion!=='sanverse.subject-matte/v1')return creativeRefusal('UNSUPPORTED_SUBJECT_MATTE_VERSION','Subject matte must use sanverse.subject-matte/v1.')
  if(!boundedId(input.id)||!boundedId(input.sourceId)||!['imported','local'].includes(String(input.provider))||!Array.isArray(input.samples)||input.samples.length===0)return creativeRefusal('INVALID_SUBJECT_MATTE','Subject matte identity/provider/samples are invalid.')
  let previous=-1
  for(const raw of input.samples as unknown[]){if(!record(raw)||!Number.isSafeInteger(raw.tick)||Number(raw.tick)<0||Number(raw.tick)<previous||![raw.x,raw.y,raw.width,raw.height,raw.confidence].every(finite)||Number(raw.width)<=0||Number(raw.height)<=0||Number(raw.confidence)<0||Number(raw.confidence)>1)return creativeRefusal('INVALID_SUBJECT_MATTE','Subject matte samples require ordered exact ticks, finite positive bounds and confidence in [0,1].');previous=Number(raw.tick)}
  return creativeValidationOk(input as unknown as CanonicalSubjectMatteV1)
}
export const createImportedSubjectMatteV1=(id:string,sourceId:string,samples:readonly SubjectMatteSampleV1[]):CanonicalSubjectMatteV1=>{const candidate:Object=Object.freeze({schemaVersion:'sanverse.subject-matte/v1',id,sourceId,provider:'imported',samples:Object.freeze([...samples].sort((a,b)=>a.tick-b.tick))});const valid=validateCanonicalSubjectMatteV1(candidate);if(!valid.ok)throw new RangeError(valid.refusal.message);return valid.value}
export const evaluateSubjectMatteV1=(matte:CanonicalSubjectMatteV1,tick:number):SubjectMatteSampleV1=>{const valid=validateCanonicalSubjectMatteV1(matte);if(!valid.ok)throw new RangeError(valid.refusal.message);if(!Number.isSafeInteger(tick)||tick<0)throw new RangeError('Subject matte evaluation requires a non-negative exact tick.');const s=matte.samples;if(tick<=s[0]!.tick)return s[0]!;if(tick>=s.at(-1)!.tick)return s.at(-1)!;let r=1;while(s[r]!.tick<=tick)r+=1;const a=s[r-1]!,b=s[r]!,p=(tick-a.tick)/(b.tick-a.tick);return Object.freeze({tick,x:lerp(a.x,b.x,p),y:lerp(a.y,b.y,p),width:lerp(a.width,b.width,p),height:lerp(a.height,b.height,p),confidence:lerp(a.confidence,b.confidence,p)})}
const keys=(matte:CanonicalSubjectMatteV1,property:'x'|'y'|'width'|'height'):readonly MotionKeyframeV1<number>[]=>Object.freeze(matte.samples.map((s,i)=>Object.freeze({id:`${matte.id}:${property}:${i}`,tick:s.tick,value:s[property],interpolation:'linear' as const})))
export const materializeSubjectMatteToMaskV1=(matte:CanonicalSubjectMatteV1,base:MotionMaskInstanceV1):MotionMaskInstanceV1=>{const valid=validateCanonicalSubjectMatteV1(matte);if(!valid.ok)throw new RangeError(valid.refusal.message);return Object.freeze({...base,x:keyframed(keys(matte,'x')),y:keyframed(keys(matte,'y')),width:keyframed(keys(matte,'width')),height:keyframed(keys(matte,'height'))})}
export interface SubjectQaFindingV1 { readonly code:'MATTE_UNAVAILABLE'|'EDGE_CONFIDENCE'|'SUBJECT_OUT_OF_FRAME'; readonly tick:number; readonly message:string }
export const runSubjectQaV1=(matte:CanonicalSubjectMatteV1|null):readonly SubjectQaFindingV1[]=>matte===null?Object.freeze([{code:'MATTE_UNAVAILABLE',tick:0,message:'Subject matte is unavailable.'}]):Object.freeze(matte.samples.flatMap(s=>{const f:SubjectQaFindingV1[]=[];if(s.confidence<.5)f.push({code:'EDGE_CONFIDENCE',tick:s.tick,message:'Subject matte confidence is low.'});if(s.x<0||s.y<0||s.x+s.width>1||s.y+s.height>1)f.push({code:'SUBJECT_OUT_OF_FRAME',tick:s.tick,message:'Subject matte leaves source bounds.'});return f}))
