import type { MotionCompositionV1 } from '@sanverse/motion-contract'
import type { MotionPointV1 } from '@sanverse/motion-primitives'
import type { SurfaceCornersV1 } from './contracts.ts'
export interface MotionSurfaceSampleV1 { readonly tick:number; readonly corners:SurfaceCornersV1; readonly confidence:number }
export interface SurfaceProjectionV1 { readonly matrix:readonly number[]; readonly cssMatrix3d:string }
const solve=(A:number[][],b:number[]):number[]=>{const n=b.length;const m=A.map((row,i)=>[...row,b[i]!]);for(let c=0;c<n;c++){let pivot=c;for(let r=c+1;r<n;r++)if(Math.abs(m[r]![c]!)>Math.abs(m[pivot]![c]!))pivot=r;[m[c],m[pivot]]=[m[pivot]!,m[c]!];const d=m[c]![c]!;if(Math.abs(d)<1e-10)throw new RangeError('Surface quad is singular.');for(let j=c;j<=n;j++)m[c]![j]/=d;for(let r=0;r<n;r++){if(r===c)continue;const f=m[r]![c]!;for(let j=c;j<=n;j++)m[r]![j]-=f*m[c]![j]!}}return m.map(row=>row[n]!)}
export const projectSurfaceQuadV1=(content:Readonly<{width:number;height:number}>,quad:SurfaceCornersV1,composition:MotionCompositionV1):SurfaceProjectionV1=>{if(content.width<=0||content.height<=0)throw new RangeError('Surface content rectangle must be positive.');const dst=[quad.topLeft,quad.topRight,quad.bottomRight,quad.bottomLeft].map(p=>({x:p.x*composition.width,y:p.y*composition.height}));const src=[{x:0,y:0},{x:content.width,y:0},{x:content.width,y:content.height},{x:0,y:content.height}];const A:number[][]=[],b:number[]=[];for(let i=0;i<4;i++){const s=src[i]!,d=dst[i]!;A.push([s.x,0,s.y,0,1,0,-d.x*s.x,-d.x*s.y]);b.push(d.x);A.push([0,s.x,0,s.y,0,1,-d.y*s.x,-d.y*s.y]);b.push(d.y)}const [a,b1,c,d,e,f,g,h]=solve(A,b);const matrix=[a,b1,0,g,c,d,0,h,0,0,1,0,e,f,0,1].map(v=>Math.abs(v)<1e-12?0:v);return Object.freeze({matrix:Object.freeze(matrix),cssMatrix3d:`matrix3d(${matrix.map(v=>Number(v.toFixed(9))).join(',')})`})}
const signedArea=(c:SurfaceCornersV1)=>{const p=[c.topLeft,c.topRight,c.bottomRight,c.bottomLeft];return p.reduce((sum,a,i)=>{const b=p[(i+1)%4]!;return sum+a.x*b.y-b.x*a.y},0)/2}
export interface SurfaceQaFindingV1 { readonly code:'SURFACE_INVERSION'|'OUT_OF_FRAME'|'LOW_CONFIDENCE'|'DEGENERATE_SURFACE'; readonly tick:number; readonly message:string }
export const runSurfaceQaV1=(samples:readonly MotionSurfaceSampleV1[]):readonly SurfaceQaFindingV1[]=>Object.freeze(samples.flatMap(s=>{const f:SurfaceQaFindingV1[]=[];const points=[s.corners.topLeft,s.corners.topRight,s.corners.bottomRight,s.corners.bottomLeft];const area=signedArea(s.corners);if(area<=0)f.push({code:'SURFACE_INVERSION',tick:s.tick,message:'Surface corner winding is inverted.'});if(Math.abs(area)<.0001)f.push({code:'DEGENERATE_SURFACE',tick:s.tick,message:'Surface area is degenerate.'});if(points.some(p=>p.x<0||p.x>1||p.y<0||p.y>1))f.push({code:'OUT_OF_FRAME',tick:s.tick,message:'Surface corners leave source bounds.'});if(s.confidence<.5)f.push({code:'LOW_CONFIDENCE',tick:s.tick,message:'Surface confidence is low.'});return f}))
