import { describe,expect,it } from 'vitest'
import { constant,createMotionScene,evaluateScene,nodeBase,type MotionShapeNodeV1 } from '@sanverse/motion-graph'
import { SANVERSE_TICKS_PER_SECOND } from '@sanverse/motion-primitives'
import { ColorMarkerTrackingProviderV1,applyTrackRepairV1,compileTrackBindingAtTickV1,evaluateMotionTrackV1,runTrackQaV1,type MotionTrackV1,type TrackingFrameRgbaV1 } from './index.ts'

const composition={width:1000,height:500,fpsNumerator:30,fpsDenominator:1} as const
const shape:MotionShapeNodeV1={...nodeBase('callout','Callout','root'),type:'shape',shape:'rounded-rectangle',width:constant(160),height:constant(70),fillColor:constant('#fff'),strokeColor:constant('#000'),strokeWidth:constant(1),radius:constant(12),transform:{...nodeBase('x','x',null).transform,positionX:constant(25),positionY:constant(-15)}}
const root={...nodeBase('root','Root',null),type:'group' as const,childIds:['callout'] as const}
const scene=createMotionScene({componentId:'source-aware.test',componentVersion:1,rootNodeId:'root',nodes:{root,callout:shape},semanticParts:[{id:'callout',label:'Callout',role:'content-group',nodeIds:['callout']}],exposures:[],layout:{mode:'manual',ownership:[],formatOverrides:[]},supportedAspectRatios:['16:9']})
const track:MotionTrackV1={schemaVersion:'sanverse.motion-track/v1',id:'track:phone',sourceId:'source:demo',sourceStartTick:0,sourceEndTick:SANVERSE_TICKS_PER_SECOND,target:{kind:'object',label:'phone'},samples:[{tick:0,x:.2,y:.4,scaleX:1,scaleY:1,rotation:0,visibility:1,confidence:.98},{tick:SANVERSE_TICKS_PER_SECOND,x:.8,y:.6,scaleX:1.4,scaleY:1.2,rotation:20,visibility:1,confidence:.95}],interpolation:{mode:'linear'},status:'valid',metadata:{coordinateSpace:'normalized-source',provider:'fixture',materializedAt:'test'}}

describe('C9 canonical tracking',()=>{
  it('evaluates the same exact tick after direct/backward/random access',()=>{const tick=720_000;const a=evaluateMotionTrackV1(track,tick),b=evaluateMotionTrackV1(track,1_300_000),c=evaluateMotionTrackV1(track,tick);expect(a).toEqual(c);expect(a).not.toEqual(b)})
  it('composes tracked base + user offset + normal Motion Graph transform',()=>{const ops=compileTrackBindingAtTickV1(scene,track,{schemaVersion:'sanverse.track-binding/v1',id:'binding:callout',trackId:track.id,nodeId:'callout',followMode:'position+scale',offset:{x:10,y:5,scaleX:1,scaleY:1,rotation:0},anchor:{x:0,y:0},smoothingPolicy:'none'},720_000,composition);const x=ops.find(op=>op.type==='set-property'&&op.target.property==='transform.positionX');const y=ops.find(op=>op.type==='set-property'&&op.target.property==='transform.positionY');expect(x&&x.type==='set-property'&&x.value).toEqual(constant(535));expect(y&&y.type==='set-property'&&y.value).toEqual(constant(240))})
  it('finds QA failures and repairs a short sample gap through typed replacement',()=>{const broken={...track,samples:[track.samples[0]!,{...track.samples[1]!,tick:2_880_000,x:4}],sourceEndTick:2_880_000} as MotionTrackV1;const qa=runTrackQaV1(broken,{maxGapTicks:1_000_000,maxNormalizedJump:.5});expect(qa.findings.some(f=>f.code==='IMPOSSIBLE_JUMP')).toBe(true);expect(qa.findings.some(f=>f.code==='MISSING_SAMPLES')).toBe(true);const repaired=applyTrackRepairV1(broken,{type:'replace-samples',startTick:0,endTick:2_880_000,samples:track.samples});expect(repaired.ok).toBe(true)})
  it('materializes an actual automatic color-marker tracking route from RGBA frames',async()=>{const frame=(tick:number,x:number):TrackingFrameRgbaV1=>{const width=8,height=4,rgba=new Uint8ClampedArray(width*height*4);for(let y=1;y<=2;y++)for(let xx=x;xx<=x+1;xx++){const i=(y*width+xx)*4;rgba[i]=20;rgba[i+1]=240;rgba[i+2]=30;rgba[i+3]=255}return{tick,width,height,rgba}};const provider=new ColorMarkerTrackingProviderV1();const result=await provider.track({id:'track:auto',sourceId:'source:encoded-video',target:{kind:'object',label:'green marker'},frames:[frame(0,1),frame(720_000,4)],color:{r:20,g:240,b:30,tolerance:12},minimumPixels:2});expect(result.ok).toBe(true);if(!result.ok)return;expect(result.value.metadata.provider).toBe('color-marker-v1');expect(result.value.samples[1]!.x).toBeGreaterThan(result.value.samples[0]!.x)})
})
