import { creativeOperationOk,creativeOperationRefusal,type CreativeOperationResultV1,type MotionCompositionV1 } from '@sanverse/motion-contract'
import { constant,evaluateScene,type MotionGraphOperationV1,type MotionSceneV1 } from '@sanverse/motion-graph'
import { easeInCubic,easeInOutCubic,easeOutCubic,lerp,SANVERSE_TICKS_PER_SECOND,type MotionPointV1 } from '@sanverse/motion-primitives'
import { validateMotionTrackV1,type MotionTrackV1,type ResolvedTrackSampleV1,type SurfaceCornersV1,type TrackBindingV1,type TrackSampleV1,type TrackTargetV1 } from './contracts.ts'

const clamp01=(v:number)=>Math.max(0,Math.min(1,v))
const easing=(track:MotionTrackV1,p:number)=>track.interpolation.mode!=='canonical-curve'?p:track.interpolation.curve==='ease-in-cubic'?easeInCubic(p):track.interpolation.curve==='ease-out-cubic'?easeOutCubic(p):easeInOutCubic(p)
const interp=(a:number|undefined,b:number|undefined,p:number,fallback:number)=>lerp(a??fallback,b??fallback,p)
const corner=(a:MotionPointV1,b:MotionPointV1,p:number):MotionPointV1=>Object.freeze({x:lerp(a.x,b.x,p),y:lerp(a.y,b.y,p)})
const surface=(a:SurfaceCornersV1|undefined,b:SurfaceCornersV1|undefined,p:number):SurfaceCornersV1|undefined=>a&&b?Object.freeze({topLeft:corner(a.topLeft,b.topLeft,p),topRight:corner(a.topRight,b.topRight,p),bottomRight:corner(a.bottomRight,b.bottomRight,p),bottomLeft:corner(a.bottomLeft,b.bottomLeft,p)}):a??b
export const evaluateMotionTrackV1=(track:MotionTrackV1,atTick:number):ResolvedTrackSampleV1=>{
  const valid=validateMotionTrackV1(track);if(!valid.ok)throw new RangeError(valid.refusal.message);if(!Number.isSafeInteger(atTick)||atTick<0)throw new RangeError('Track evaluation requires a non-negative exact tick.')
  const samples=track.samples;if(atTick<=samples[0]!.tick)return Object.freeze({...samples[0]!,scaleX:samples[0]!.scaleX??1,scaleY:samples[0]!.scaleY??1,rotation:samples[0]!.rotation??0});if(atTick>=samples.at(-1)!.tick){const s=samples.at(-1)!;return Object.freeze({...s,scaleX:s.scaleX??1,scaleY:s.scaleY??1,rotation:s.rotation??0})}
  let right=1;while(right<samples.length&&samples[right]!.tick<=atTick)right+=1;const a=samples[right-1]!,b=samples[right]!;if(track.interpolation.mode==='hold')return Object.freeze({...a,tick:atTick,scaleX:a.scaleX??1,scaleY:a.scaleY??1,rotation:a.rotation??0});const p=easing(track,clamp01((atTick-a.tick)/(b.tick-a.tick)));return Object.freeze({tick:atTick,x:lerp(a.x,b.x,p),y:lerp(a.y,b.y,p),scaleX:interp(a.scaleX,b.scaleX,p,1),scaleY:interp(a.scaleY,b.scaleY,p,1),rotation:interp(a.rotation,b.rotation,p,0),visibility:lerp(a.visibility,b.visibility,p),confidence:lerp(a.confidence,b.confidence,p),...(surface(a.surfaceCorners,b.surfaceCorners,p)?{surfaceCorners:surface(a.surfaceCorners,b.surfaceCorners,p)!}:{})})
}
export const compileTrackBindingAtTickV1=(scene:MotionSceneV1,track:MotionTrackV1,binding:TrackBindingV1,tick:number,composition:MotionCompositionV1):readonly MotionGraphOperationV1[]=>{
  if(binding.trackId!==track.id)throw new RangeError('Track binding references a different track.');const node=scene.nodes[binding.nodeId];if(!node)throw new RangeError(`Unknown bound node ${binding.nodeId}.`);const tracked=evaluateMotionTrackV1(track,tick);const resolved=evaluateScene(scene,{localTicks:tick,durationTicks:Math.max(1,track.sourceEndTick),ticksPerSecond:SANVERSE_TICKS_PER_SECOND,composition,reducedMotion:false}).nodes[binding.nodeId]!;const ops:MotionGraphOperationV1[]=[];const add=(property:'transform.positionX'|'transform.positionY'|'transform.scaleX'|'transform.scaleY'|'transform.rotationDeg',value:number)=>ops.push(Object.freeze({operationId:`track:${binding.id}:${tick}:${property}`,type:'set-property',target:{nodeId:binding.nodeId,property},value:constant(value)}));add('transform.positionX',tracked.x*composition.width+binding.offset.x+resolved.transform.positionX);add('transform.positionY',tracked.y*composition.height+binding.offset.y+resolved.transform.positionY);if(binding.followMode==='position+scale'||binding.followMode==='full-transform'||binding.followMode==='surface'){add('transform.scaleX',tracked.scaleX*binding.offset.scaleX*resolved.transform.scaleX);add('transform.scaleY',tracked.scaleY*binding.offset.scaleY*resolved.transform.scaleY)}if(binding.followMode==='position+rotation'||binding.followMode==='full-transform'||binding.followMode==='surface')add('transform.rotationDeg',tracked.rotation+binding.offset.rotation+resolved.transform.rotationDeg);return Object.freeze(ops)
}

export interface TrackingFrameRgbaV1 { readonly tick:number; readonly width:number; readonly height:number; readonly rgba:Uint8ClampedArray }
export interface ColorMarkerTrackingRequestV1 { readonly id:string; readonly sourceId:string; readonly target:TrackTargetV1; readonly frames:readonly TrackingFrameRgbaV1[]; readonly color:Readonly<{r:number;g:number;b:number;tolerance:number}>; readonly minimumPixels:number }
export interface TrackingProviderV1 { readonly id:string; track(request:ColorMarkerTrackingRequestV1):Promise<CreativeOperationResultV1<MotionTrackV1>> }
export class ColorMarkerTrackingProviderV1 implements TrackingProviderV1 { readonly id='color-marker-v1';async track(request:ColorMarkerTrackingRequestV1):Promise<CreativeOperationResultV1<MotionTrackV1>>{if(!request.frames.length||request.minimumPixels<1)return creativeOperationRefusal('TRACKING_INPUT_INVALID','Tracking requires decoded RGBA frames and a positive pixel threshold.');const samples:TrackSampleV1[]=[];let found=0;for(const frame of [...request.frames].sort((a,b)=>a.tick-b.tick)){if(frame.rgba.length!==frame.width*frame.height*4)return creativeOperationRefusal('TRACKING_FRAME_INVALID','RGBA frame size does not match dimensions.');let count=0,sx=0,sy=0,minX=frame.width,minY=frame.height,maxX=-1,maxY=-1;for(let y=0;y<frame.height;y+=1)for(let x=0;x<frame.width;x+=1){const i=(y*frame.width+x)*4;const d=Math.abs(frame.rgba[i]!-request.color.r)+Math.abs(frame.rgba[i+1]!-request.color.g)+Math.abs(frame.rgba[i+2]!-request.color.b);if(d<=request.color.tolerance*3&&frame.rgba[i+3]!>0){count+=1;sx+=x+.5;sy+=y+.5;minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y)}}if(count>=request.minimumPixels){found+=1;const x=(sx/count)/frame.width,y=(sy/count)/frame.height,w=(maxX-minX+1)/frame.width,h=(maxY-minY+1)/frame.height;samples.push(Object.freeze({tick:frame.tick,x,y,scaleX:1,scaleY:1,rotation:0,visibility:1,confidence:Math.min(1,count/Math.max(request.minimumPixels*4,1)),...(request.target.kind==='surface'?{surfaceCorners:Object.freeze({topLeft:{x:minX/frame.width,y:minY/frame.height},topRight:{x:(maxX+1)/frame.width,y:minY/frame.height},bottomRight:{x:(maxX+1)/frame.width,y:(maxY+1)/frame.height},bottomLeft:{x:minX/frame.width,y:(maxY+1)/frame.height}})}:{})}))}else samples.push(Object.freeze({tick:frame.tick,x:samples.at(-1)?.x??.5,y:samples.at(-1)?.y??.5,visibility:0,confidence:0}))}const status=found===request.frames.length?'valid':found===0?'lost':'partial';const track:MotionTrackV1=Object.freeze({schemaVersion:'sanverse.motion-track/v1',id:request.id,sourceId:request.sourceId,sourceStartTick:request.frames[0]!.tick,sourceEndTick:request.frames.at(-1)!.tick,target:request.target,samples:Object.freeze(samples),interpolation:{mode:'linear' as const},status,metadata:{coordinateSpace:'normalized-source' as const,provider:this.id,materializedAt:'runtime'}});const valid=validateMotionTrackV1(track);return valid.ok?creativeOperationOk(track,1):creativeOperationRefusal(valid.refusal.code,valid.refusal.message,valid.refusal.details)}}
