import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import type { ComponentParityRecordV1, ComponentRegistrationDescriptorV1, MotionComponentIntegrationRecordV1 } from './contracts.ts'
import type { ComponentProductizationReportV1 } from './productization.ts'

export interface ComponentRegistrationLedgerV1 { readonly schemaVersion:'sanverse.component-registration-ledger/v1'; readonly components:readonly ComponentRegistrationDescriptorV1[] }
const emptyLedger=():ComponentRegistrationLedgerV1=>Object.freeze({schemaVersion:'sanverse.component-registration-ledger/v1',components:Object.freeze([])})

export const registrationBlockingReasons=(record:MotionComponentIntegrationRecordV1,parity:ComponentParityRecordV1|null,productization:ComponentProductizationReportV1|null):readonly string[]=>{
  const reasons:string[]=[]
  if(record.visualParityStatus!=='passed') reasons.push('VISUAL_PARITY_NOT_PASSED')
  if(record.productizationStatus!=='ready') reasons.push('PRODUCTIZATION_NOT_READY')
  if(record.determinismStatus!=='passed') reasons.push('DETERMINISM_NOT_PASSED')
  if(record.directSeekStatus!=='passed') reasons.push('DIRECT_SEEK_NOT_PASSED')
  if(record.semanticMappingStatus!=='passed') reasons.push('SEMANTIC_MAPPING_NOT_PASSED')
  if(record.c3Status!=='passed'||record.c4Status!=='passed'||record.c5Status!=='passed') reasons.push('COMPOSITOR_PROJECTION_NOT_PASSED')
  if(record.aiEditabilityStatus!=='passed') reasons.push('AI_EDITABILITY_NOT_PASSED')
  if(!record.canonicalVideoHash) reasons.push('CANONICAL_GOLDEN_VIDEO_MISSING')
  if(!parity||parity.status!=='passed') reasons.push('PARITY_RECORD_NOT_PASSED')
  if(parity&&parity.reviewer!=='owner'&&parity.reviewer!=='owner-batch-authorized-engineering-evidence') reasons.push('OWNER_INTEGRATED_PARITY_APPROVAL_REQUIRED')
  if(!productization||productization.status!=='ready') reasons.push('PRODUCTIZATION_REPORT_NOT_READY')
  return Object.freeze([...new Set(reasons)])
}

const ledgerPath=(repositoryRoot:string)=>join(resolve(repositoryRoot),'motion','component-intake','public-registration-ledger.json')
export const readRegistrationLedger=(repositoryRoot:string):ComponentRegistrationLedgerV1=>{
  const path=ledgerPath(repositoryRoot)
  return existsSync(path)?JSON.parse(readFileSync(path,'utf8')) as ComponentRegistrationLedgerV1:emptyLedger()
}

export const renderGeneratedRegistry=(components:readonly ComponentRegistrationDescriptorV1[]):string=>{
  const sorted=[...components].sort((a,b)=>a.componentId.localeCompare(b.componentId))
  const imports=sorted.map((entry)=>`import { ${entry.definitionExportName}, ${entry.moduleExportName} } from '${entry.moduleImportPath}'`).join('\n')
  const definitions=sorted.map((entry)=>`  ${entry.definitionExportName},`).join('\n')
  const modules=sorted.map((entry)=>`  [${entry.moduleExportName}.definition.id]: ${entry.moduleExportName},`).join('\n')
  return `import type { MotionComponentDefinitionV1, MotionComponentModuleV1 } from '@sanverse/motion-contract'\n${imports}${imports?'\n':''}\n/** Generated by motion:register. Do not hand-edit. */\nexport const INGESTED_PUBLIC_COMPONENT_DEFINITIONS = Object.freeze([\n${definitions}${definitions?'\n':''}] satisfies readonly MotionComponentDefinitionV1[])\nexport const INGESTED_PUBLIC_COMPONENT_MODULES_BY_ID: Readonly<Record<string, MotionComponentModuleV1<any, any>>> = Object.freeze({\n${modules}${modules?'\n':''}})\n`
}

export const registerProductizedComponent=(repositoryRoot:string,descriptor:ComponentRegistrationDescriptorV1,record:MotionComponentIntegrationRecordV1,parity:ComponentParityRecordV1|null,productization:ComponentProductizationReportV1|null):ComponentRegistrationLedgerV1=>{
  if(descriptor.componentId!==record.componentId||descriptor.componentVersion!==record.componentVersion) throw new Error('REGISTRATION_DESCRIPTOR_IDENTITY_MISMATCH')
  if(!/^\.\/[a-z0-9._/-]+\.(?:ts|tsx)$/iu.test(descriptor.moduleImportPath)||descriptor.moduleImportPath.includes('..')) throw new Error('REGISTRATION_MODULE_IMPORT_INVALID')
  if(!/^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(descriptor.moduleExportName)||!/^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(descriptor.definitionExportName)) throw new Error('REGISTRATION_EXPORT_NAME_INVALID')
  const blockers=registrationBlockingReasons(record,parity,productization)
  if(blockers.length) throw new Error(`REGISTRATION_BLOCKED: ${blockers.join(', ')}`)
  const current=readRegistrationLedger(repositoryRoot)
  if(current.components.some(entry=>entry.componentId===descriptor.componentId)) throw new Error(`DUPLICATE_PUBLIC_COMPONENT_ID: ${descriptor.componentId}`)
  const next:Object=Object.freeze({schemaVersion:'sanverse.component-registration-ledger/v1',components:Object.freeze([...current.components,descriptor].sort((a,b)=>a.componentId.localeCompare(b.componentId)))})
  const registryPath=join(resolve(repositoryRoot),'packages','motion-library','src','ingested','registry.generated.ts')
  const ledger=next as ComponentRegistrationLedgerV1
  const generated=renderGeneratedRegistry(ledger.components)
  mkdirSync(dirname(registryPath),{recursive:true});mkdirSync(dirname(ledgerPath(repositoryRoot)),{recursive:true})
  const registryTemp=`${registryPath}.tmp`;const ledgerTemp=`${ledgerPath(repositoryRoot)}.tmp`
  writeFileSync(registryTemp,generated,'utf8');writeFileSync(ledgerTemp,`${JSON.stringify(ledger,null,2)}\n`,'utf8')
  renameSync(registryTemp,registryPath);renameSync(ledgerTemp,ledgerPath(repositoryRoot))
  return ledger
}
