import { describe,expect,it } from 'vitest'
import { buildCreativePreferenceIntelligenceV1,type CreativeFailureEvidenceV1,type CreativePreferenceEvidenceV1 } from './preference-intelligence.ts'
const p=(id:string,projectId:string,value:string,kind:CreativePreferenceEvidenceV1['kind']='owner-accepted'):CreativePreferenceEvidenceV1=>({schemaVersion:'sanverse.creative-preference-evidence/v1',id,projectId,kind,dimension:'camera-policy',value,contextTags:['talking-head']})
const f=(id:string,projectId:string):CreativeFailureEvidenceV1=>({schemaVersion:'sanverse.creative-failure-evidence/v1',id,projectId,code:'CAMERA_TOO_AGGRESSIVE',family:'camera',contextTags:['talking-head'],resolution:'reduce depth and pan amplitude'})
describe('B8 preference and failure intelligence',()=>{
  it('never promotes a preference from one event or one project',()=>{const one=buildCreativePreferenceIntelligenceV1([p('p1','a','restrained')],[]);expect(one.ok).toBe(true);if(!one.ok)return;expect(one.value.promoted).toHaveLength(0);expect(one.value.candidates[0]?.blockedReasons).toContain('Fewer than three explicit positive owner signals.');const same=buildCreativePreferenceIntelligenceV1([p('p1','a','restrained'),p('p2','a','restrained'),p('p3','a','restrained')],[]);expect(same.ok&&same.value.promoted).toHaveLength(0)})
  it('promotes only repeated explicit evidence across projects with full explainability',()=>{const result=buildCreativePreferenceIntelligenceV1([p('p1','a','restrained'),p('p2','b','restrained'),p('p3','b','restrained')],[]);expect(result.ok).toBe(true);if(!result.ok)return;expect(result.value.promoted).toEqual([expect.objectContaining({dimension:'camera-policy',value:'restrained',positiveCount:3,projectCount:2,confidence:1,evidenceIds:['p1','p2','p3']})]);expect(result.value.policy.automaticMutation).toBe(false)})
  it('blocks promotion when explicit rejection or repeated competing preference exists',()=>{const evidence=[p('p1','a','restrained'),p('p2','b','restrained'),p('p3','b','restrained'),p('p4','c','restrained','owner-rejected'),p('p5','a','expressive'),p('p6','b','expressive')];const result=buildCreativePreferenceIntelligenceV1(evidence,[]);expect(result.ok).toBe(true);if(!result.ok)return;expect(result.value.promoted).toHaveLength(0);expect(result.value.candidates.find(item=>item.value==='restrained')?.blockedReasons.join(' ')).toMatch(/rejection|Competing/iu)})
  it('promotes recurring cross-project failures into explainable avoidance lessons, not hidden edits',()=>{const result=buildCreativePreferenceIntelligenceV1([], [f('f1','a'),f('f2','b')]);expect(result.ok).toBe(true);if(!result.ok)return;expect(result.value.failureLessons[0]).toMatchObject({code:'CAMERA_TOO_AGGRESSIVE',family:'camera',occurrenceCount:2,projectCount:2,resolutions:['reduce depth and pan amplitude']});expect(result.value.failureLessons[0]?.recommendation).toContain('Avoid repeating')})
  it('fails closed on duplicate or malformed evidence',()=>{expect(buildCreativePreferenceIntelligenceV1([p('same','a','restrained')],[f('same','b')])).toMatchObject({ok:false,refusal:{code:'INTELLIGENCE_EVIDENCE_DUPLICATE'}});expect(buildCreativePreferenceIntelligenceV1([{...p('x','a','restrained'),dimension:'unknown' as never}],[])).toMatchObject({ok:false,refusal:{code:'PREFERENCE_EVIDENCE_INVALID'}})})
})
