import { describe,expect,it } from 'vitest'
import { applyMotionOperations,constant,createMotionScene,evaluateScene,keyframed,nodeBase,type MotionSceneV1 } from '@sanverse/motion-graph'
import type { CameraRigV1,DepthBindingV1 } from './camera-depth.ts'
import { renderCameraDepthAtTickV1,validateCameraRigV1,validateDepthBindingsV1 } from './camera-depth.ts'

const composition={width:1000,height:500,fpsNumerator:30,fpsDenominator:1} as const
const duration=1_440_000
const scene=():MotionSceneV1=>{const root=nodeBase('root','Root',null),back=nodeBase('back','Background','root'),hero=nodeBase('hero','Hero','root');return createMotionScene({componentId:'sanverse.camera-depth-proof',componentVersion:1,rootNodeId:'root',nodes:Object.freeze({root:Object.freeze({...root,type:'group' as const,childIds:Object.freeze(['back','hero'])}),back:Object.freeze({...back,type:'shape' as const,shape:'rectangle' as const,width:constant(400),height:constant(220),fillColor:constant('#22334f'),strokeColor:constant('transparent'),strokeWidth:constant(0),radius:constant(0)}),hero:Object.freeze({...hero,type:'shape' as const,transform:Object.freeze({...hero.transform,positionX:keyframed([{id:'h0',tick:0,value:0,interpolation:'linear'},{id:'h1',tick:duration,value:100,interpolation:'linear'}])}),shape:'rounded-rectangle' as const,width:constant(180),height:constant(90),fillColor:constant('#39d0ff'),strokeColor:constant('#fff'),strokeWidth:constant(2),radius:constant(16)})}),semanticParts:Object.freeze([{id:'background',label:'Background',role:'surface' as const,nodeIds:Object.freeze(['back'])},{id:'hero',label:'Hero',role:'content-group' as const,nodeIds:Object.freeze(['hero'])}]),exposures:Object.freeze([]),layout:Object.freeze({mode:'manual' as const,ownership:Object.freeze([]),formatOverrides:Object.freeze([])}),supportedAspectRatios:Object.freeze(['16:9'])})}
const rig:CameraRigV1=Object.freeze({schemaVersion:'sanverse.camera-rig/v1',id:'camera:main',durationTicks:duration,positionX:keyframed([{id:'cx0',tick:0,value:0,interpolation:'linear'},{id:'cx1',tick:duration,value:100,interpolation:'linear'}]),positionY:constant(20),zoom:keyframed([{id:'cz0',tick:0,value:1,interpolation:'linear'},{id:'cz1',tick:duration,value:1.2,interpolation:'linear'}])})
const bindings:readonly DepthBindingV1[]=Object.freeze([{schemaVersion:'sanverse.depth-binding/v1',id:'depth:back',nodeId:'back',depth:.25},{schemaVersion:'sanverse.depth-binding/v1',id:'depth:hero',nodeId:'hero',depth:1}])

describe('V1.3 C10 camera/depth',()=>{
  it('validates a bounded exact-tick rig and refuses duplicate/unknown depth bindings',()=>{expect(validateCameraRigV1(rig).ok).toBe(true);expect(validateDepthBindingsV1(scene(),bindings).ok).toBe(true);expect(validateDepthBindingsV1(scene(),[...bindings,{...bindings[1]!,id:'depth:dup'}])).toMatchObject({ok:false,refusal:{code:'DEPTH_BINDING_INVALID'}});expect(validateDepthBindingsV1(scene(),[{schemaVersion:'sanverse.depth-binding/v1',id:'missing',nodeId:'missing',depth:1}])).toMatchObject({ok:false,refusal:{code:'DEPTH_NODE_MISSING'}})})
  it('creates stronger parallax/zoom on foreground than background using ordinary graph transforms',()=>{const result=renderCameraDepthAtTickV1({scene:scene(),rig,bindings,tick:720_000,composition});expect(result.ok).toBe(true);if(!result.ok)return;const resolved=evaluateScene(result.value.scene,{localTicks:720_000,durationTicks:duration,ticksPerSecond:1_440_000,composition,reducedMotion:false});expect(resolved.nodes.back?.transform).toMatchObject({positionX:-12.5,positionY:-5,scaleX:1.025,scaleY:1.025});expect(resolved.nodes.hero?.transform).toMatchObject({positionX:0,positionY:-20,scaleX:1.1,scaleY:1.1});expect(result.value.operations).toHaveLength(8)})
  it('is history-free: direct, backward and random-access evaluation at the same tick are identical',()=>{const base=scene(),input={scene:base,rig,bindings,composition};const direct=renderCameraDepthAtTickV1({...input,tick:360_000});const later=renderCameraDepthAtTickV1({...input,tick:1_200_000});const backward=renderCameraDepthAtTickV1({...input,tick:360_000});const random=renderCameraDepthAtTickV1({...input,tick:360_000});expect(later.ok).toBe(true);expect(backward).toEqual(direct);expect(random).toEqual(direct)})
  it('composes after source-aware/tracked graph transforms instead of replacing them',()=>{const tracked=applyMotionOperations(scene(),[{operationId:'tracked:x',type:'set-property',target:{nodeId:'hero',property:'transform.positionX'},value:constant(240)},{operationId:'tracked:y',type:'set-property',target:{nodeId:'hero',property:'transform.positionY'},value:constant(80)}],{durationTicks:duration});expect(tracked.ok).toBe(true);if(!tracked.ok)return;const result=renderCameraDepthAtTickV1({scene:tracked.scene,rig,bindings:[bindings[1]!],tick:720_000,composition});expect(result.ok).toBe(true);if(!result.ok)return;const resolved=evaluateScene(result.value.scene,{localTicks:720_000,durationTicks:duration,ticksPerSecond:1_440_000,composition,reducedMotion:false});expect(resolved.nodes.hero?.transform.positionX).toBe(190);expect(resolved.nodes.hero?.transform.positionY).toBe(60)})
  it('fails closed for invalid zoom/depth/ticks rather than extrapolating',()=>{expect(renderCameraDepthAtTickV1({scene:scene(),rig:{...rig,zoom:constant(8)},bindings,tick:0,composition})).toMatchObject({ok:false,refusal:{code:'CAMERA_INPUT_INVALID'}});expect(renderCameraDepthAtTickV1({scene:scene(),rig,bindings:[{...bindings[0]!,depth:3}],tick:0,composition})).toMatchObject({ok:false,refusal:{code:'DEPTH_BINDING_INVALID'}});expect(renderCameraDepthAtTickV1({scene:scene(),rig,bindings,tick:duration+1,composition})).toMatchObject({ok:false,refusal:{code:'CAMERA_TICK_INVALID'}})})
})
