import { describe,expect,it } from 'vitest'
import { constant,createMotionScene,nodeBase } from '@sanverse/motion-graph'
import type { CameraDepthControlStateV1 } from './semantic.ts'
import { applyCameraDepthControlV1 } from './semantic.ts'

const duration=1_440_000
const root=nodeBase('root','Root',null),back=nodeBase('back','Back','root'),hero=nodeBase('hero','Hero','root')
const scene=createMotionScene({componentId:'camera-semantic',componentVersion:1,rootNodeId:'root',nodes:{root:{...root,type:'group',childIds:['back','hero']},back:{...back,type:'shape',shape:'rectangle',width:constant(1),height:constant(1),fillColor:constant('#111111'),strokeColor:constant('transparent'),strokeWidth:constant(0),radius:constant(0)},hero:{...hero,type:'shape',shape:'rectangle',width:constant(.3),height:constant(.2),fillColor:constant('#ffffff'),strokeColor:constant('transparent'),strokeWidth:constant(0),radius:constant(0)}},semanticParts:[],exposures:[],layout:{mode:'manual',ownership:[],formatOverrides:[]},supportedAspectRatios:['16:9']})
const state:CameraDepthControlStateV1={schemaVersion:'sanverse.camera-depth-control-state/v1',rig:{schemaVersion:'sanverse.camera-rig/v1',id:'camera:main',durationTicks:duration,positionX:constant(0),positionY:constant(0),zoom:constant(1)},bindings:[]}

describe('V1.3 typed camera/depth semantic operations',()=>{
  it('sets bounded camera position/zoom without creating a second timeline',()=>{const positioned=applyCameraDepthControlV1(state,{type:'camera.set-position',x:120,y:-40});expect(positioned).toMatchObject({ok:true,value:{rig:{positionX:{kind:'constant',value:120},positionY:{kind:'constant',value:-40}}}});if(!positioned.ok)return;expect(applyCameraDepthControlV1(positioned.value,{type:'camera.set-zoom',zoom:1.4})).toMatchObject({ok:true,value:{rig:{zoom:{kind:'constant',value:1.4}}}})})
  it('adds/replaces exact-tick camera keyframes deterministically',()=>{const first=applyCameraDepthControlV1(state,{type:'camera.set-keyframe',property:'zoom',keyframe:{id:'z0',tick:0,value:1,interpolation:'linear'}});expect(first.ok).toBe(true);if(!first.ok)return;const second=applyCameraDepthControlV1(first.value,{type:'camera.set-keyframe',property:'zoom',keyframe:{id:'z1',tick:duration,value:1.5,interpolation:'linear'}});expect(second).toMatchObject({ok:true,value:{rig:{zoom:{kind:'keyframes',keyframes:[{id:'z0',tick:0},{id:'z1',tick:duration}]}}}});if(!second.ok)return;expect(applyCameraDepthControlV1(second.value,{type:'camera.set-keyframe',property:'zoom',keyframe:{id:'replacement',tick:duration,value:1.25,interpolation:'linear'}})).toMatchObject({ok:true,value:{rig:{zoom:{keyframes:[{id:'z0'},{id:'replacement',value:1.25}]}}}})})
  it('requires scene truth for depth changes and refuses unknown nodes',()=>{const binding={schemaVersion:'sanverse.depth-binding/v1' as const,id:'depth:hero',nodeId:'hero',depth:1};expect(applyCameraDepthControlV1(state,{type:'depth.set',binding})).toMatchObject({ok:false,refusal:{code:'DEPTH_SCENE_REQUIRED'}});expect(applyCameraDepthControlV1(state,{type:'depth.set',binding:{...binding,nodeId:'missing'}},scene)).toMatchObject({ok:false,refusal:{code:'DEPTH_NODE_MISSING'}});expect(applyCameraDepthControlV1(state,{type:'depth.set',binding},scene)).toMatchObject({ok:true,value:{bindings:[binding]}})})
  it('distributes ordered 2.5D depth across known nodes and stays bounded',()=>{const distributed=applyCameraDepthControlV1(state,{type:'depth.distribute',nodeIds:['back','hero'],minimumDepth:.2,maximumDepth:1.2},scene);expect(distributed).toMatchObject({ok:true,value:{bindings:[{nodeId:'back',depth:.2},{nodeId:'hero',depth:1.2}]}});expect(applyCameraDepthControlV1(state,{type:'depth.distribute',nodeIds:['back','hero'],minimumDepth:-1,maximumDepth:4},scene)).toMatchObject({ok:false,refusal:{code:'DEPTH_DISTRIBUTION_INVALID'}})})
  it('refuses unsafe zoom, last-key removal and missing depth references',()=>{expect(applyCameraDepthControlV1(state,{type:'camera.set-zoom',zoom:8})).toMatchObject({ok:false,refusal:{code:'CAMERA_ZOOM_INVALID'}});const keyed:CameraDepthControlStateV1={...state,rig:{...state.rig,zoom:{kind:'keyframes',keyframes:[{id:'only',tick:0,value:1,interpolation:'hold'}]}}};expect(applyCameraDepthControlV1(keyed,{type:'camera.remove-keyframe',property:'zoom',keyframeId:'only'})).toMatchObject({ok:false,refusal:{code:'CAMERA_KEYFRAME_LAST_REQUIRED'}});expect(applyCameraDepthControlV1(state,{type:'depth.remove',nodeId:'hero'})).toMatchObject({ok:false,refusal:{code:'DEPTH_BINDING_NOT_FOUND'}})})
})
