import type { MotionComponentDefinitionV1, MotionComponentModuleV1 } from '@sanverse/motion-contract'
import { CTA_PILL_DEFINITION, CtaPillModule } from './ch1-approved-components.tsx'
import { EXPLAINER_BOARD_DEFINITION, ExplainerBoardModule } from './ch1-approved-components.tsx'
import { FEATURE_MATRIX_DEFINITION, FeatureMatrixModule } from './ch1-approved-components.tsx'
import { FLOATING_VALUE_CLOUD_DEFINITION, FloatingValueCloudModule } from './ch1-approved-components.tsx'
import { FROSTED_ICON_RAIL_DEFINITION, FrostedIconRailModule } from './frosted-icon-rail.tsx'
import { KINETIC_PHRASE_DEFINITION, KineticPhraseModule } from './ch1-approved-components.tsx'
import { MEDIA_CUTAWAY_DEFINITION, MediaCutawayModule } from './ch1-approved-components.tsx'
import { MILESTONE_STAGE_DEFINITION, MilestoneStageModule } from './ch1-approved-components.tsx'
import { PROGRESSIVE_CHOICE_STACK_DEFINITION, ProgressiveChoiceStackModule } from './ch1-approved-components.tsx'
import { STAT_BURST_DEFINITION, StatBurstModule } from './ch1-approved-components.tsx'

/** Generated by motion:register. Do not hand-edit. */
export const INGESTED_PUBLIC_COMPONENT_DEFINITIONS = Object.freeze([
  CTA_PILL_DEFINITION,
  EXPLAINER_BOARD_DEFINITION,
  FEATURE_MATRIX_DEFINITION,
  FLOATING_VALUE_CLOUD_DEFINITION,
  FROSTED_ICON_RAIL_DEFINITION,
  KINETIC_PHRASE_DEFINITION,
  MEDIA_CUTAWAY_DEFINITION,
  MILESTONE_STAGE_DEFINITION,
  PROGRESSIVE_CHOICE_STACK_DEFINITION,
  STAT_BURST_DEFINITION,
] satisfies readonly MotionComponentDefinitionV1[])
export const INGESTED_PUBLIC_COMPONENT_MODULES_BY_ID: Readonly<Record<string, MotionComponentModuleV1<any, any>>> = Object.freeze({
  [CtaPillModule.definition.id]: CtaPillModule,
  [ExplainerBoardModule.definition.id]: ExplainerBoardModule,
  [FeatureMatrixModule.definition.id]: FeatureMatrixModule,
  [FloatingValueCloudModule.definition.id]: FloatingValueCloudModule,
  [FrostedIconRailModule.definition.id]: FrostedIconRailModule,
  [KineticPhraseModule.definition.id]: KineticPhraseModule,
  [MediaCutawayModule.definition.id]: MediaCutawayModule,
  [MilestoneStageModule.definition.id]: MilestoneStageModule,
  [ProgressiveChoiceStackModule.definition.id]: ProgressiveChoiceStackModule,
  [StatBurstModule.definition.id]: StatBurstModule,
})
