import { creativeOperationOk, creativeOperationRefusal, type CreativeOperationResultV1 } from '@sanverse/motion-contract'
import { diffStoryboardSequenceV1, createAnimaticV1, applyAnimaticTransactionV1, runAnimaticQaV1, approveAnimaticV1, approveStoryboardSandboxV1, createStoryboardSandboxV1, reviseStoryboardStateGraphV1, reviseStoryboardGraphsV1, applyStoryboardDesignTransactionV1, reopenStoryboardSandboxV1, runStoryboardStructuralQaV1, type AnimaticQaOptionsV1, type AnimaticQaReportV1, type AnimaticTransactionV1, type AnimaticV1, type OwnerApprovalV1, type ReviseStoryboardStateGraphInputV1, type ReviseStoryboardGraphsInputV1, type ApplyStoryboardDesignTransactionInputV1, type StoryboardSandboxV1, type StoryboardStructuralQaContextV1, type StoryboardStructuralQaReportV1, type StoryboardV1 } from '@sanverse/motion-storyboard'
import { planMotionForgeV1, type MotionPlanV1 } from '@sanverse/creative-direction'
import { applyMotionPlanAtomicV15 } from './atomic-motion-plan-v15.ts'
import { applyApprovedMotionDraftV1, applyCreativeMergeInverseV1, applyLocalizedMotionRepairV1, approveMotionDraftV1, createMotionDraftV1, discardMotionDraftV1, runMotionStructuralQaV1, type AcceptedCreativeProjectV1, type AppliedCreativeMergeV1, type AppliedLocalizedRepairV1, type LocalizedRepairProposalV1, type MotionDraftV1, type MotionStructuralQaContextV1, type MotionStructuralQaReportV1, type VisualEvidenceV1, type VisualQaFindingV1 } from './quality-lifecycle.ts'

export type ClosedLoopReviewStageV1='storyboard'|'animatic'|'motion'
export interface ClosedLoopReviewRequestV1 { readonly stage:ClosedLoopReviewStageV1; readonly subjectId:string; readonly subjectRevision:number; readonly startTick:number; readonly endTick:number; readonly criticalTicks:readonly number[] }
export interface ClosedLoopReviewRendererV1 { readonly renderMotionReview:(draft:MotionDraftV1,request:ClosedLoopReviewRequestV1)=>Promise<VisualEvidenceV1>|VisualEvidenceV1 }
export interface OwnerReviewPacketV1 { readonly stage:ClosedLoopReviewStageV1; readonly subjectId:string; readonly subjectRevision:number; readonly qaPassed:boolean; readonly evidence?:VisualEvidenceV1; readonly message:string }
export interface BuildAnimaticInputV1 { readonly id:string; readonly timings:readonly Readonly<{stateId:string;startTick:number;endTick:number}>[]; readonly sourceAudioRef?:Readonly<{sourceId:string;assetRef?:string}> }
export interface BuildMotionDraftInputV1 { readonly id:string }
export interface BuildMotionPlanInputV1 { readonly id:string; readonly styleLockId?:string }
export interface ClosedLoopEngineStateV1 {
  readonly acceptedProject:AcceptedCreativeProjectV1
  readonly storyboardSandbox:StoryboardSandboxV1|null
  readonly storyboardQa:StoryboardStructuralQaReportV1|null
  readonly animatic:AnimaticV1|null
  readonly animaticQa:AnimaticQaReportV1|null
  readonly motionPlan:MotionPlanV1|null
  readonly motionDraft:MotionDraftV1|null
  readonly motionQa:MotionStructuralQaReportV1|null
  readonly visualEvidence:VisualEvidenceV1|null
  readonly visualFindings:readonly VisualQaFindingV1[]
  readonly lastMerge:AppliedCreativeMergeV1|null
}
export interface ClosedLoopEngineV1 {
  readonly getState:()=>ClosedLoopEngineStateV1
  readonly createStoryboardSandbox:(sandboxId:string,storyboard:StoryboardV1)=>CreativeOperationResultV1<StoryboardSandboxV1>
  readonly reviseStoryboard:(input:ReviseStoryboardStateGraphInputV1)=>CreativeOperationResultV1<StoryboardSandboxV1>
  readonly reviseStoryboardGraphs:(input:ReviseStoryboardGraphsInputV1)=>CreativeOperationResultV1<StoryboardSandboxV1>
  readonly applyStoryboardDesign:(input:ApplyStoryboardDesignTransactionInputV1)=>CreativeOperationResultV1<StoryboardSandboxV1>
  readonly reopenStoryboard:(expectedSandboxRevision:number)=>CreativeOperationResultV1<StoryboardSandboxV1>
  readonly validateStoryboard:(context:StoryboardStructuralQaContextV1)=>CreativeOperationResultV1<StoryboardStructuralQaReportV1>
  readonly buildAnimatic:(input:BuildAnimaticInputV1)=>CreativeOperationResultV1<AnimaticV1>
  readonly reviseAnimatic:(transaction:AnimaticTransactionV1)=>CreativeOperationResultV1<AnimaticV1>
  readonly validateAnimatic:(options:AnimaticQaOptionsV1)=>CreativeOperationResultV1<AnimaticQaReportV1>
  readonly buildMotionPlan:(input:BuildMotionPlanInputV1)=>CreativeOperationResultV1<MotionPlanV1>
  readonly buildMotionDraft:(input:BuildMotionDraftInputV1)=>CreativeOperationResultV1<MotionDraftV1>
  readonly repairMotion:(proposal:LocalizedRepairProposalV1)=>CreativeOperationResultV1<AppliedLocalizedRepairV1>
  readonly validateMotion:(context:MotionStructuralQaContextV1)=>CreativeOperationResultV1<MotionStructuralQaReportV1>
  readonly renderReview:(request:ClosedLoopReviewRequestV1)=>Promise<CreativeOperationResultV1<VisualEvidenceV1>>
  readonly setVisualFindings:(findings:readonly VisualQaFindingV1[])=>CreativeOperationResultV1<readonly VisualQaFindingV1[]>
  readonly requestOwnerReview:(stage:ClosedLoopReviewStageV1)=>CreativeOperationResultV1<OwnerReviewPacketV1>
  readonly recordOwnerApproval:(approval:OwnerApprovalV1)=>CreativeOperationResultV1<ClosedLoopEngineStateV1>
  readonly applyApprovedSandbox:()=>CreativeOperationResultV1<AppliedCreativeMergeV1>
  readonly undoLastCreativeMerge:()=>CreativeOperationResultV1<AcceptedCreativeProjectV1>
  readonly discardSandbox:()=>CreativeOperationResultV1<AcceptedCreativeProjectV1>
}

const requireValue=<T>(value:T|null,code:string,message:string):CreativeOperationResultV1<T>=>value===null?creativeOperationRefusal(code,message):creativeOperationOk(value,1)
const snapshot=(acceptedProject:AcceptedCreativeProjectV1,storyboardSandbox:StoryboardSandboxV1|null,storyboardQa:StoryboardStructuralQaReportV1|null,animatic:AnimaticV1|null,animaticQa:AnimaticQaReportV1|null,motionPlan:MotionPlanV1|null,motionDraft:MotionDraftV1|null,motionQa:MotionStructuralQaReportV1|null,visualEvidence:VisualEvidenceV1|null,visualFindings:readonly VisualQaFindingV1[],lastMerge:AppliedCreativeMergeV1|null):ClosedLoopEngineStateV1=>Object.freeze({acceptedProject,storyboardSandbox,storyboardQa,animatic,animaticQa,motionPlan,motionDraft,motionQa,visualEvidence,visualFindings:Object.freeze([...visualFindings]),lastMerge})

export const createClosedLoopEngineV1=(initialProject:AcceptedCreativeProjectV1,renderer?:ClosedLoopReviewRendererV1,restored?:ClosedLoopEngineStateV1):ClosedLoopEngineV1=>{
  if(restored&&(restored.acceptedProject.id!==initialProject.id||restored.acceptedProject.revision!==initialProject.revision))throw new Error('CREATIVE_RUN_REHYDRATION_FAILED: restored Closed-Loop state does not match the candidate project identity/revision.')
  let acceptedProject=restored?.acceptedProject??initialProject
  let storyboardSandbox:StoryboardSandboxV1|null=restored?.storyboardSandbox??null,storyboardQa:StoryboardStructuralQaReportV1|null=restored?.storyboardQa??null
  let animatic:AnimaticV1|null=restored?.animatic??null,animaticQa:AnimaticQaReportV1|null=restored?.animaticQa??null
  let motionPlan:MotionPlanV1|null=restored?.motionPlan??null,motionDraft:MotionDraftV1|null=restored?.motionDraft??null,motionQa:MotionStructuralQaReportV1|null=restored?.motionQa??null
  let visualEvidence:VisualEvidenceV1|null=restored?.visualEvidence??null,visualFindings:readonly VisualQaFindingV1[]=Object.freeze([...(restored?.visualFindings??[])]),lastMerge:AppliedCreativeMergeV1|null=restored?.lastMerge??null
  const state=()=>snapshot(acceptedProject,storyboardSandbox,storyboardQa,animatic,animaticQa,motionPlan,motionDraft,motionQa,visualEvidence,visualFindings,lastMerge)
  const engine:ClosedLoopEngineV1={
    getState:state,
    createStoryboardSandbox:(sandboxId,storyboard)=>{try{storyboardSandbox=createStoryboardSandboxV1(sandboxId,acceptedProject.revision,storyboard);storyboardQa=null;animatic=null;animaticQa=null;motionPlan=null;motionDraft=null;motionQa=null;visualEvidence=null;visualFindings=Object.freeze([]);return creativeOperationOk(storyboardSandbox,storyboardSandbox.sandboxRevision)}catch(error){return creativeOperationRefusal('STORYBOARD_SANDBOX_INVALID',error instanceof Error?error.message:'Storyboard sandbox creation failed.')}},
    reviseStoryboard:(input)=>{const current=requireValue(storyboardSandbox,'STORYBOARD_SANDBOX_REQUIRED','Create a storyboard sandbox before revising it.');if(!current.ok)return current;const result=reviseStoryboardStateGraphV1(current.value,input);if(!result.ok)return result as CreativeOperationResultV1<StoryboardSandboxV1>;storyboardSandbox=result.value.sandbox;storyboardQa=null;animatic=null;animaticQa=null;motionPlan=null;motionDraft=null;motionQa=null;visualEvidence=null;visualFindings=Object.freeze([]);return creativeOperationOk(storyboardSandbox,storyboardSandbox.sandboxRevision)},
    reviseStoryboardGraphs:(input)=>{const current=requireValue(storyboardSandbox,'STORYBOARD_SANDBOX_REQUIRED','Create a storyboard sandbox before revising it.');if(!current.ok)return current;const result=reviseStoryboardGraphsV1(current.value,input);if(!result.ok)return result as CreativeOperationResultV1<StoryboardSandboxV1>;storyboardSandbox=result.value.sandbox;storyboardQa=null;animatic=null;animaticQa=null;motionPlan=null;motionDraft=null;motionQa=null;visualEvidence=null;visualFindings=Object.freeze([]);return creativeOperationOk(storyboardSandbox,storyboardSandbox.sandboxRevision)},
    applyStoryboardDesign:(input)=>{const current=requireValue(storyboardSandbox,'STORYBOARD_SANDBOX_REQUIRED','Create a storyboard sandbox before revising it.');if(!current.ok)return current;const result=applyStoryboardDesignTransactionV1(current.value,input);if(!result.ok)return result as CreativeOperationResultV1<StoryboardSandboxV1>;storyboardSandbox=result.value.sandbox;storyboardQa=null;animatic=null;animaticQa=null;motionPlan=null;motionDraft=null;motionQa=null;visualEvidence=null;visualFindings=Object.freeze([]);return creativeOperationOk(storyboardSandbox,storyboardSandbox.sandboxRevision)},
    reopenStoryboard:(expectedSandboxRevision)=>{const current=requireValue(storyboardSandbox,'STORYBOARD_SANDBOX_REQUIRED','Storyboard sandbox is missing.');if(!current.ok)return current;const reopened=reopenStoryboardSandboxV1(current.value,expectedSandboxRevision);if(!reopened.ok)return reopened;storyboardSandbox=reopened.value;storyboardQa=null;animatic=null;animaticQa=null;motionPlan=null;motionDraft=null;motionQa=null;visualEvidence=null;visualFindings=Object.freeze([]);return creativeOperationOk(storyboardSandbox,storyboardSandbox.sandboxRevision)},
    validateStoryboard:(context)=>{const current=requireValue(storyboardSandbox,'STORYBOARD_SANDBOX_REQUIRED','Create a storyboard sandbox before validation.');if(!current.ok)return current as CreativeOperationResultV1<StoryboardStructuralQaReportV1>;storyboardQa=runStoryboardStructuralQaV1(current.value.storyboard,context);return creativeOperationOk(storyboardQa,current.value.storyboard.revision)},
    buildAnimatic:(input)=>{const current=requireValue(storyboardSandbox,'STORYBOARD_SANDBOX_REQUIRED','Storyboard approval is required before animatic creation.');if(!current.ok)return current as CreativeOperationResultV1<AnimaticV1>;if(current.value.storyboard.status!=='owner-approved')return creativeOperationRefusal('STORYBOARD_APPROVAL_REQUIRED','Animatic requires the exact owner-approved storyboard revision.');try{animatic=createAnimaticV1({id:input.id,storyboardId:current.value.storyboard.id,storyboardApprovedRevision:current.value.storyboard.revision,timings:Object.freeze(input.timings.map(item=>Object.freeze({...item}))),...(input.sourceAudioRef?{sourceAudioRef:Object.freeze({...input.sourceAudioRef})}:{})},current.value.storyboard);animaticQa=null;return creativeOperationOk(animatic,animatic.revision)}catch(error){return creativeOperationRefusal('ANIMATIC_INVALID',error instanceof Error?error.message:'Animatic creation failed.')}},
    reviseAnimatic:(transaction)=>{const current=requireValue(animatic,'ANIMATIC_REQUIRED','Build an animatic before revising timing.');if(!current.ok)return current;const result=applyAnimaticTransactionV1(current.value,transaction);if(!result.ok)return result as CreativeOperationResultV1<AnimaticV1>;animatic=result.value.animatic;animaticQa=null;motionPlan=null;motionDraft=null;motionQa=null;visualEvidence=null;visualFindings=Object.freeze([]);return creativeOperationOk(animatic,animatic.revision)},
    validateAnimatic:(options)=>{const current=requireValue(animatic,'ANIMATIC_REQUIRED','Build an animatic before validation.');const board=requireValue(storyboardSandbox,'STORYBOARD_SANDBOX_REQUIRED','Storyboard sandbox is missing.');if(!current.ok)return current as CreativeOperationResultV1<AnimaticQaReportV1>;if(!board.ok)return board as CreativeOperationResultV1<AnimaticQaReportV1>;animaticQa=runAnimaticQaV1(current.value,board.value.storyboard,options);return creativeOperationOk(animaticQa,current.value.revision)},
    buildMotionPlan:(input)=>{const board=requireValue(storyboardSandbox,'STORYBOARD_SANDBOX_REQUIRED','Storyboard sandbox is missing.');const timing=requireValue(animatic,'ANIMATIC_REQUIRED','Approved animatic is required before Motion Forge.');if(!board.ok)return board as CreativeOperationResultV1<MotionPlanV1>;if(!timing.ok)return timing as CreativeOperationResultV1<MotionPlanV1>;if(board.value.storyboard.status!=='owner-approved'||timing.value.status!=='owner-approved')return creativeOperationRefusal('MOTION_FORGE_REQUIRES_APPROVAL','Motion Forge requires owner-approved Storyboard and Animatic revisions.');const stateById=new Map(board.value.storyboard.states.map(item=>[item.id,item]));const planned=planMotionForgeV1({motionPlanId:input.id,storyboardId:board.value.storyboard.id,storyboardApprovedRevision:board.value.storyboard.revision,storyboardStatus:'owner-approved',animaticId:timing.value.id,animaticApprovedRevision:timing.value.revision,animaticStatus:'owner-approved',stateTimings:Object.freeze(timing.value.timings.map(item=>Object.freeze({...item,nodeIds:Object.freeze([...(stateById.get(item.stateId)?.focusNodeIds??[])])}))),storyboardDiffs:diffStoryboardSequenceV1(board.value.storyboard.states),...(input.styleLockId?{styleLockId:input.styleLockId}:{})});if(!planned.ok)return creativeOperationRefusal(planned.refusal.code,planned.refusal.message,planned.refusal.details);motionPlan=planned.value;motionDraft=null;motionQa=null;visualEvidence=null;visualFindings=Object.freeze([]);return creativeOperationOk(motionPlan,motionPlan.revision)},
    buildMotionDraft:(input)=>{const plan=requireValue(motionPlan,'MOTION_PLAN_REQUIRED','Build MotionPlanV1 before compiling motion.'),board=requireValue(storyboardSandbox,'STORYBOARD_SANDBOX_REQUIRED','Approved Storyboard is required before compiling motion.');if(!plan.ok)return plan as CreativeOperationResultV1<MotionDraftV1>;if(!board.ok)return board as CreativeOperationResultV1<MotionDraftV1>;if(board.value.storyboard.status!=='owner-approved'||board.value.storyboard.revision!==plan.value.storyboardApprovedRevision)return creativeOperationRefusal('STORYBOARD_BASELINE_MISMATCH','Motion Forge must compile from the exact approved Storyboard revision recorded by the MotionPlan.');const structuralBase=board.value.storyboard.states[0]?.graphState;if(!structuralBase)return creativeOperationRefusal('STORYBOARD_BASELINE_MISSING','Approved Storyboard has no structural graph state to animate.');const compiled=applyMotionPlanAtomicV15(structuralBase,plan.value);if(!compiled.ok)return creativeOperationRefusal(compiled.refusal.code,compiled.refusal.message,compiled.refusal.details);try{motionDraft=createMotionDraftV1(input.id,acceptedProject.revision,plan.value.id,compiled.value.scene);motionQa=null;visualEvidence=null;visualFindings=Object.freeze([]);return creativeOperationOk(motionDraft,motionDraft.revision)}catch(error){return creativeOperationRefusal('MOTION_DRAFT_INVALID',error instanceof Error?error.message:'Motion draft creation failed.')}},
    repairMotion:(proposal)=>{const current=requireValue(motionDraft,'MOTION_DRAFT_REQUIRED','Build a motion draft before repair.');if(!current.ok)return current as CreativeOperationResultV1<AppliedLocalizedRepairV1>;const result=applyLocalizedMotionRepairV1(current.value,proposal);if(!result.ok)return result;motionDraft=result.value.draft;motionQa=null;visualEvidence=null;return result},
    validateMotion:(context)=>{const current=requireValue(motionDraft,'MOTION_DRAFT_REQUIRED','Build a motion draft before validation.');if(!current.ok)return current as CreativeOperationResultV1<MotionStructuralQaReportV1>;motionQa=runMotionStructuralQaV1(current.value.scene,context);return creativeOperationOk(motionQa,current.value.revision)},
    renderReview:async(request)=>{const current=requireValue(motionDraft,'MOTION_DRAFT_REQUIRED','Build a motion draft before review rendering.');if(!current.ok)return current as CreativeOperationResultV1<VisualEvidenceV1>;if(!renderer)return creativeOperationRefusal('REVIEW_RENDERER_UNAVAILABLE','No Closed-Loop review renderer is configured.');if(request.stage!=='motion'||request.subjectId!==current.value.id||request.subjectRevision!==current.value.revision)return creativeOperationRefusal('REVIEW_REVISION_MISMATCH','Motion review request must target the exact current motion draft revision.');visualEvidence=await renderer.renderMotionReview(current.value,request);return creativeOperationOk(visualEvidence,current.value.revision)},
    setVisualFindings:(findings)=>{visualFindings=Object.freeze([...findings]);return creativeOperationOk(visualFindings,motionDraft?.revision??acceptedProject.revision)},
    requestOwnerReview:(stage)=>{if(stage==='storyboard'){const current=requireValue(storyboardSandbox,'STORYBOARD_SANDBOX_REQUIRED','Storyboard sandbox is missing.');if(!current.ok)return current as CreativeOperationResultV1<OwnerReviewPacketV1>;return creativeOperationOk(Object.freeze({stage,subjectId:current.value.storyboard.id,subjectRevision:current.value.storyboard.revision,qaPassed:storyboardQa?.ok===true,message:'Owner approval is requested for this exact Storyboard revision. No approval is implied.'}),current.value.storyboard.revision)}if(stage==='animatic'){const current=requireValue(animatic,'ANIMATIC_REQUIRED','Animatic is missing.');if(!current.ok)return current as CreativeOperationResultV1<OwnerReviewPacketV1>;return creativeOperationOk(Object.freeze({stage,subjectId:current.value.id,subjectRevision:current.value.revision,qaPassed:animaticQa?.ok===true,message:'Owner approval is requested for this exact Animatic revision. No approval is implied.'}),current.value.revision)}const current=requireValue(motionDraft,'MOTION_DRAFT_REQUIRED','Motion draft is missing.');if(!current.ok)return current as CreativeOperationResultV1<OwnerReviewPacketV1>;return creativeOperationOk(Object.freeze({stage,subjectId:current.value.id,subjectRevision:current.value.revision,qaPassed:motionQa?.ok===true,...(visualEvidence?{evidence:visualEvidence}:{}),message:'Owner approval is requested for this exact Motion revision. No approval is implied.'}),current.value.revision)},
    recordOwnerApproval:(approval)=>{if(approval.scope==='storyboard'){const current=requireValue(storyboardSandbox,'STORYBOARD_SANDBOX_REQUIRED','Storyboard sandbox is missing.');if(!current.ok)return current as CreativeOperationResultV1<ClosedLoopEngineStateV1>;if(!storyboardQa)return creativeOperationRefusal('STORYBOARD_QA_REQUIRED','Run Storyboard QA before owner approval.');const approved=approveStoryboardSandboxV1(current.value,approval,storyboardQa);if(!approved.ok)return approved as CreativeOperationResultV1<ClosedLoopEngineStateV1>;storyboardSandbox=approved.value;return creativeOperationOk(state(),storyboardSandbox.sandboxRevision)}if(approval.scope==='animatic'){const current=requireValue(animatic,'ANIMATIC_REQUIRED','Animatic is missing.');if(!current.ok)return current as CreativeOperationResultV1<ClosedLoopEngineStateV1>;if(!animaticQa)return creativeOperationRefusal('ANIMATIC_QA_REQUIRED','Run Animatic QA before owner approval.');const approved=approveAnimaticV1(current.value,approval,animaticQa);if(!approved.ok)return approved as CreativeOperationResultV1<ClosedLoopEngineStateV1>;animatic=approved.value.animatic;return creativeOperationOk(state(),animatic.revision)}const current=requireValue(motionDraft,'MOTION_DRAFT_REQUIRED','Motion draft is missing.');if(!current.ok)return current as CreativeOperationResultV1<ClosedLoopEngineStateV1>;if(!motionQa)return creativeOperationRefusal('MOTION_QA_REQUIRED','Run Motion QA before owner approval.');if(!visualEvidence)return creativeOperationRefusal('VISUAL_EVIDENCE_REQUIRED','Render canonical review evidence before owner approval.');const approved=approveMotionDraftV1(current.value,approval,motionQa,visualFindings,visualEvidence);if(!approved.ok)return approved as CreativeOperationResultV1<ClosedLoopEngineStateV1>;motionDraft=approved.value;return creativeOperationOk(state(),motionDraft.revision)},
    applyApprovedSandbox:()=>{const current=requireValue(motionDraft,'MOTION_DRAFT_REQUIRED','Motion draft is missing.');if(!current.ok)return current as CreativeOperationResultV1<AppliedCreativeMergeV1>;const merged=applyApprovedMotionDraftV1(acceptedProject,current.value);if(!merged.ok)return merged;acceptedProject=merged.value.project;lastMerge=merged.value;return merged},
    undoLastCreativeMerge:()=>{if(!lastMerge)return creativeOperationRefusal('CREATIVE_MERGE_HISTORY_REQUIRED','No Creative Engine merge is available to undo.');const undone=applyCreativeMergeInverseV1(acceptedProject,lastMerge.historyEntry);if(!undone.ok)return undone;acceptedProject=undone.value;lastMerge=null;return undone},
    discardSandbox:()=>{acceptedProject=motionDraft?discardMotionDraftV1(acceptedProject,motionDraft):acceptedProject;storyboardSandbox=null;storyboardQa=null;animatic=null;animaticQa=null;motionPlan=null;motionDraft=null;motionQa=null;visualEvidence=null;visualFindings=Object.freeze([]);return creativeOperationOk(acceptedProject,acceptedProject.revision)},
  }
  return Object.freeze(engine)
}
