import { creativeOperationOk,creativeOperationRefusal,type CreativeOperationResultV1 } from '@sanverse/motion-contract'
import { rankCapabilitiesV1,type CapabilityRetrievalQueryV1,type RankedCapabilityV1 } from '@sanverse/creative-direction'
import { promotedCapabilityToCapabilityCatalogItemV1,applyPromotionTransactionV1,applyStyleLockV1,applyTemplateParameterV1,bindMotionRecipeV1,classifyPromotionCandidateV1,createPromotionCandidateV1,createPromotionRegistryV1,createPromotionWorkspaceV1,extractMotionRecipeV1,instantiateReusableMotionTemplateV1,productizePromotionCandidateV1,proposeParameterizationPlanV1,registerPromotedCapabilityV1,reviewParameterCandidateV1,runPromotionQaV1,type ParameterReviewEditV1,type ParameterizationPlanV1,type ProductizedPromotedCapabilityV1,type PromotedMotionRecipeV1,type PromotionCandidateV1,type PromotionClassificationV1,type PromotionQaReportV1,type PromotionRegistrationConfirmationV1,type PromotionRegistryV1,type PromotionReviewArtifactsV1,type PromotionSourceV1,type PromotionTargetKindV1,type PromotionWorkspaceV1,type RegisteredPromotedCapabilityV1,type StyleLockV1 } from '@sanverse/motion-promotion'
import type { OwnerApprovalV1 } from '@sanverse/motion-storyboard'
import { applyMotionPlanV1 } from './semantic-motion.ts'
import { applyApprovedMotionDraftV1,applyCreativeMergeInverseV1,approveMotionDraftV1,createMotionDraftV1,runMotionStructuralQaV1,type AcceptedCreativeProjectV1,type AppliedCreativeMergeV1,type MotionDraftV1,type MotionStructuralQaContextV1,type MotionStructuralQaReportV1,type VisualEvidenceV1 } from './quality-lifecycle.ts'

export interface PromotionReuseReviewRendererV1 { readonly renderReuseReview:(draft:MotionDraftV1,capability:RegisteredPromotedCapabilityV1)=>Promise<VisualEvidenceV1>|VisualEvidenceV1 }
export interface CapabilityReuseSandboxV1 {
  readonly id:string
  readonly capabilityId:string
  readonly capabilityVersion:number
  readonly baseProjectRevision:number
  readonly revision:number
  readonly motionDraft:MotionDraftV1
  readonly qa:MotionStructuralQaReportV1|null
  readonly evidence:VisualEvidenceV1|null
  readonly recipePlanId?:string
}
export interface PromotionReuseEngineStateV1 {
  readonly source:PromotionSourceV1
  readonly candidate:PromotionCandidateV1|null
  readonly workspace:PromotionWorkspaceV1|null
  readonly parameterization:ParameterizationPlanV1|null
  readonly classification:PromotionClassificationV1|null
  readonly productized:ProductizedPromotedCapabilityV1|null
  readonly recipe:PromotedMotionRecipeV1|null
  readonly promotionQa:PromotionQaReportV1|null
  readonly registry:PromotionRegistryV1
  readonly acceptedProject:AcceptedCreativeProjectV1
  readonly reuseSandbox:CapabilityReuseSandboxV1|null
  readonly lastReuseMerge:AppliedCreativeMergeV1|null
}
export interface PromotionReuseEngineV1 {
  readonly getState:()=>PromotionReuseEngineStateV1
  readonly createCandidate:(input:Readonly<{candidateId:string;workspaceId:string;targetKinds:readonly PromotionTargetKindV1[]}>)=>CreativeOperationResultV1<PromotionCandidateV1>
  readonly inspectCandidate:()=>CreativeOperationResultV1<PromotionReuseEngineStateV1>
  readonly proposeParameters:(planId:string)=>CreativeOperationResultV1<ParameterizationPlanV1>
  readonly reviewParameter:(parameterId:string,edit:ParameterReviewEditV1)=>CreativeOperationResultV1<ParameterizationPlanV1>
  readonly setTargetKind:(kind:PromotionTargetKindV1,idempotencyKey:string)=>CreativeOperationResultV1<PromotionWorkspaceV1>
  readonly productize:(input:Readonly<{id:string;title:string;description:string;registrationVersion:number}>)=>CreativeOperationResultV1<ProductizedPromotedCapabilityV1>
  readonly validatePromotion:(input:Readonly<{replacementValues:Readonly<Record<string,unknown>>;durationTicks:number;ticksPerSecond:number;composition:Readonly<{width:number;height:number;fpsNumerator:number;fpsDenominator:number}>;sampleTicks:readonly number[]}>)=>CreativeOperationResultV1<PromotionQaReportV1>
  readonly registerPromotion:(confirmation:PromotionRegistrationConfirmationV1,artifacts:PromotionReviewArtifactsV1)=>CreativeOperationResultV1<RegisteredPromotedCapabilityV1>
  readonly retrievePromoted:(query:CapabilityRetrievalQueryV1)=>CreativeOperationResultV1<readonly RankedCapabilityV1[]>
  readonly instantiateCapability:(input:Readonly<{capabilityId:string;sandboxId:string;instanceId:string;values?:Readonly<Record<string,unknown>>}>)=>CreativeOperationResultV1<CapabilityReuseSandboxV1>
  readonly setCapabilityParameter:(publicPath:string,value:unknown,expectedSandboxRevision:number)=>CreativeOperationResultV1<CapabilityReuseSandboxV1>
  readonly applyCapabilityStyleLock:(lock:StyleLockV1,expectedSandboxRevision:number)=>CreativeOperationResultV1<CapabilityReuseSandboxV1>
  readonly applyRecipe:(input:Readonly<{recipeApplicationId:string;storyboardId:string;storyboardApprovedRevision:number;animaticId:string;animaticApprovedRevision:number;roleBindings:Readonly<Record<string,readonly string[]>>;expectedSandboxRevision:number}>)=>CreativeOperationResultV1<CapabilityReuseSandboxV1>
  readonly validateReuse:(context:MotionStructuralQaContextV1)=>CreativeOperationResultV1<MotionStructuralQaReportV1>
  readonly renderReuseReview:()=>Promise<CreativeOperationResultV1<VisualEvidenceV1>>
  readonly recordReuseApproval:(approval:OwnerApprovalV1)=>CreativeOperationResultV1<CapabilityReuseSandboxV1>
  readonly applyReuse:()=>CreativeOperationResultV1<AppliedCreativeMergeV1>
  readonly undoReuse:()=>CreativeOperationResultV1<AcceptedCreativeProjectV1>
  readonly discardReuse:()=>CreativeOperationResultV1<AcceptedCreativeProjectV1>
}

const requireValue=<T>(value:T|null,code:string,message:string):CreativeOperationResultV1<T>=>value===null?creativeOperationRefusal(code,message):creativeOperationOk(value,1)
const replaceDraftScene=(draft:MotionDraftV1,scene:MotionDraftV1['scene']):MotionDraftV1=>Object.freeze({...draft,scene,revision:draft.revision+1,status:'draft' as const,ownerApprovalId:undefined})
const snapshot=(source:PromotionSourceV1,candidate:PromotionCandidateV1|null,workspace:PromotionWorkspaceV1|null,parameterization:ParameterizationPlanV1|null,classification:PromotionClassificationV1|null,productized:ProductizedPromotedCapabilityV1|null,recipe:PromotedMotionRecipeV1|null,promotionQa:PromotionQaReportV1|null,registry:PromotionRegistryV1,acceptedProject:AcceptedCreativeProjectV1,reuseSandbox:CapabilityReuseSandboxV1|null,lastReuseMerge:AppliedCreativeMergeV1|null):PromotionReuseEngineStateV1=>Object.freeze({source,candidate,workspace,parameterization,classification,productized,recipe,promotionQa,registry,acceptedProject,reuseSandbox,lastReuseMerge})

export const createPromotionReuseEngineV1=(source:PromotionSourceV1,initialProjectB:AcceptedCreativeProjectV1,renderer?:PromotionReuseReviewRendererV1):PromotionReuseEngineV1=>{
  let candidate:PromotionCandidateV1|null=null,workspace:PromotionWorkspaceV1|null=null,parameterization:ParameterizationPlanV1|null=null,classification:PromotionClassificationV1|null=null
  let productized:ProductizedPromotedCapabilityV1|null=null,recipe:PromotedMotionRecipeV1|null=null,promotionQa:PromotionQaReportV1|null=null,registry:PromotionRegistryV1=createPromotionRegistryV1()
  let acceptedProject=initialProjectB,reuseSandbox:CapabilityReuseSandboxV1|null=null,lastReuseMerge:AppliedCreativeMergeV1|null=null
  const state=()=>snapshot(source,candidate,workspace,parameterization,classification,productized,recipe,promotionQa,registry,acceptedProject,reuseSandbox,lastReuseMerge)
  const engine:PromotionReuseEngineV1={
    getState:state,
    createCandidate:(input)=>{const created=createPromotionCandidateV1(source,input.targetKinds,input.candidateId);if(!created.ok)return created;candidate=created.value;try{workspace=createPromotionWorkspaceV1(input.workspaceId,candidate)}catch(error){candidate=null;return creativeOperationRefusal('PROMOTION_WORKSPACE_INVALID',error instanceof Error?error.message:'Promotion workspace creation failed.')}classification=classifyPromotionCandidateV1(candidate,source.scene,source.motionPlan);parameterization=null;productized=null;recipe=null;promotionQa=null;return created},
    inspectCandidate:()=>candidate?creativeOperationOk(state(),candidate.revision):creativeOperationRefusal('PROMOTION_CANDIDATE_REQUIRED','Create a promotion candidate first.'),
    proposeParameters:(planId)=>{const current=requireValue(candidate,'PROMOTION_CANDIDATE_REQUIRED','Create a promotion candidate before parameterization.');if(!current.ok)return current as CreativeOperationResultV1<ParameterizationPlanV1>;const proposed=proposeParameterizationPlanV1(current.value,source.scene,planId);if(!proposed.ok)return proposed;parameterization=proposed.value;if(workspace){const tx=applyPromotionTransactionV1(workspace,{schemaVersion:'sanverse.promotion-transaction/v1',id:`tx:${planId}`,idempotencyKey:`plan:${planId}`,baseRevision:workspace.revision,operations:Object.freeze([{type:'promotion.set-parameterization-plan',parameterizationPlanId:planId}])});if(!tx.ok)return tx as CreativeOperationResultV1<ParameterizationPlanV1>;workspace=tx.value.workspace}return proposed},
    reviewParameter:(parameterId,edit)=>{const plan=requireValue(parameterization,'PROMOTION_PARAMETERIZATION_REQUIRED','Propose parameters before reviewing them.');if(!plan.ok)return plan;const reviewed=reviewParameterCandidateV1(plan.value,parameterId,edit);if(!reviewed.ok)return reviewed;parameterization=reviewed.value;productized=null;promotionQa=null;return reviewed},
    setTargetKind:(kind,idempotencyKey)=>{const current=requireValue(workspace,'PROMOTION_WORKSPACE_REQUIRED','Create a promotion workspace first.');if(!current.ok)return current;const result=applyPromotionTransactionV1(current.value,{schemaVersion:'sanverse.promotion-transaction/v1',id:`tx:target:${kind}`,idempotencyKey,baseRevision:current.value.revision,operations:Object.freeze([{type:'promotion.set-target-kind',targetKind:kind}])});if(!result.ok)return result as CreativeOperationResultV1<PromotionWorkspaceV1>;workspace=result.value.workspace;productized=null;promotionQa=null;return creativeOperationOk(workspace,workspace.revision)},
    productize:(input)=>{const c=requireValue(candidate,'PROMOTION_CANDIDATE_REQUIRED','Create a promotion candidate first.'),p=requireValue(parameterization,'PROMOTION_PARAMETERIZATION_REQUIRED','Parameterization plan is required.'),w=requireValue(workspace,'PROMOTION_WORKSPACE_REQUIRED','Promotion workspace is required.');if(!c.ok)return c as CreativeOperationResultV1<ProductizedPromotedCapabilityV1>;if(!p.ok)return p as CreativeOperationResultV1<ProductizedPromotedCapabilityV1>;if(!w.ok)return w as CreativeOperationResultV1<ProductizedPromotedCapabilityV1>;classification=classification??classifyPromotionCandidateV1(c.value,source.scene,source.motionPlan);const target=w.value.targetKind??classification.recommendedKind;const result=productizePromotionCandidateV1({...input,candidate:c.value,source,parameterization:p.value,classification,targetKind:target});if(!result.ok)return result;productized=result.value;promotionQa=null;if(source.motionPlan){const extracted=extractMotionRecipeV1({id:`${input.id}:recipe`,title:`${input.title} motion recipe`,motionPlan:source.motionPlan,scene:source.scene,communicationGoals:result.value.communicationGoals,supportedPresentationModes:result.value.supportedPresentationModes});if(extracted.ok)recipe=extracted.value}return result},
    validatePromotion:(input)=>{const current=requireValue(productized,'PROMOTION_PRODUCTIZED_REQUIRED','Productize the promotion candidate before QA.');if(!current.ok)return current as CreativeOperationResultV1<PromotionQaReportV1>;const defaultInstance=instantiateReusableMotionTemplateV1(current.value.template,current.value.canonicalFixture.values,{instanceId:'promotion-qa:default'});if(!defaultInstance.ok)return defaultInstance as CreativeOperationResultV1<PromotionQaReportV1>;const replacementInstance=instantiateReusableMotionTemplateV1(current.value.template,input.replacementValues,{instanceId:'promotion-qa:replacement'});if(!replacementInstance.ok)return replacementInstance as CreativeOperationResultV1<PromotionQaReportV1>;promotionQa=runPromotionQaV1({source,capability:current.value,defaultInstance:defaultInstance.value.scene,replacementInstance:replacementInstance.value.scene,durationTicks:input.durationTicks,ticksPerSecond:input.ticksPerSecond,composition:input.composition,sampleTicks:input.sampleTicks});return creativeOperationOk(promotionQa,current.value.version)},
    registerPromotion:(confirmation,artifacts)=>{const current=requireValue(productized,'PROMOTION_PRODUCTIZED_REQUIRED','Productized capability is required before registration.'),qa=requireValue(promotionQa,'PROMOTION_QA_REQUIRED','Promotion QA is required before registration.');if(!current.ok)return current as CreativeOperationResultV1<RegisteredPromotedCapabilityV1>;if(!qa.ok)return qa as CreativeOperationResultV1<RegisteredPromotedCapabilityV1>;const registered=registerPromotedCapabilityV1(registry,current.value,qa.value,confirmation,artifacts);if(!registered.ok)return registered as CreativeOperationResultV1<RegisteredPromotedCapabilityV1>;registry=registered.value.registry;return creativeOperationOk(registered.value.entry,registry.revision)},
    retrievePromoted:(query)=>{const ranked=rankCapabilitiesV1(registry.entries.map(promotedCapabilityToCapabilityCatalogItemV1),query);return creativeOperationOk(ranked,registry.revision)},
    instantiateCapability:(input)=>{const capability=registry.entries.find(item=>item.id===input.capabilityId);if(!capability)return creativeOperationRefusal('PROMOTED_CAPABILITY_NOT_FOUND',`Registered promoted capability ${input.capabilityId} was not found.`);const instantiated=instantiateReusableMotionTemplateV1(capability.template,input.values??Object.freeze({}),{instanceId:input.instanceId});if(!instantiated.ok)return instantiated as CreativeOperationResultV1<CapabilityReuseSandboxV1>;let draft:MotionDraftV1;try{draft=createMotionDraftV1(input.sandboxId,acceptedProject.revision,`promotion-reuse:${capability.id}:v${capability.version}`,instantiated.value.scene)}catch(error){return creativeOperationRefusal('CAPABILITY_REUSE_SANDBOX_INVALID',error instanceof Error?error.message:'Cannot create capability reuse sandbox.')}reuseSandbox=Object.freeze({id:input.sandboxId,capabilityId:capability.id,capabilityVersion:capability.version,baseProjectRevision:acceptedProject.revision,revision:1,motionDraft:draft,qa:null,evidence:null});lastReuseMerge=null;return creativeOperationOk(reuseSandbox,1)},
    setCapabilityParameter:(publicPath,value,expectedSandboxRevision)=>{const sandbox=requireValue(reuseSandbox,'CAPABILITY_REUSE_SANDBOX_REQUIRED','Instantiate a promoted capability before adapting it.');if(!sandbox.ok)return sandbox;if(expectedSandboxRevision!==sandbox.value.revision)return creativeOperationRefusal('STALE_CAPABILITY_REUSE_REVISION',`Expected reuse sandbox revision ${expectedSandboxRevision}; current revision is ${sandbox.value.revision}.`);const capability=registry.entries.find(item=>item.id===sandbox.value.capabilityId&&item.version===sandbox.value.capabilityVersion);if(!capability)return creativeOperationRefusal('PROMOTED_CAPABILITY_NOT_FOUND','Registered promoted capability is unavailable.');const applied=applyTemplateParameterV1(capability.template,sandbox.value.motionDraft.scene,publicPath,value);if(!applied.ok)return applied as CreativeOperationResultV1<CapabilityReuseSandboxV1>;const revision=sandbox.value.revision+1;reuseSandbox=Object.freeze({...sandbox.value,revision,motionDraft:replaceDraftScene(sandbox.value.motionDraft,applied.value),qa:null,evidence:null});return creativeOperationOk(reuseSandbox,revision)},
    applyCapabilityStyleLock:(lock,expectedSandboxRevision)=>{const sandbox=requireValue(reuseSandbox,'CAPABILITY_REUSE_SANDBOX_REQUIRED','Instantiate a promoted capability before style adaptation.');if(!sandbox.ok)return sandbox;if(expectedSandboxRevision!==sandbox.value.revision)return creativeOperationRefusal('STALE_CAPABILITY_REUSE_REVISION',`Expected reuse sandbox revision ${expectedSandboxRevision}; current revision is ${sandbox.value.revision}.`);const capability=registry.entries.find(item=>item.id===sandbox.value.capabilityId&&item.version===sandbox.value.capabilityVersion);if(!capability)return creativeOperationRefusal('PROMOTED_CAPABILITY_NOT_FOUND','Registered promoted capability is unavailable.');const applied=applyStyleLockV1(capability.template,sandbox.value.motionDraft.scene,lock);if(!applied.ok)return applied as CreativeOperationResultV1<CapabilityReuseSandboxV1>;const revision=sandbox.value.revision+1;reuseSandbox=Object.freeze({...sandbox.value,revision,motionDraft:replaceDraftScene(sandbox.value.motionDraft,applied.value.scene),qa:null,evidence:null});return creativeOperationOk(reuseSandbox,revision)},
    applyRecipe:(input)=>{const sandbox=requireValue(reuseSandbox,'CAPABILITY_REUSE_SANDBOX_REQUIRED','Instantiate a promoted capability before applying a recipe.'),currentRecipe=requireValue(recipe,'PROMOTED_MOTION_RECIPE_REQUIRED','No promoted Motion Recipe is available.');if(!sandbox.ok)return sandbox;if(!currentRecipe.ok)return currentRecipe as CreativeOperationResultV1<CapabilityReuseSandboxV1>;if(input.expectedSandboxRevision!==sandbox.value.revision)return creativeOperationRefusal('STALE_CAPABILITY_REUSE_REVISION',`Expected reuse sandbox revision ${input.expectedSandboxRevision}; current revision is ${sandbox.value.revision}.`);const bound=bindMotionRecipeV1(currentRecipe.value,{recipeApplicationId:input.recipeApplicationId,storyboardId:input.storyboardId,storyboardApprovedRevision:input.storyboardApprovedRevision,animaticId:input.animaticId,animaticApprovedRevision:input.animaticApprovedRevision,roleBindings:input.roleBindings});if(!bound.ok)return bound as CreativeOperationResultV1<CapabilityReuseSandboxV1>;const compiled=applyMotionPlanV1(sandbox.value.motionDraft.scene,bound.value);if(!compiled.ok)return creativeOperationRefusal(compiled.refusal.code,compiled.refusal.message,compiled.refusal.details);const revision=sandbox.value.revision+1;reuseSandbox=Object.freeze({...sandbox.value,revision,motionDraft:replaceDraftScene(sandbox.value.motionDraft,compiled.value.scene),qa:null,evidence:null,recipePlanId:bound.value.id});return creativeOperationOk(reuseSandbox,revision)},
    validateReuse:(context)=>{const sandbox=requireValue(reuseSandbox,'CAPABILITY_REUSE_SANDBOX_REQUIRED','Instantiate a promoted capability before reuse QA.');if(!sandbox.ok)return sandbox as CreativeOperationResultV1<MotionStructuralQaReportV1>;const qa=runMotionStructuralQaV1(sandbox.value.motionDraft.scene,context);reuseSandbox=Object.freeze({...sandbox.value,qa});return creativeOperationOk(qa,sandbox.value.revision)},
    renderReuseReview:async()=>{const sandbox=requireValue(reuseSandbox,'CAPABILITY_REUSE_SANDBOX_REQUIRED','Instantiate a promoted capability before review.');if(!sandbox.ok)return sandbox as CreativeOperationResultV1<VisualEvidenceV1>;if(!renderer)return creativeOperationRefusal('REVIEW_RENDERER_UNAVAILABLE','No promotion reuse review renderer is configured.');const capability=registry.entries.find(item=>item.id===sandbox.value.capabilityId&&item.version===sandbox.value.capabilityVersion);if(!capability)return creativeOperationRefusal('PROMOTED_CAPABILITY_NOT_FOUND','Registered promoted capability is unavailable.');const evidence=await renderer.renderReuseReview(sandbox.value.motionDraft,capability);reuseSandbox=Object.freeze({...sandbox.value,evidence});return creativeOperationOk(evidence,sandbox.value.revision)},
    recordReuseApproval:(approval)=>{const sandbox=requireValue(reuseSandbox,'CAPABILITY_REUSE_SANDBOX_REQUIRED','Instantiate a promoted capability before approval.');if(!sandbox.ok)return sandbox;if(!sandbox.value.qa)return creativeOperationRefusal('MOTION_QA_REQUIRED','Run reuse Motion QA before approval.');if(!sandbox.value.evidence)return creativeOperationRefusal('VISUAL_EVIDENCE_REQUIRED','Render reuse review evidence before approval.');const approved=approveMotionDraftV1(sandbox.value.motionDraft,approval,sandbox.value.qa,Object.freeze([]),sandbox.value.evidence);if(!approved.ok)return approved as CreativeOperationResultV1<CapabilityReuseSandboxV1>;reuseSandbox=Object.freeze({...sandbox.value,motionDraft:approved.value});return creativeOperationOk(reuseSandbox,reuseSandbox.revision)},
    applyReuse:()=>{const sandbox=requireValue(reuseSandbox,'CAPABILITY_REUSE_SANDBOX_REQUIRED','Instantiate a promoted capability before apply.');if(!sandbox.ok)return sandbox as CreativeOperationResultV1<AppliedCreativeMergeV1>;const merged=applyApprovedMotionDraftV1(acceptedProject,sandbox.value.motionDraft);if(!merged.ok)return merged;acceptedProject=merged.value.project;lastReuseMerge=merged.value;return merged},
    undoReuse:()=>{if(!lastReuseMerge)return creativeOperationRefusal('CREATIVE_MERGE_HISTORY_REQUIRED','No promoted-capability reuse merge is available to undo.');const undone=applyCreativeMergeInverseV1(acceptedProject,lastReuseMerge.historyEntry);if(!undone.ok)return undone;acceptedProject=undone.value;lastReuseMerge=null;return undone},
    discardReuse:()=>{reuseSandbox=null;return creativeOperationOk(acceptedProject,acceptedProject.revision)},
  }
  return Object.freeze(engine)
}
