import { describe,expect,it } from 'vitest'
import { createMotionScene,nodeBase } from '@sanverse/motion-graph'
import { applyApprovedMotionDraftV1,applyCreativeMergeInverseV1,applyLocalizedMotionRepairV1,approveMotionDraftV1,createMotionDraftV1,discardMotionDraftV1,resolveOwnerCommentToRepairTargetV1,runMotionStructuralQaV1,type AcceptedCreativeProjectV1,type VisualEvidenceV1 } from './quality-lifecycle.ts'

const scene=(heroName='Hero')=>createMotionScene({componentId:'sanverse.lifecycle-proof',componentVersion:1,rootNodeId:'root',nodes:Object.freeze({root:Object.freeze({...nodeBase('root','Root',null),type:'group' as const,childIds:Object.freeze(['hero','untouched'])}),hero:Object.freeze({...nodeBase('hero',heroName,'root'),type:'group' as const,childIds:Object.freeze([])}),untouched:Object.freeze({...nodeBase('untouched','Untouched','root'),type:'group' as const,childIds:Object.freeze([])})}),semanticParts:Object.freeze([{id:'hero-part',label:'Hero',role:'content-group' as const,nodeIds:Object.freeze(['hero'])}]),exposures:Object.freeze([]),layout:Object.freeze({mode:'responsive' as const,ownership:Object.freeze([]),formatOverrides:Object.freeze([])}),supportedAspectRatios:Object.freeze(['16:9'])})
const qa=(value=scene())=>runMotionStructuralQaV1(value,{durationTicks:1_440_000,ticksPerSecond:1_440_000,composition:{width:1920,height:1080,fpsNumerator:30,fpsDenominator:1},sampleTicks:Object.freeze([0,360000,720000,1440000]),expectedSemanticNodeIds:Object.freeze(['hero']),availableCapabilities:Object.freeze([]),requiredCapabilities:Object.freeze([])})
const evidence:VisualEvidenceV1=Object.freeze({canonicalReviewRef:'review://motion/r1',posterRef:'frame://poster',criticalFrameRefs:Object.freeze(['frame://critical']),kvsAnchorFrameRefs:Object.freeze(['frame://kvs']),entrancePayoffExitFrameRefs:Object.freeze(['frame://entry','frame://payoff','frame://exit']),sourceCompositeFrameRefs:Object.freeze(['frame://source-composite'])})

describe('Batch 6 QA / localized repair / owner approval / atomic merge',()=>{
  it('runs exact-tick structural QA and reports capabilities/provenance/locks/unsupported ops without machine approval',()=>{expect(qa()).toEqual({ok:true,findings:[]});const report=runMotionStructuralQaV1(scene(),{durationTicks:1_440_000,ticksPerSecond:1_440_000,composition:{width:1920,height:1080,fpsNumerator:30,fpsDenominator:1},sampleTicks:Object.freeze([720000]),expectedSemanticNodeIds:Object.freeze(['missing']),requiredCapabilities:Object.freeze(['tracking']),availableCapabilities:Object.freeze([]),provenanceViolations:Object.freeze(['Rights evidence missing.']),lockViolations:Object.freeze(['style lock violated']),unsupportedOperationIds:Object.freeze(['motion.magic'])});expect(report.ok).toBe(false);expect(report.findings.map((item)=>item.code)).toEqual(expect.arrayContaining(['SEMANTIC_ID_INTEGRITY','MISSING_REQUIRED_CAPABILITY','PROVENANCE_VIOLATION','LOCK_VIOLATION','UNSUPPORTED_OPERATION']))})
  it('applies a localized reversible repair only to declared nodes and proves unrelated graph regions remain unchanged',()=>{const draft=createMotionDraftV1('motion:draft',4,'plan:1',scene());const repaired=applyLocalizedMotionRepairV1(draft,{id:'repair:1',expectedMotionRevision:1,findingIds:Object.freeze(['finding:1']),beatIds:Object.freeze(['beat:1']),nodeIds:Object.freeze(['hero']),startTick:400000,endTick:600000,operations:Object.freeze([{operationId:'repair:rename',type:'rename-node' as const,nodeId:'hero',name:'Repaired Hero'}])});expect(repaired.ok).toBe(true);if(!repaired.ok)return;expect(repaired.value.draft.scene.nodes.hero?.name).toBe('Repaired Hero');expect(repaired.value.draft.scene.nodes.untouched).toEqual(draft.scene.nodes.untouched);expect(repaired.value.inverseOperations).toHaveLength(1);expect(repaired.value.nodesTouched).toEqual(['hero']);expect(repaired.value.beatsTouched).toEqual(['beat:1'])})
  it('resolves exact-time owner comments to overlapping beats/nodes and stores the touched time range',()=>{const target=resolveOwnerCommentToRepairTargetV1({id:'comment:1',startTick:500000,endTick:700000,nodeIds:Object.freeze(['hero']),comment:'Make this payoff land harder.'},[{id:'beat:a',startTick:0,endTick:600000,nodeIds:Object.freeze(['hero'])},{id:'beat:b',startTick:600000,endTick:1000000,nodeIds:Object.freeze(['hero','untouched'])}]);expect(target.ok).toBe(true);if(!target.ok)return;expect(target.value.beatIds).toEqual(['beat:a','beat:b']);expect(target.value.nodeIds).toEqual(['hero']);expect(target.value.startTick).toBe(500000)})
  it('requires explicit exact-revision motion approval, merges as one history entry, undoes in one inverse, refuses stale merge, and discard leaves accepted state equivalent',()=>{const accepted:AcceptedCreativeProjectV1=Object.freeze({id:'project:1',revision:4,scene:scene()});let draft=createMotionDraftV1('motion:draft',4,'plan:1',scene('Approved Hero'));const approval={schemaVersion:'sanverse.owner-approval/v1' as const,id:'approval:motion:1',scope:'motion' as const,subjectId:draft.id,subjectRevision:draft.revision,status:'owner-approved' as const,approvedAt:'2026-08-26T08:00:00.000Z'};const approved=approveMotionDraftV1(draft,approval,qa(draft.scene),Object.freeze([]),evidence);expect(approved.ok).toBe(true);if(!approved.ok)return;draft=approved.value;const merged=applyApprovedMotionDraftV1(accepted,draft);expect(merged.ok).toBe(true);if(!merged.ok)return;expect(merged.value.project.revision).toBe(5);expect(merged.value.historyEntry.fromRevision).toBe(4);expect(merged.value.historyEntry.toRevision).toBe(5);expect(merged.value.project.scene.nodes.hero?.name).toBe('Approved Hero');const undone=applyCreativeMergeInverseV1(merged.value.project,merged.value.historyEntry);expect(undone.ok).toBe(true);if(!undone.ok)return;expect(undone.value.scene.nodes.hero?.name).toBe('Hero');expect(applyApprovedMotionDraftV1({...accepted,revision:5},draft)).toMatchObject({ok:false,refusal:{code:'STALE_ACCEPTED_PROJECT_REVISION'}});expect(discardMotionDraftV1(accepted,draft)).toBe(accepted)})
})
