import { creativeOperationOk, creativeOperationRefusal, type CreativeOperationResultV1 } from '@sanverse/motion-contract'
import { applyMotionOperations, evaluateScene, validateMotionScene, type MotionGraphOperationV1, type MotionSceneV1 } from '@sanverse/motion-graph'
import { validateOwnerApprovalV1, type OwnerApprovalV1 } from '@sanverse/motion-storyboard'

export type VisualQaStageV1='storyboard'|'animatic'|'motion'
export type QaSeverityV1='info'|'warning'|'error'
export interface VisualQaFindingV1 { readonly id:string; readonly stage:VisualQaStageV1; readonly severity:QaSeverityV1; readonly code:string; readonly message:string; readonly startTick?:number; readonly endTick?:number; readonly stateIds?:readonly string[]; readonly nodeIds?:readonly string[]; readonly beatIds?:readonly string[]; readonly evidenceRefs?:readonly string[] }
export interface VisualEvidenceV1 { readonly canonicalReviewRef:string; readonly posterRef:string; readonly criticalFrameRefs:readonly string[]; readonly kvsAnchorFrameRefs:readonly string[]; readonly entrancePayoffExitFrameRefs:readonly string[]; readonly sourceCompositeFrameRefs:readonly string[] }
export interface MotionStructuralQaContextV1 { readonly durationTicks:number; readonly ticksPerSecond:number; readonly composition:Readonly<{width:number;height:number;fpsNumerator:number;fpsDenominator:number}>; readonly sampleTicks:readonly number[]; readonly expectedSemanticNodeIds?:readonly string[]; readonly requiredCapabilities?:readonly string[]; readonly availableCapabilities?:readonly string[]; readonly unavailableAssetRefs?:readonly string[]; readonly provenanceViolations?:readonly string[]; readonly lockViolations?:readonly string[]; readonly unsupportedOperationIds?:readonly string[] }
export interface MotionStructuralQaFindingV1 { readonly code:string; readonly severity:'error'|'warning'; readonly message:string; readonly nodeIds?:readonly string[]; readonly tick?:number }
export interface MotionStructuralQaReportV1 { readonly ok:boolean; readonly findings:readonly MotionStructuralQaFindingV1[] }

export interface MotionDraftV1 { readonly id:string; readonly baseProjectRevision:number; readonly motionPlanId:string; readonly scene:MotionSceneV1; readonly revision:number; readonly status:'draft'|'qa'|'awaiting-owner'|'owner-approved'; readonly ownerApprovalId?:string }
export interface LocalizedRepairProposalV1 { readonly id:string; readonly expectedMotionRevision:number; readonly findingIds:readonly string[]; readonly beatIds:readonly string[]; readonly nodeIds:readonly string[]; readonly startTick:number; readonly endTick:number; readonly operations:readonly MotionGraphOperationV1[] }
export interface AppliedLocalizedRepairV1 { readonly draft:MotionDraftV1; readonly inverseOperations:readonly MotionGraphOperationV1[]; readonly nodesTouched:readonly string[]; readonly beatsTouched:readonly string[]; readonly tickRange:Readonly<{startTick:number;endTick:number}> }
export interface OwnerExactTimeCommentV1 { readonly id:string; readonly startTick:number; readonly endTick:number; readonly nodeIds:readonly string[]; readonly comment:string }
export interface MotionRepairTargetV1 { readonly commentId:string; readonly startTick:number; readonly endTick:number; readonly nodeIds:readonly string[]; readonly beatIds:readonly string[] }

export interface AcceptedCreativeProjectV1 { readonly id:string; readonly revision:number; readonly scene:MotionSceneV1 }
export interface CreativeMergeHistoryEntryV1 { readonly id:string; readonly fromRevision:number; readonly toRevision:number; readonly previousScene:MotionSceneV1; readonly nextScene:MotionSceneV1 }
export interface AppliedCreativeMergeV1 { readonly project:AcceptedCreativeProjectV1; readonly historyEntry:CreativeMergeHistoryEntryV1 }

const stable=(value:unknown):string=>JSON.stringify(value,(_,entry)=>entry&&typeof entry==='object'&&!Array.isArray(entry)?Object.fromEntries(Object.entries(entry).sort(([a],[b])=>a.localeCompare(b))):entry)
const finding=(code:string,message:string,nodeIds?:readonly string[],tick?:number):MotionStructuralQaFindingV1=>Object.freeze({code,severity:'error' as const,message,...(nodeIds?{nodeIds:Object.freeze([...nodeIds])}:{}),...(tick!==undefined?{tick}:{})})
export const validateVisualEvidenceV1=(evidence:VisualEvidenceV1):readonly string[]=>{const issues:string[]=[];if(!evidence.canonicalReviewRef.trim())issues.push('Canonical 1× review reference is required.');if(!evidence.posterRef.trim())issues.push('Poster reference is required.');if(evidence.criticalFrameRefs.length===0)issues.push('At least one critical checkpoint frame is required.');if(evidence.kvsAnchorFrameRefs.length===0)issues.push('KVS anchor frame evidence is required.');if(evidence.entrancePayoffExitFrameRefs.length===0)issues.push('Entrance/payoff/exit window evidence is required.');if(evidence.sourceCompositeFrameRefs.length===0)issues.push('Source-composite frame evidence is required.');return Object.freeze(issues)}

export const runMotionStructuralQaV1=(scene:MotionSceneV1,context:MotionStructuralQaContextV1):MotionStructuralQaReportV1=>{
  const findings:MotionStructuralQaFindingV1[]=[];const graph=validateMotionScene(scene);if(!graph.ok)findings.push(finding('GRAPH_INVALID',graph.issues.map((item)=>`${item.path}: ${item.message}`).join('; ')))
  const missing=(context.expectedSemanticNodeIds??[]).filter((id)=>!scene.nodes[id]);if(missing.length)findings.push(finding('SEMANTIC_ID_INTEGRITY',`Missing expected semantic nodes: ${missing.join(', ')}.`,missing))
  const capabilities=new Set(context.availableCapabilities??[]),missingCaps=(context.requiredCapabilities??[]).filter((item)=>!capabilities.has(item));if(missingCaps.length)findings.push(finding('MISSING_REQUIRED_CAPABILITY',`Missing capabilities: ${missingCaps.join(', ')}.`))
  for(const asset of context.unavailableAssetRefs??[])findings.push(finding('ASSET_UNAVAILABLE',`Required asset unavailable: ${asset}.`))
  for(const violation of context.provenanceViolations??[])findings.push(finding('PROVENANCE_VIOLATION',violation))
  for(const violation of context.lockViolations??[])findings.push(finding('LOCK_VIOLATION',violation))
  for(const operationId of context.unsupportedOperationIds??[])findings.push(finding('UNSUPPORTED_OPERATION',`Unsupported operation: ${operationId}.`))
  for(const tick of context.sampleTicks){if(!Number.isSafeInteger(tick)||tick<0||tick>context.durationTicks){findings.push(finding('INVALID_RANGE',`QA sample tick ${tick} is outside the motion duration.`,undefined,tick));continue}try{const renderContext={localTicks:tick,durationTicks:context.durationTicks,ticksPerSecond:context.ticksPerSecond,composition:context.composition,reducedMotion:false} as const;const direct=evaluateScene(scene,renderContext);evaluateScene(scene,{...renderContext,localTicks:context.durationTicks});const backward=evaluateScene(scene,renderContext);evaluateScene(scene,{...renderContext,localTicks:0});const repeated=evaluateScene(scene,renderContext);if(stable(direct)!==stable(backward)||stable(backward)!==stable(repeated))findings.push(finding('DIRECT_SEEK_PARITY',`Scene differs across direct/backward/repeated seek at tick ${tick}.`,undefined,tick))}catch(error){findings.push(finding('EXACT_TICK_DETERMINISM',error instanceof Error?error.message:'Exact-tick evaluation failed.',undefined,tick))}}
  return Object.freeze({ok:findings.length===0,findings:Object.freeze(findings)})
}

export const createMotionDraftV1=(id:string,baseProjectRevision:number,motionPlanId:string,scene:MotionSceneV1):MotionDraftV1=>{if(!id.trim()||!motionPlanId.trim()||!Number.isSafeInteger(baseProjectRevision)||baseProjectRevision<0||!validateMotionScene(scene).ok)throw new RangeError('Motion draft input is invalid.');return Object.freeze({id,baseProjectRevision,motionPlanId,scene,revision:1,status:'draft'})}
const operationNodeIds=(operation:MotionGraphOperationV1):readonly string[]=>{if(operation.type==='set-matte')return Object.freeze([operation.relationship.sourceNodeId,operation.relationship.targetNodeId]);if(operation.type==='remove-matte')return Object.freeze([]);if('nodeId'in operation&&typeof operation.nodeId==='string')return Object.freeze([operation.nodeId]);if('target'in operation&&operation.target&&'nodeId'in operation.target)return Object.freeze([operation.target.nodeId]);if(operation.type==='add-node')return Object.freeze([operation.node.id,operation.parentId]);if(operation.type==='group-nodes')return operation.nodeIds;return Object.freeze([])}
export const applyLocalizedMotionRepairV1=(draft:MotionDraftV1,proposal:LocalizedRepairProposalV1):CreativeOperationResultV1<AppliedLocalizedRepairV1>=>{
  if(proposal.expectedMotionRevision!==draft.revision)return creativeOperationRefusal('STALE_MOTION_REVISION',`Expected motion revision ${proposal.expectedMotionRevision}; current revision is ${draft.revision}.`)
  if(draft.status==='owner-approved')return creativeOperationRefusal('MOTION_LOCKED','Owner-approved motion cannot be repaired in place; create a new revision first.')
  if(!proposal.id.trim()||proposal.operations.length===0||!Number.isSafeInteger(proposal.startTick)||!Number.isSafeInteger(proposal.endTick)||proposal.startTick<0||proposal.endTick<proposal.startTick)return creativeOperationRefusal('REPAIR_PROPOSAL_INVALID','Localized repair proposal is invalid.')
  const allowed=new Set(proposal.nodeIds);const touched=[...new Set(proposal.operations.flatMap(operationNodeIds))];const outside=touched.filter((id)=>!allowed.has(id));if(outside.length)return creativeOperationRefusal('REPAIR_SCOPE_VIOLATION',`Repair operations touch nodes outside declared scope: ${outside.join(', ')}.`)
  const beforeUntouched=Object.fromEntries(Object.entries(draft.scene.nodes).filter(([id])=>!allowed.has(id)).map(([id,node])=>[id,stable(node)]))
  const applied=applyMotionOperations(draft.scene,proposal.operations);if(!applied.ok)return creativeOperationRefusal('LOCALIZED_REPAIR_FAILED',applied.error.message,applied.error);if(applied.inverseOperations===null)return creativeOperationRefusal('LOCALIZED_REPAIR_NOT_REVERSIBLE','Localized repair must produce canonical inverse operations.')
  for(const [id,serialized] of Object.entries(beforeUntouched))if(stable(applied.scene.nodes[id])!==serialized)return creativeOperationRefusal('REPAIR_SCOPE_VIOLATION',`Unrelated node ${id} changed during localized repair.`)
  const revision=draft.revision+1;const next:MotionDraftV1=Object.freeze({...draft,scene:applied.scene,revision,status:'draft',ownerApprovalId:undefined})
  return creativeOperationOk(Object.freeze({draft:next,inverseOperations:applied.inverseOperations,nodesTouched:Object.freeze(touched),beatsTouched:Object.freeze([...proposal.beatIds]),tickRange:Object.freeze({startTick:proposal.startTick,endTick:proposal.endTick})}),revision)
}

export const resolveOwnerCommentToRepairTargetV1=(comment:OwnerExactTimeCommentV1,beats:readonly Readonly<{id:string;startTick:number;endTick:number;nodeIds:readonly string[]}>[]):CreativeOperationResultV1<MotionRepairTargetV1>=>{if(!comment.id.trim()||!comment.comment.trim()||!Number.isSafeInteger(comment.startTick)||!Number.isSafeInteger(comment.endTick)||comment.startTick<0||comment.endTick<comment.startTick)return creativeOperationRefusal('OWNER_COMMENT_INVALID','Owner exact-time comment is invalid.');const overlap=beats.filter((beat)=>Math.min(comment.endTick,beat.endTick)>=Math.max(comment.startTick,beat.startTick));const nodeFilter=new Set(comment.nodeIds);const resolvedNodes=[...new Set(overlap.flatMap((beat)=>beat.nodeIds).filter((id)=>nodeFilter.size===0||nodeFilter.has(id)))];return creativeOperationOk(Object.freeze({commentId:comment.id,startTick:comment.startTick,endTick:comment.endTick,nodeIds:Object.freeze(resolvedNodes),beatIds:Object.freeze(overlap.map((beat)=>beat.id))}),1)}

export const approveMotionDraftV1=(draft:MotionDraftV1,approval:OwnerApprovalV1,structuralQa:MotionStructuralQaReportV1,visualFindings:readonly VisualQaFindingV1[],evidence:VisualEvidenceV1):CreativeOperationResultV1<MotionDraftV1>=>{if(!structuralQa.ok)return creativeOperationRefusal('MOTION_QA_FAILED','Motion structural QA must pass before owner approval.',structuralQa.findings);const evidenceIssues=validateVisualEvidenceV1(evidence);if(evidenceIssues.length)return creativeOperationRefusal('VISUAL_EVIDENCE_INCOMPLETE',evidenceIssues.join(' '));if(visualFindings.some((item)=>item.severity==='error'))return creativeOperationRefusal('VISUAL_QA_FAILED','Unresolved visual QA errors remain.',visualFindings);const valid=validateOwnerApprovalV1(approval);if(!valid.ok)return creativeOperationRefusal(valid.refusal.code,valid.refusal.message,valid.refusal.details);if(approval.scope!=='motion'||approval.subjectId!==draft.id||approval.subjectRevision!==draft.revision)return creativeOperationRefusal('APPROVAL_REVISION_MISMATCH','Motion approval must target the exact current motion revision.');return creativeOperationOk(Object.freeze({...draft,status:'owner-approved' as const,ownerApprovalId:approval.id}),draft.revision)}

export const applyApprovedMotionDraftV1=(project:AcceptedCreativeProjectV1,draft:MotionDraftV1):CreativeOperationResultV1<AppliedCreativeMergeV1>=>{if(draft.status!=='owner-approved'||!draft.ownerApprovalId)return creativeOperationRefusal('OWNER_APPROVAL_REQUIRED','Only an explicitly owner-approved motion draft can merge.');if(project.revision!==draft.baseProjectRevision)return creativeOperationRefusal('STALE_ACCEPTED_PROJECT_REVISION',`Sandbox started from project revision ${draft.baseProjectRevision}, but accepted project is now revision ${project.revision}.`);const revision=project.revision+1;const next:AcceptedCreativeProjectV1=Object.freeze({...project,revision,scene:draft.scene});const entry:CreativeMergeHistoryEntryV1=Object.freeze({id:`creative-merge:${draft.id}:r${draft.revision}`,fromRevision:project.revision,toRevision:revision,previousScene:project.scene,nextScene:draft.scene});return creativeOperationOk(Object.freeze({project:next,historyEntry:entry}),revision)}
export const applyCreativeMergeInverseV1=(project:AcceptedCreativeProjectV1,entry:CreativeMergeHistoryEntryV1):CreativeOperationResultV1<AcceptedCreativeProjectV1>=>{if(project.revision!==entry.toRevision||stable(project.scene)!==stable(entry.nextScene))return creativeOperationRefusal('MERGE_INVERSE_STALE','Creative merge inverse no longer matches accepted project state.');const revision=project.revision+1;return creativeOperationOk(Object.freeze({...project,revision,scene:entry.previousScene}),revision)}
export const discardMotionDraftV1=(project:AcceptedCreativeProjectV1,_draft:MotionDraftV1):AcceptedCreativeProjectV1=>project
