import { describe,expect,it } from 'vitest'
import { planMotionForgeV1,type MotionIntentV1,type MotionPlanV1 } from '@sanverse/creative-direction'
import { constant,createDefaultMask,createMotionScene,evaluateScene,nodeBase } from '@sanverse/motion-graph'
import { applyMotionPlanV1,compileMotionIntentV1 } from './semantic-motion.ts'

const scene=()=>createMotionScene({componentId:'sanverse.motion-forge-proof',componentVersion:1,rootNodeId:'root',nodes:Object.freeze({root:Object.freeze({...nodeBase('root','Root',null),type:'group' as const,childIds:Object.freeze(['hero','path'])}),hero:Object.freeze({...nodeBase('hero','Hero','root'),type:'group' as const,childIds:Object.freeze([]),masks:Object.freeze([createDefaultMask('mask:hero','rounded-rectangle')])}),path:Object.freeze({...nodeBase('path','Path','root'),type:'path' as const,pathData:'M 0 0 L 100 0',fillColor:constant('transparent'),strokeColor:constant('#ffffff'),strokeWidth:constant(2),trimProgress:constant(0)})}),semanticParts:Object.freeze([{id:'hero-part',label:'Hero',role:'content-group' as const,nodeIds:Object.freeze(['hero'])}]),exposures:Object.freeze([]),layout:Object.freeze({mode:'responsive' as const,ownership:Object.freeze([]),formatOverrides:Object.freeze([])}),supportedAspectRatios:Object.freeze(['16:9'])})
const ctx=(localTicks:number)=>({localTicks,durationTicks:1_440_000,ticksPerSecond:1_440_000,composition:{width:1920,height:1080,fpsNumerator:30,fpsDenominator:1},reducedMotion:false} as const)

describe('Batch 5 semantic Motion Forge compiler',()=>{
  it('compiles an approved MotionPlan into canonical graph tracks and preserves direct/backward/repeated-seek determinism',()=>{const planned=planMotionForgeV1({motionPlanId:'plan:forge',storyboardId:'storyboard:1',storyboardApprovedRevision:2,storyboardStatus:'owner-approved',animaticId:'animatic:1',animaticApprovedRevision:3,animaticStatus:'owner-approved',stateTimings:Object.freeze([{stateId:'a',startTick:0,endTick:720000,nodeIds:Object.freeze(['hero'])},{stateId:'b',startTick:720000,endTick:1440000,nodeIds:Object.freeze(['hero'])}]),storyboardDiffs:Object.freeze([{fromStateId:'a',toStateId:'b',addedNodeIds:Object.freeze([]),removedNodeIds:Object.freeze([]),changedNodes:Object.freeze([{nodeId:'hero',changedProperties:Object.freeze(['transform'])}])}])});expect(planned.ok).toBe(true);if(!planned.ok)return;const compiled=applyMotionPlanV1(scene(),planned.value);expect(compiled.ok).toBe(true);if(!compiled.ok)return;expect(compiled.value.operations.length).toBeGreaterThanOrEqual(3);const direct=evaluateScene(compiled.value.scene,ctx(1_080_000)).nodes.hero!;evaluateScene(compiled.value.scene,ctx(1_440_000));const backward=evaluateScene(compiled.value.scene,ctx(1_080_000)).nodes.hero!;evaluateScene(compiled.value.scene,ctx(0));const repeated=evaluateScene(compiled.value.scene,ctx(1_080_000)).nodes.hero!;expect(direct).toEqual(backward);expect(backward).toEqual(repeated);expect(direct.transform.positionX).toBeGreaterThan(-80);expect(direct.transform.positionX).toBeLessThanOrEqual(0)})
  it('compiles draw, mask reveal, sequence and controlled overshoot into existing graph/keyframe/mask authorities',()=>{let current=scene();const intents:MotionIntentV1[]=[{id:'draw',type:'motion.draw',nodeIds:Object.freeze(['path']),startTick:0,endTick:300000},{id:'mask',type:'motion.mask-reveal',nodeIds:Object.freeze(['hero']),startTick:300000,endTick:600000,parameters:Object.freeze({maskId:'mask:hero'})},{id:'seq',type:'motion.sequence',nodeIds:Object.freeze(['hero','path']),startTick:600000,endTick:900000},{id:'over',type:'motion.controlled-overshoot',nodeIds:Object.freeze(['hero']),startTick:900000,endTick:1200000}];for(const intent of intents){const result=compileMotionIntentV1(current,intent);expect(result.ok,intent.id).toBe(true);if(!result.ok)continue;const plan:MotionPlanV1={id:`plan:${intent.id}`,storyboardId:'sb',storyboardApprovedRevision:1,animaticId:'an',animaticApprovedRevision:1,beats:Object.freeze([{id:`beat:${intent.id}`,purpose:'build',startTick:intent.startTick,endTick:intent.endTick,nodeIds:intent.nodeIds,operationIntents:Object.freeze([intent])}]),revision:1};const applied=applyMotionPlanV1(current,plan);expect(applied.ok,intent.id).toBe(true);if(applied.ok)current=applied.value.scene}expect(evaluateScene(current,ctx(600000)).nodes.hero!.masks[0]?.opacity).toBe(1);expect(evaluateScene(current,ctx(300000)).nodes.path!.type).toBe('path')})
  it('returns typed refusals for missing nodes, missing mask ids and timing/ease tools without an existing keyframed target',()=>{expect(compileMotionIntentV1(scene(),{id:'bad-node',type:'motion.fade',nodeIds:Object.freeze(['missing']),startTick:0,endTick:100})).toMatchObject({ok:false,refusal:{code:'MOTION_INTENT_TARGET_INVALID'}});expect(compileMotionIntentV1(scene(),{id:'bad-mask',type:'motion.mask-reveal',nodeIds:Object.freeze(['hero']),startTick:0,endTick:100})).toMatchObject({ok:false,refusal:{code:'MOTION_INTENT_PARAMETERS_REQUIRED'}});expect(compileMotionIntentV1(scene(),{id:'bad-ease',type:'motion.soften',nodeIds:Object.freeze(['hero']),startTick:0,endTick:100,parameters:Object.freeze({property:'opacity'})})).toMatchObject({ok:false,refusal:{code:'MOTION_INTENT_REQUIRES_KEYFRAMES'}})})
})
