import { describe,expect,it } from 'vitest'
import { constant,createMotionScene,nodeBase } from '@sanverse/motion-graph'
import { createSanverseToolRegistryV1 } from './registry.ts'
import { registerCreativeEngineV12ToolsV1,SOURCE_AWARE_TOOL_IDS_V12 } from './source-aware-workflow-tools.ts'

const composition={width:1000,height:500,fpsNumerator:30,fpsDenominator:1} as const
const scene=()=>{const root=nodeBase('root','Root',null),card=nodeBase('card','Card','root');return createMotionScene({componentId:'tool.source-aware',componentVersion:1,rootNodeId:'root',nodes:Object.freeze({root:Object.freeze({...root,type:'group' as const,childIds:Object.freeze(['card'])}),card:Object.freeze({...card,type:'shape' as const,shape:'rounded-rectangle' as const,width:constant(120),height:constant(60),fillColor:constant('#00ff88'),strokeColor:constant('#ffffff'),strokeWidth:constant(1),radius:constant(12)})}),semanticParts:Object.freeze([{id:'card',label:'Card',role:'content-group' as const,nodeIds:Object.freeze(['card'])}]),exposures:Object.freeze([]),layout:Object.freeze({mode:'manual' as const,ownership:Object.freeze([]),formatOverrides:Object.freeze([])}),supportedAspectRatios:Object.freeze(['16:9'])})}
const track=Object.freeze({schemaVersion:'sanverse.motion-track/v1' as const,id:'track-1',sourceId:'source-1',sourceStartTick:0,sourceEndTick:720_000,target:Object.freeze({kind:'object' as const,label:'Object'}),samples:Object.freeze([{tick:0,x:.25,y:.5,visibility:1,confidence:1},{tick:720_000,x:.5,y:.5,visibility:1,confidence:1}]),interpolation:Object.freeze({mode:'linear' as const}),status:'valid' as const,metadata:Object.freeze({coordinateSpace:'normalized-source' as const,provider:'fixture',materializedAt:'test'})})
const binding=Object.freeze({schemaVersion:'sanverse.track-binding/v1' as const,id:'bind-1',trackId:'track-1',nodeId:'card',followMode:'position' as const,offset:Object.freeze({x:0,y:0,scaleX:1,scaleY:1,rotation:0}),anchor:Object.freeze({x:.5,y:.5}),smoothingPolicy:'none' as const})
const provenance=(kind:'react-svg'|'remotion')=>Object.freeze({schemaVersion:'sanverse.external-motion-provenance/v1' as const,sourceKind:kind,sourceName:'owner fixture',rightsClass:'owner-authored' as const,attributionRequired:false,reusableLibraryAllowed:true,projectUseAllowed:true,aiModificationAllowed:true,restrictions:Object.freeze([])})

describe('Creative Engine V1.2 internal typed tool surface',()=>{
  it('registers the exact V1.2 tool vocabulary without replacing the registry authority',()=>{const registry=registerCreativeEngineV12ToolsV1(createSanverseToolRegistryV1());expect(registry.list().map(tool=>tool.id).sort((a,b)=>a.localeCompare(b))).toEqual([...SOURCE_AWARE_TOOL_IDS_V12].sort((a,b)=>a.localeCompare(b)))})
  it('runs track QA and tracked-attached rendering through registry validation',async()=>{const registry=registerCreativeEngineV12ToolsV1(createSanverseToolRegistryV1());expect(await registry.invoke('source.track_qa',{track})).toMatchObject({ok:true,value:{ok:true,findings:[]}});const rendered=await registry.invoke('source.render_tracked_attachment',{scene:scene(),track,binding,tick:360_000,composition});expect(rendered).toMatchObject({ok:true,value:{mode:'tracked-attached',tick:360_000}})})
  it('exposes B6/B7 recommendation/scoring as evidence tools rather than project mutation',async()=>{const registry=registerCreativeEngineV12ToolsV1(createSanverseToolRegistryV1());const style=await registry.invoke('style.recommend_lock',{brand:{palette:['#090909','#5fff52'],traits:['clean']},existingStyle:{},approvedAssetSignals:[],promotedAssetSignals:[],videoContext:{talkingHead:true,informationDensity:'high',negativeSpace:'high',subjectPriority:'high'},locked:false});expect(style).toMatchObject({ok:true,value:{schemaVersion:'sanverse.style-lock-recommendation/v1'}});const cohesion=await registry.invoke('cohesion.score_scene',{language:{schemaVersion:'sanverse.video-creative-language/v1',id:'lang',version:1,styleLockId:'style',preferredPresentationModes:['overlay'],typographyLanguage:'editorial',surfaceLanguage:'flat',motionRhythm:'calm',transitionVocabulary:['cut'],densityPolicy:'low',cameraPolicy:'restrained',paletteRoles:['background','accent'],easingFamily:['soft'],overshootMax:.1,allowedExceptions:[]},scene:{sceneId:'s1',paletteRoles:['background','accent'],typographyLanguage:'editorial',surfaceLanguage:'flat',motionRhythm:'calm',easing:'soft',overshoot:.05,density:'low',presentationMode:'overlay',transition:'cut'}});expect(cohesion).toMatchObject({ok:true,value:{level:'HIGH',score:1}})})
  it('rights-gates and materializes the supported React/SVG bridge through the same registry',async()=>{const registry=registerCreativeEngineV12ToolsV1(createSanverseToolRegistryV1()),source='export const Card=()=> (<svg viewBox="0 0 100 100"><rect id="card" x="10" y="10" width="80" height="80" fill="#111111"/></svg>)';expect(await registry.invoke('external.inspect_supported',{assetId:'react-card',sourceKind:'react-svg',source,provenance:provenance('react-svg')})).toMatchObject({ok:true,value:{directSeekSafe:true}});expect(await registry.invoke('external.materialize_supported',{assetId:'react-card',sourceKind:'react-svg',source,provenance:provenance('react-svg')})).toMatchObject({ok:true,value:{kind:'canonical-scene'}})})
  it('exposes the exact semantic M5/M6/M7, easing, stagger and source-layout packs as sandbox-gated tools',async()=>{const registry=registerCreativeEngineV12ToolsV1(createSanverseToolRegistryV1()),state={attached:true,track,binding};for(const id of ['tracking.attach','tracking.detach','tracking.set-target','tracking.set-follow-mode','tracking.set-offset','tracking.set-anchor','tracking.set-smoothing-policy','tracking.correct-sample','surface.attach','surface.set-quad','surface.replace-content','surface.fit','surface.set-mask','surface.set-opacity','surface.correct-track','subject.isolate','subject.set-matte','subject.place-background','subject.add-foreground','motion.soften','motion.snappier','motion.heavy-settle','motion.soft-land','motion.hard-land','motion.controlled-overshoot','motion.remove-overshoot','motion.copy-ease','motion.match-ease','motion.normalize-curves','stagger.deterministic-random','layout.place-in-negative-space','layout.avoid-subject','layout.avoid-face','layout.fit-beside-speaker','layout.balance-split','layout.create-pip','layout.attach-callout','layout.keep-label-readable','layout.wrap-subject'])expect(registry.get(id),id).toMatchObject({requiresSandbox:true});expect(await registry.invoke('tracking.detach',{state})).toMatchObject({ok:false,refusal:{code:'SANDBOX_CONTEXT_REQUIRED'}});expect(await registry.invoke('tracking.detach',{state},{sandboxId:'sandbox:v12'})).toMatchObject({ok:true,value:{attached:false}})})
})
