import { describe,expect,it } from 'vitest'
import { applyMotionOperations,constant,createMotionScene,evaluateScene,keyframed,nodeBase } from '@sanverse/motion-graph'
import { applyEasingPackV12,applySourceAwareLayoutPackV12,applyStaggerPackV12 } from './v12-semantic-packs.ts'
import type { MotionTrackV1,TrackBindingV1 } from '@sanverse/motion-source-aware'

const scene=()=>createMotionScene({componentId:'sanverse.v12-pack-proof',componentVersion:1,rootNodeId:'root',nodes:Object.freeze({root:Object.freeze({...nodeBase('root','Root',null),type:'group' as const,childIds:Object.freeze(['a','b','c','d'])}),a:Object.freeze({...nodeBase('a','A','root'),type:'group' as const,childIds:Object.freeze([]),opacity:keyframed([{id:'a0',tick:0,value:0,interpolation:'linear'},{id:'a1',tick:720_000,value:1,interpolation:'linear'}])}),b:Object.freeze({...nodeBase('b','B','root'),type:'group' as const,childIds:Object.freeze([])}),c:Object.freeze({...nodeBase('c','C','root'),type:'group' as const,childIds:Object.freeze([])}),d:Object.freeze({...nodeBase('d','D','root'),type:'group' as const,childIds:Object.freeze([])})}),semanticParts:Object.freeze([{id:'items',label:'Items',role:'content-group' as const,nodeIds:Object.freeze(['a','b','c','d'])}]),exposures:Object.freeze([]),layout:Object.freeze({mode:'responsive' as const,ownership:Object.freeze([]),formatOverrides:Object.freeze([])}),supportedAspectRatios:Object.freeze(['16:9'])})
const composition={width:1920,height:1080,fpsNumerator:30,fpsDenominator:1} as const
const track:MotionTrackV1={schemaVersion:'sanverse.motion-track/v1',id:'track:layout',sourceId:'source:1',sourceStartTick:0,sourceEndTick:720_000,target:{kind:'object',label:'phone'},samples:Object.freeze([{tick:0,x:.05,y:.05,visibility:1,confidence:1},{tick:720_000,x:.97,y:.95,visibility:1,confidence:1}]),interpolation:{mode:'linear'},status:'valid',metadata:{coordinateSpace:'normalized-source',provider:'fixture',materializedAt:'now'}}
const binding:TrackBindingV1={schemaVersion:'sanverse.track-binding/v1',id:'binding:layout',trackId:track.id,nodeId:'b',followMode:'position',offset:{x:0,y:0,scaleX:1,scaleY:1,rotation:0},anchor:{x:.5,y:.5},smoothingPolicy:'none'}

describe('V1.2 semantic tool packs',()=>{
  it('compiles easing tools to canonical C5-compatible keyframes and direct-seeks deterministically',()=>{const softened=applyEasingPackV12({command:'soften',scene:scene(),nodeId:'a',property:'opacity',durationTicks:720_000});expect(softened.ok).toBe(true);if(!softened.ok)return;const node=evaluateScene(softened.value.scene,{localTicks:360_000,durationTicks:720_000,ticksPerSecond:1_440_000,composition,reducedMotion:false}).nodes.a!;expect(node.opacity).toBeGreaterThan(0);const scaled=applyMotionOperations(softened.value.scene,[{operationId:'scale-track',type:'set-property',target:{nodeId:'a',property:'transform.scaleX'},value:keyframed([{id:'s0',tick:0,value:.8,interpolation:'linear'},{id:'s1',tick:720_000,value:1,interpolation:'linear'}])}],{durationTicks:720_000});expect(scaled.ok).toBe(true);if(!scaled.ok)return;expect(applyEasingPackV12({command:'controlled-overshoot',scene:scaled.scene,nodeId:'a',property:'transform.scaleX',durationTicks:720_000})).toMatchObject({ok:true})})
  it('implements every stagger direction including deterministic-random with stable seed',()=>{for(const mode of ['left-to-right','right-to-left','center-out','outside-in','accelerating','decelerating','wave','deterministic-random'] as const){const a=applyStaggerPackV12({scene:scene(),nodeIds:['a','b','c','d'],mode,startTick:0,endTick:720_000,seed:'same-seed'}),b=applyStaggerPackV12({scene:scene(),nodeIds:['a','b','c','d'],mode,startTick:0,endTick:720_000,seed:'same-seed'});expect(a,mode).toEqual(b);expect(a.ok,mode).toBe(true)}})
  it('places graphics from measured source geometry and keeps tracked labels inside frame bounds',()=>{const negative=applySourceAwareLayoutPackV12({command:'place-in-negative-space',scene:scene(),nodeId:'b',composition,nodeSize:{width:300,height:100},negativeSpaces:[{x:.02,y:.1,width:.3,height:.7},{x:.75,y:.15,width:.2,height:.5}],durationTicks:720_000});expect(negative.ok).toBe(true);const beside=applySourceAwareLayoutPackV12({command:'fit-beside-speaker',scene:scene(),nodeId:'b',composition,nodeSize:{width:300,height:100},subject:{x:.55,y:.15,width:.25,height:.7},durationTicks:720_000});expect(beside.ok).toBe(true);const readable=applySourceAwareLayoutPackV12({command:'keep-label-readable',scene:scene(),nodeId:'b',composition,nodeSize:{width:300,height:100},track,binding,tick:720_000,durationTicks:720_000});expect(readable.ok).toBe(true);if(readable.ok){const resolved=evaluateScene(readable.value.scene,{localTicks:720_000,durationTicks:720_000,ticksPerSecond:1_440_000,composition,reducedMotion:false}).nodes.b!;expect(resolved.transform.positionX).toBeLessThanOrEqual(1920)}})
})
