import { creativeOperationOk,creativeOperationRefusal,type CreativeOperationResultV1,type MotionCompositionV1 } from '@sanverse/motion-contract'
import { applyMotionOperations,constant,keyframed,readMotionAnimatableTarget,type Animatable,type MotionBezierHandlesV1,type MotionGraphOperationV1,type MotionKeyframeV1,type MotionNodePropertyNameV1,type MotionPropertyPrimitiveV1,type MotionSceneV1 } from '@sanverse/motion-graph'
import { deterministicRandom01V1 } from '@sanverse/motion-primitives'
import { compileTrackBindingAtTickV1,evaluateMotionTrackV1,type MotionTrackV1,type TrackBindingV1 } from '@sanverse/motion-source-aware'

export const EASING_PACK_COMMANDS_V12=Object.freeze(['soften','snappier','heavy-settle','soft-land','hard-land','controlled-overshoot','remove-overshoot','copy-ease','match-ease','normalize-curves'] as const)
export type EasingPackCommandV12=(typeof EASING_PACK_COMMANDS_V12)[number]
export interface EasingPackRequestV12 {readonly command:EasingPackCommandV12;readonly scene:MotionSceneV1;readonly nodeId:string;readonly property:MotionNodePropertyNameV1;readonly sourceNodeId?:string;readonly sourceProperty?:MotionNodePropertyNameV1;readonly durationTicks:number}
export interface AppliedToolPackV12 {readonly scene:MotionSceneV1;readonly operations:readonly MotionGraphOperationV1[]}
const ease:Record<Exclude<EasingPackCommandV12,'controlled-overshoot'|'copy-ease'|'match-ease'|'normalize-curves'>,MotionBezierHandlesV1>=Object.freeze({
  soften:{inX:.25,inY:.1,outX:.25,outY:1},snappier:{inX:.12,inY:0,outX:.2,outY:1},'heavy-settle':{inX:.16,inY:.02,outX:.28,outY:1},'soft-land':{inX:.2,inY:.05,outX:.3,outY:1},'hard-land':{inX:.05,inY:0,outX:.18,outY:1},'remove-overshoot':{inX:.25,inY:.1,outX:.25,outY:1},
})
const getTrack=(scene:MotionSceneV1,nodeId:string,property:MotionNodePropertyNameV1)=>{try{return readMotionAnimatableTarget(scene,{kind:'node',nodeId,property})}catch{return null}}
const copyKeys=(keys:readonly MotionKeyframeV1<MotionPropertyPrimitiveV1>[],mapper:(key:MotionKeyframeV1<MotionPropertyPrimitiveV1>,index:number)=>MotionKeyframeV1<MotionPropertyPrimitiveV1>)=>keyframed(keys.map(mapper))
const setTrack=(request:EasingPackRequestV12,value:Animatable<MotionPropertyPrimitiveV1>):CreativeOperationResultV1<AppliedToolPackV12>=>{const operation:Object=Object.freeze({operationId:`easing:${request.command}:${request.nodeId}:${request.property}`,type:'set-property',target:{nodeId:request.nodeId,property:request.property},value});const applied=applyMotionOperations(request.scene,[operation as MotionGraphOperationV1],{durationTicks:request.durationTicks});return applied.ok?creativeOperationOk(Object.freeze({scene:applied.scene,operations:Object.freeze([operation as MotionGraphOperationV1])}),1):creativeOperationRefusal('EASING_PACK_APPLY_FAILED',applied.error.message,applied.error)}
export const applyEasingPackV12=(request:EasingPackRequestV12):CreativeOperationResultV1<AppliedToolPackV12>=>{
  if(!EASING_PACK_COMMANDS_V12.includes(request.command)||!Number.isSafeInteger(request.durationTicks)||request.durationTicks<=0)return creativeOperationRefusal('EASING_PACK_INPUT_INVALID','Easing pack requires a supported command and positive exact duration.')
  const record=getTrack(request.scene,request.nodeId,request.property);if(!record)return creativeOperationRefusal('EASING_PACK_TARGET_INVALID','Easing pack target does not exist.');if(record.animatable.kind!=='keyframes')return creativeOperationRefusal('EASING_PACK_KEYFRAMES_REQUIRED','Easing pack requires an existing canonical keyframed target.')
  const keys=record.animatable.keyframes as readonly MotionKeyframeV1<MotionPropertyPrimitiveV1>[]
  if(request.command==='controlled-overshoot'){if(typeof keys[0]?.value!=='number'||typeof keys.at(-1)?.value!=='number')return creativeOperationRefusal('EASING_PACK_NUMERIC_REQUIRED','Controlled overshoot requires numeric keyframes.');const first=keys[0]!,last=keys.at(-1)!,midTick=Math.round((first.tick+last.tick)/2),from=Number(first.value),to=Number(last.value),delta=Math.max(Math.abs(to-from)*.08,.02);return setTrack(request,keyframed([{...first,interpolation:'bezier',bezier:ease.snappier},{id:`${first.id}:overshoot`,tick:midTick,value:to+(to>=from?delta:-delta),interpolation:'bezier',bezier:{inX:.2,inY:0,outX:.2,outY:1}},{...last,interpolation:'bezier',bezier:ease['soft-land']}]))}
  if(request.command==='copy-ease'||request.command==='match-ease'){if(!request.sourceNodeId||!request.sourceProperty)return creativeOperationRefusal('EASING_PACK_SOURCE_REQUIRED',`${request.command} requires sourceNodeId/sourceProperty.`);const source=getTrack(request.scene,request.sourceNodeId,request.sourceProperty);if(!source||source.animatable.kind!=='keyframes')return creativeOperationRefusal('EASING_PACK_SOURCE_INVALID','Ease source must be an existing canonical keyframed target.');const sourceKeys=source.animatable.keyframes as readonly MotionKeyframeV1<MotionPropertyPrimitiveV1>[];if(!sourceKeys.length)return creativeOperationRefusal('EASING_PACK_SOURCE_INVALID','Ease source has no keyframes.');const value=copyKeys(keys,(key,index)=>{const sourceKey=request.command==='match-ease'?sourceKeys[0]!:sourceKeys[Math.min(index,sourceKeys.length-1)]!;return Object.freeze({...key,interpolation:sourceKey.interpolation, ...(sourceKey.bezier?{bezier:sourceKey.bezier}:{bezier:undefined})})});return setTrack(request,value)}
  const handles=request.command==='normalize-curves'?ease.soften:ease[request.command]
  return setTrack(request,copyKeys(keys,key=>Object.freeze({...key,interpolation:'bezier' as const,bezier:handles})))
}

export const STAGGER_PACK_MODES_V12=Object.freeze(['left-to-right','right-to-left','center-out','outside-in','accelerating','decelerating','wave','deterministic-random'] as const)
export type StaggerPackModeV12=(typeof STAGGER_PACK_MODES_V12)[number]
export interface StaggerPackRequestV12 {readonly scene:MotionSceneV1;readonly nodeIds:readonly string[];readonly mode:StaggerPackModeV12;readonly startTick:number;readonly endTick:number;readonly seed?:string|number}
const orderFor=(count:number,mode:StaggerPackModeV12,seed:string|number):readonly number[]=>{const indices=Array.from({length:count},(_,i)=>i);if(mode==='right-to-left')return indices.reverse();if(mode==='center-out')return indices.sort((a,b)=>Math.abs(a-(count-1)/2)-Math.abs(b-(count-1)/2)||a-b);if(mode==='outside-in')return indices.sort((a,b)=>Math.abs(b-(count-1)/2)-Math.abs(a-(count-1)/2)||a-b);if(mode==='deterministic-random')return indices.sort((a,b)=>deterministicRandom01V1(seed,a)-deterministicRandom01V1(seed,b)||a-b);if(mode==='wave')return indices.sort((a,b)=>Math.sin(a*Math.PI/2)-Math.sin(b*Math.PI/2)||a-b);return indices}
export const applyStaggerPackV12=(request:StaggerPackRequestV12):CreativeOperationResultV1<AppliedToolPackV12>=>{if(!request.nodeIds.length||!Number.isSafeInteger(request.startTick)||!Number.isSafeInteger(request.endTick)||request.startTick<0||request.endTick<=request.startTick)return creativeOperationRefusal('STAGGER_PACK_INPUT_INVALID','Stagger pack requires nodes and a valid exact-tick range.');const missing=request.nodeIds.filter(id=>!request.scene.nodes[id]);if(missing.length)return creativeOperationRefusal('STAGGER_PACK_TARGET_INVALID',`Missing stagger nodes: ${missing.join(', ')}.`);const order=orderFor(request.nodeIds.length,request.mode,request.seed??'sanverse-v1.2'),rank=new Map(order.map((index,rank)=>[index,rank])),span=request.endTick-request.startTick;const operations=request.nodeIds.map((nodeId,index)=>{const r=rank.get(index)??index,linear=r/Math.max(1,request.nodeIds.length),fraction=request.mode==='accelerating'?fractionPow(linear,1.6):request.mode==='decelerating'?fractionPow(linear,.65):linear,start=Math.min(request.endTick-1,request.startTick+Math.round(span*.72*fraction)),end=Math.min(request.endTick,start+Math.max(1,Math.round(span*.28)));return Object.freeze({operationId:`stagger:${request.mode}:${nodeId}`,type:'set-property' as const,target:{nodeId,property:'opacity' as const},value:keyframed([{id:`stagger:${nodeId}:0`,tick:start,value:0,interpolation:'bezier' as const,bezier:ease.snappier},{id:`stagger:${nodeId}:1`,tick:end,value:1,interpolation:'bezier' as const,bezier:ease['soft-land']}])})});const applied=applyMotionOperations(request.scene,operations,{durationTicks:request.endTick});return applied.ok?creativeOperationOk(Object.freeze({scene:applied.scene,operations:Object.freeze(operations)}),1):creativeOperationRefusal('STAGGER_PACK_APPLY_FAILED',applied.error.message,applied.error)}
const fractionPow=(value:number,power:number)=>Math.max(0,Math.min(1,Math.pow(value,power)))

export interface NormalizedRectV12 {readonly x:number;readonly y:number;readonly width:number;readonly height:number}
export const SOURCE_AWARE_LAYOUT_COMMANDS_V12=Object.freeze(['place-in-negative-space','avoid-subject','avoid-face','fit-beside-speaker','balance-split','create-pip','attach-callout','keep-label-readable','wrap-subject'] as const)
export type SourceAwareLayoutCommandV12=(typeof SOURCE_AWARE_LAYOUT_COMMANDS_V12)[number]
export interface SourceAwareLayoutRequestV12 {readonly command:SourceAwareLayoutCommandV12;readonly scene:MotionSceneV1;readonly nodeId:string;readonly composition:MotionCompositionV1;readonly nodeSize:Readonly<{width:number;height:number}>;readonly subject?:NormalizedRectV12;readonly face?:NormalizedRectV12;readonly negativeSpaces?:readonly NormalizedRectV12[];readonly tick?:number;readonly track?:MotionTrackV1;readonly binding?:TrackBindingV1;readonly durationTicks:number}
const validRect=(rect:NormalizedRectV12|undefined)=>Boolean(rect&&[rect.x,rect.y,rect.width,rect.height].every(Number.isFinite)&&rect.width>0&&rect.height>0)
const center=(rect:NormalizedRectV12)=>({x:rect.x+rect.width/2,y:rect.y+rect.height/2})
const placementOps=(request:SourceAwareLayoutRequestV12,x:number,y:number,scale=1):readonly MotionGraphOperationV1[]=>Object.freeze([{operationId:`layout:${request.command}:${request.nodeId}:x`,type:'set-property',target:{nodeId:request.nodeId,property:'transform.positionX'},value:constant(x*request.composition.width)},{operationId:`layout:${request.command}:${request.nodeId}:y`,type:'set-property',target:{nodeId:request.nodeId,property:'transform.positionY'},value:constant(y*request.composition.height)},{operationId:`layout:${request.command}:${request.nodeId}:sx`,type:'set-property',target:{nodeId:request.nodeId,property:'transform.scaleX'},value:constant(scale)},{operationId:`layout:${request.command}:${request.nodeId}:sy`,type:'set-property',target:{nodeId:request.nodeId,property:'transform.scaleY'},value:constant(scale)}] as MotionGraphOperationV1[])
export const applySourceAwareLayoutPackV12=(request:SourceAwareLayoutRequestV12):CreativeOperationResultV1<AppliedToolPackV12>=>{
  if(!SOURCE_AWARE_LAYOUT_COMMANDS_V12.includes(request.command)||!request.scene.nodes[request.nodeId])return creativeOperationRefusal('SOURCE_LAYOUT_INPUT_INVALID','Source-aware layout requires a supported command and existing node.')
  if(request.command==='keep-label-readable'||request.command==='attach-callout'){if(!request.track||!request.binding||!Number.isSafeInteger(request.tick))return creativeOperationRefusal('SOURCE_LAYOUT_TRACK_REQUIRED',`${request.command} requires canonical track, binding and exact tick.`);let operations:readonly MotionGraphOperationV1[];try{operations=compileTrackBindingAtTickV1(request.scene,request.track,request.binding,request.tick!,request.composition)}catch(error){return creativeOperationRefusal('SOURCE_LAYOUT_TRACK_INVALID',error instanceof Error?error.message:'Track binding failed.')};if(request.command==='attach-callout'){const applied=applyMotionOperations(request.scene,operations,{durationTicks:request.durationTicks});return applied.ok?creativeOperationOk(Object.freeze({scene:applied.scene,operations}),1):creativeOperationRefusal('SOURCE_LAYOUT_APPLY_FAILED',applied.error.message,applied.error)}const tracked=evaluateMotionTrackV1(request.track,request.tick!),halfX=request.nodeSize.width/(2*request.composition.width),halfY=request.nodeSize.height/(2*request.composition.height),x=Math.max(halfX,Math.min(1-halfX,tracked.x)),y=Math.max(halfY,Math.min(1-halfY,tracked.y));const clamped=placementOps(request,x,y,request.binding.offset.scaleX);const combined=Object.freeze([...operations,...clamped]);const applied=applyMotionOperations(request.scene,combined,{durationTicks:request.durationTicks});return applied.ok?creativeOperationOk(Object.freeze({scene:applied.scene,operations:combined}),1):creativeOperationRefusal('SOURCE_LAYOUT_APPLY_FAILED',applied.error.message,applied.error)}
  let target={x:.5,y:.5},scale=1
  if(request.command==='create-pip'){target={x:.82,y:.2};scale=.3}
  else if(request.command==='place-in-negative-space'){const spaces=(request.negativeSpaces??[]).filter(validRect);if(!spaces.length)return creativeOperationRefusal('SOURCE_LAYOUT_NEGATIVE_SPACE_REQUIRED','place-in-negative-space requires measured negative-space rectangles.');target=center([...spaces].sort((a,b)=>b.width*b.height-a.width*a.height)[0]!)}
  else {const obstacle=request.command==='avoid-face'?request.face:request.subject;if(!validRect(obstacle))return creativeOperationRefusal('SOURCE_LAYOUT_OBSTACLE_REQUIRED',`${request.command} requires measured ${request.command==='avoid-face'?'face':'subject'} bounds.`);const c=center(obstacle!),left=obstacle!.x,right=1-(obstacle!.x+obstacle!.width);if(request.command==='balance-split'){target={x:c.x<.5?.75:.25,y:.5}}else if(request.command==='fit-beside-speaker'){target={x:left>right?Math.max(.15,left/2):Math.min(.85,obstacle!.x+obstacle!.width+right/2),y:c.y}}else if(request.command==='wrap-subject'){target={x:left>right?.18:.82,y:c.y};scale=.82}else target={x:left>right?.15:.85,y:c.y<.5?.75:.25}}
  const operations=placementOps(request,target.x,target.y,scale),applied=applyMotionOperations(request.scene,operations,{durationTicks:request.durationTicks});return applied.ok?creativeOperationOk(Object.freeze({scene:applied.scene,operations}),1):creativeOperationRefusal('SOURCE_LAYOUT_APPLY_FAILED',applied.error.message,applied.error)
}
