import { buildCreativePreferenceIntelligenceV1,type CreativeFailureEvidenceV1,type CreativePreferenceEvidenceV1 } from '@sanverse/creative-direction'
import { applyCameraDepthControlV1,renderCameraDepthAtTickV1,type CameraDepthControlStateV1,type CameraRigPropertyV1,type DepthBindingV1 } from '@sanverse/motion-camera-depth'
import { creativeOperationOk,creativeOperationRefusal,creativeValidationOk,type CreativeValidationResultV1 } from '@sanverse/motion-contract'
import { inspectExternalMotionAssetV1,materializeExternalMotionAssetV1,type ExternalMotionProvenanceV1 } from '@sanverse/motion-external-bridge'
import type { MotionKeyframeV1,MotionSceneV1 } from '@sanverse/motion-graph'
import { createCreativeEngineV12ToolRegistryV1 } from './source-aware-workflow-tools.ts'
import type { ClosedLoopEngineV1 } from './closed-loop-engine.ts'
import type { PromotionReuseEngineV1 } from './promotion-reuse-engine.ts'
import type { SanverseToolDefinitionV1,SanverseToolRegistryV1 } from './registry.ts'

const outputSchema=Object.freeze({type:'object',required:['ok'],additionalProperties:true})
const schema=(required:readonly string[])=>Object.freeze({type:'object',required:Object.freeze([...required]),additionalProperties:true})
const record=(input:unknown):input is Record<string,unknown>=>Boolean(input)&&typeof input==='object'&&!Array.isArray(input)
const requiredRecord=(keys:readonly string[])=>(input:unknown):CreativeValidationResultV1<Record<string,unknown>>=>record(input)&&keys.every(key=>key in input)?creativeValidationOk(input):({ok:false,refusal:Object.freeze({code:'INVALID_TOOL_INPUT',message:`Tool input requires: ${keys.join(', ')}.`})})
const register=<I,O>(registry:SanverseToolRegistryV1,definition:SanverseToolDefinitionV1<I,O>)=>{const result=registry.register(definition as SanverseToolDefinitionV1);if(!result.ok)throw new RangeError(`${result.refusal.code}: ${result.refusal.message}`)}

export const CAMERA_DEPTH_TOOL_IDS_V13=Object.freeze(['camera.set-position','camera.set-zoom','camera.set-keyframe','camera.remove-keyframe','depth.set','depth.remove','depth.distribute','camera.render-depth'] as const)
export const PREFERENCE_TOOL_IDS_V13=Object.freeze(['preference.build-intelligence'] as const)
export const RIVE_TOOL_IDS_V13=Object.freeze(['external.inspect-rive','external.materialize-rive'] as const)
export const CREATIVE_ENGINE_V13_TOOL_IDS=Object.freeze([...CAMERA_DEPTH_TOOL_IDS_V13,...PREFERENCE_TOOL_IDS_V13,...RIVE_TOOL_IDS_V13] as const)

export const registerCreativeEngineV13ToolsV1=(registry:SanverseToolRegistryV1):SanverseToolRegistryV1=>{
  register(registry,{id:'camera.set-position',version:1,level:'T1',inputSchema:schema(['state','x','y']),outputSchema,requiresSandbox:true,validateInput:requiredRecord(['state','x','y']),execute:(input)=>applyCameraDepthControlV1(input.state as CameraDepthControlStateV1,{type:'camera.set-position',x:Number(input.x),y:Number(input.y)})})
  register(registry,{id:'camera.set-zoom',version:1,level:'T1',inputSchema:schema(['state','zoom']),outputSchema,requiresSandbox:true,validateInput:requiredRecord(['state','zoom']),execute:(input)=>applyCameraDepthControlV1(input.state as CameraDepthControlStateV1,{type:'camera.set-zoom',zoom:Number(input.zoom)})})
  register(registry,{id:'camera.set-keyframe',version:1,level:'T1',inputSchema:schema(['state','property','keyframe']),outputSchema,requiresSandbox:true,validateInput:requiredRecord(['state','property','keyframe']),execute:(input)=>applyCameraDepthControlV1(input.state as CameraDepthControlStateV1,{type:'camera.set-keyframe',property:String(input.property) as CameraRigPropertyV1,keyframe:input.keyframe as MotionKeyframeV1<number>})})
  register(registry,{id:'camera.remove-keyframe',version:1,level:'T1',inputSchema:schema(['state','property','keyframeId']),outputSchema,requiresSandbox:true,validateInput:requiredRecord(['state','property','keyframeId']),execute:(input)=>applyCameraDepthControlV1(input.state as CameraDepthControlStateV1,{type:'camera.remove-keyframe',property:String(input.property) as CameraRigPropertyV1,keyframeId:String(input.keyframeId)})})
  register(registry,{id:'depth.set',version:1,level:'T1',inputSchema:schema(['state','scene','binding']),outputSchema,requiresSandbox:true,validateInput:requiredRecord(['state','scene','binding']),execute:(input)=>applyCameraDepthControlV1(input.state as CameraDepthControlStateV1,{type:'depth.set',binding:input.binding as DepthBindingV1},input.scene as MotionSceneV1)})
  register(registry,{id:'depth.remove',version:1,level:'T1',inputSchema:schema(['state','nodeId']),outputSchema,requiresSandbox:true,validateInput:requiredRecord(['state','nodeId']),execute:(input)=>applyCameraDepthControlV1(input.state as CameraDepthControlStateV1,{type:'depth.remove',nodeId:String(input.nodeId)})})
  register(registry,{id:'depth.distribute',version:1,level:'T1',inputSchema:schema(['state','scene','nodeIds','minimumDepth','maximumDepth']),outputSchema,requiresSandbox:true,validateInput:requiredRecord(['state','scene','nodeIds','minimumDepth','maximumDepth']),execute:(input)=>applyCameraDepthControlV1(input.state as CameraDepthControlStateV1,{type:'depth.distribute',nodeIds:Array.isArray(input.nodeIds)?input.nodeIds.map(String):[],minimumDepth:Number(input.minimumDepth),maximumDepth:Number(input.maximumDepth)},input.scene as MotionSceneV1)})
  register(registry,{id:'camera.render-depth',version:1,level:'T1',inputSchema:schema(['state','scene','tick','composition']),outputSchema,requiresSandbox:true,validateInput:requiredRecord(['state','scene','tick','composition']),execute:(input)=>{const state=input.state as CameraDepthControlStateV1;return renderCameraDepthAtTickV1({scene:input.scene as MotionSceneV1,rig:state.rig,bindings:state.bindings,tick:Number(input.tick),composition:input.composition as never})}})
  register(registry,{id:'preference.build-intelligence',version:1,level:'T0',inputSchema:schema(['preferences','failures']),outputSchema,requiresSandbox:false,validateInput:requiredRecord(['preferences','failures']),execute:(input)=>buildCreativePreferenceIntelligenceV1(input.preferences as readonly CreativePreferenceEvidenceV1[],input.failures as readonly CreativeFailureEvidenceV1[])})
  register(registry,{id:'external.inspect-rive',version:1,level:'T0',inputSchema:schema(['assetId','source','provenance']),outputSchema,requiresSandbox:false,validateInput:requiredRecord(['assetId','source','provenance']),execute:(input)=>{const source=String(input.source),inspection=inspectExternalMotionAssetV1({assetId:String(input.assetId),sourceKind:'rive',bytes:source,provenance:input.provenance as ExternalMotionProvenanceV1});return inspection.ok?creativeOperationOk(inspection.value,1):creativeOperationRefusal(inspection.refusal.code,inspection.refusal.message,inspection.refusal.details)}})
  register(registry,{id:'external.materialize-rive',version:1,level:'T1',inputSchema:schema(['assetId','source','provenance']),outputSchema,requiresSandbox:true,validateInput:requiredRecord(['assetId','source','provenance']),execute:(input)=>{const source=String(input.source),inspection=inspectExternalMotionAssetV1({assetId:String(input.assetId),sourceKind:'rive',bytes:source,provenance:input.provenance as ExternalMotionProvenanceV1});if(!inspection.ok)return creativeOperationRefusal(inspection.refusal.code,inspection.refusal.message,inspection.refusal.details);const materialized=materializeExternalMotionAssetV1(inspection.value,source);return materialized.ok?creativeOperationOk(materialized.value,1):creativeOperationRefusal(materialized.refusal.code,materialized.refusal.message,materialized.refusal.details)}})
  return registry
}

export const createCreativeEngineV13ToolRegistryV1=(closedLoop:ClosedLoopEngineV1,promotion:PromotionReuseEngineV1):SanverseToolRegistryV1=>registerCreativeEngineV13ToolsV1(createCreativeEngineV12ToolRegistryV1(closedLoop,promotion))
