import { describe,expect,it } from 'vitest'
import { constant,createMotionScene,nodeBase } from '@sanverse/motion-graph'
import type { CameraDepthControlStateV1 } from '@sanverse/motion-camera-depth'
import { createSanverseToolRegistryV1 } from './registry.ts'
import { registerCreativeEngineV13ToolsV1,CREATIVE_ENGINE_V13_TOOL_IDS } from './v13-workflow-tools.ts'

const duration=1_440_000,composition={width:1000,height:500,fpsNumerator:30,fpsDenominator:1} as const
const root=nodeBase('root','Root',null),back=nodeBase('back','Back','root'),hero=nodeBase('hero','Hero','root')
const scene=createMotionScene({componentId:'v13-tools',componentVersion:1,rootNodeId:'root',nodes:{root:{...root,type:'group',childIds:['back','hero']},back:{...back,type:'shape',shape:'rectangle',width:constant(1),height:constant(1),fillColor:constant('#111111'),strokeColor:constant('transparent'),strokeWidth:constant(0),radius:constant(0)},hero:{...hero,type:'shape',shape:'rectangle',width:constant(.3),height:constant(.2),fillColor:constant('#ffffff'),strokeColor:constant('transparent'),strokeWidth:constant(0),radius:constant(0)}},semanticParts:[],exposures:[],layout:{mode:'manual',ownership:[],formatOverrides:[]},supportedAspectRatios:['16:9']})
const state:CameraDepthControlStateV1={schemaVersion:'sanverse.camera-depth-control-state/v1',rig:{schemaVersion:'sanverse.camera-rig/v1',id:'camera:main',durationTicks:duration,positionX:constant(0),positionY:constant(0),zoom:constant(1)},bindings:[{schemaVersion:'sanverse.depth-binding/v1',id:'depth:hero',nodeId:'hero',depth:1}]}
const provenance={schemaVersion:'sanverse.external-motion-provenance/v1' as const,sourceKind:'rive' as const,sourceName:'owner rive subset',rightsClass:'owner-authored' as const,attributionRequired:false,reusableLibraryAllowed:true,projectUseAllowed:true,aiModificationAllowed:true,restrictions:[] as const}
const rive=JSON.stringify({schemaVersion:'sanverse.rive-subset/v1',artboardId:'hero',width:1000,height:500,durationTicks:duration,stateMachines:[],shapes:[{id:'card',type:'rect',x:500,y:250,width:200,height:100,fill:'#22ddff'}]})

describe('Creative Engine V1.3 internal tool layer',()=>{
  it('registers the exact V1.3 surface and requires sandbox for candidate-mutating camera/depth/Rive tools',()=>{const registry=registerCreativeEngineV13ToolsV1(createSanverseToolRegistryV1());expect(registry.list().map(tool=>tool.id).sort()).toEqual([...CREATIVE_ENGINE_V13_TOOL_IDS].sort());for(const id of ['camera.set-position','camera.set-zoom','depth.set','depth.distribute','camera.render-depth','external.materialize-rive'])expect(registry.get(id),id).toMatchObject({requiresSandbox:true});expect(registry.get('preference.build-intelligence')).toMatchObject({requiresSandbox:false})})
  it('routes typed camera controls through sandbox fencing and renders the same C10 authority',async()=>{const registry=registerCreativeEngineV13ToolsV1(createSanverseToolRegistryV1());expect(await registry.invoke('camera.set-zoom',{state,zoom:1.2})).toMatchObject({ok:false,refusal:{code:'SANDBOX_CONTEXT_REQUIRED'}});const changed=await registry.invoke('camera.set-zoom',{state,zoom:1.2},{sandboxId:'sandbox:v13'});expect(changed).toMatchObject({ok:true,value:{rig:{zoom:{kind:'constant',value:1.2}}}});const rendered=await registry.invoke('camera.render-depth',{state,scene,tick:720_000,composition},{sandboxId:'sandbox:v13'});expect(rendered).toMatchObject({ok:true,value:{schemaVersion:'sanverse.camera-depth-frame/v1',tick:720_000,semanticNodeIds:expect.arrayContaining(['hero'])}})})
  it('builds conservative explainable B8 intelligence without mutating project state',async()=>{const registry=registerCreativeEngineV13ToolsV1(createSanverseToolRegistryV1()),preferences=[['p1','a'],['p2','b'],['p3','b']].map(([id,projectId])=>({schemaVersion:'sanverse.creative-preference-evidence/v1',id,projectId,kind:'owner-accepted',dimension:'camera-policy',value:'restrained',contextTags:['talking-head']}));const result=await registry.invoke('preference.build-intelligence',{preferences,failures:[]});expect(result).toMatchObject({ok:true,value:{promoted:[{dimension:'camera-policy',value:'restrained',positiveCount:3}],policy:{automaticMutation:false}}})})
  it('rights-gates and materializes only the deterministic Rive subset through the same registry',async()=>{const registry=registerCreativeEngineV13ToolsV1(createSanverseToolRegistryV1());expect(await registry.invoke('external.inspect-rive',{assetId:'rive-card',source:rive,provenance})).toMatchObject({ok:true,value:{sourceKind:'rive',deterministic:true,directSeekSafe:true}});expect(await registry.invoke('external.materialize-rive',{assetId:'rive-card',source:rive,provenance})).toMatchObject({ok:false,refusal:{code:'SANDBOX_CONTEXT_REQUIRED'}});expect(await registry.invoke('external.materialize-rive',{assetId:'rive-card',source:rive,provenance},{sandboxId:'sandbox:v13'})).toMatchObject({ok:true,value:{kind:'canonical-scene',scene:{componentId:'external.rive-card'}}})})
})
