import { describe, expect, it } from 'vitest'
import { createSanverseToolRegistryV1 } from './registry.ts'
import { CREATIVE_ENGINE_V14_TOOL_IDS, registerCreativeEngineV14ToolsV1 } from './v14-workflow-tools.ts'

const provenance=(sourceKind:'procedural'|'shader')=>({schemaVersion:'sanverse.external-motion-provenance/v1' as const,sourceKind,sourceName:`owner ${sourceKind}`,rightsClass:'owner-authored' as const,attributionRequired:false,reusableLibraryAllowed:true,projectUseAllowed:true,aiModificationAllowed:true,restrictions:[] as const})
const procedural=JSON.stringify({schemaVersion:'sanverse.procedural-subset/v1',program:'orbital-rings',width:960,height:540,seed:42,parameters:{ringCount:8,radius:180,thickness:4,wobble:14,speed:1.1}})
const shader=JSON.stringify({schemaVersion:'sanverse.shader-subset/v1',program:'plasma-field',width:960,height:540,seed:88,parameters:{frequency:.8,amplitude:.9,hueShift:210,scale:1.2}})

describe('Creative Engine V1.4 internal Expert Motion tool layer',()=>{
  it('registers the exact bounded V1.4 surface with sandbox fences on candidate-producing calls',()=>{const registry=registerCreativeEngineV14ToolsV1(createSanverseToolRegistryV1());expect(registry.list().map(tool=>tool.id).sort()).toEqual([...CREATIVE_ENGINE_V14_TOOL_IDS].sort());for(const id of ['expert.instantiate-recipe','expert.evaluate-at-tick','external.materialize-procedural','external.materialize-shader'])expect(registry.get(id),id).toMatchObject({requiresSandbox:true});for(const id of ['external.inspect-procedural','external.inspect-shader'])expect(registry.get(id),id).toMatchObject({requiresSandbox:false})})
  it('instantiates and exact-tick evaluates a vetted expert recipe only inside an explicit sandbox',async()=>{const registry=registerCreativeEngineV14ToolsV1(createSanverseToolRegistryV1());expect(await registry.invoke('expert.instantiate-recipe',{recipeId:'expert.radial-payoff',width:960,height:540})).toMatchObject({ok:false,refusal:{code:'SANDBOX_CONTEXT_REQUIRED'}});const made=await registry.invoke('expert.instantiate-recipe',{recipeId:'expert.radial-payoff',width:960,height:540,seed:77},{sandboxId:'sandbox:v14'});expect(made).toMatchObject({ok:true,value:{kind:'particles',program:'radial-burst',seed:77}});if(!made.ok)return;const frame=await registry.invoke('expert.evaluate-at-tick',{spec:made.value,tick:3_456_789},{sandboxId:'sandbox:v14'});expect(frame).toMatchObject({ok:true,value:{schemaVersion:'sanverse.motion-expert-frame/v1',tick:3_456_789,seed:77,resourceUsage:{primitiveCount:72}}})})
  it('rights-gates, inspects and materializes only the supported declarative procedural/shader subsets',async()=>{const registry=registerCreativeEngineV14ToolsV1(createSanverseToolRegistryV1());for(const [kind,source] of [['procedural',procedural],['shader',shader]] as const){expect(await registry.invoke(`external.inspect-${kind}`,{assetId:`asset:${kind}`,source,provenance:provenance(kind)})).toMatchObject({ok:true,value:{sourceKind:kind,deterministic:true,directSeekSafe:true,materialization:'canonical-scene'}});expect(await registry.invoke(`external.materialize-${kind}`,{assetId:`asset:${kind}`,source,provenance:provenance(kind)})).toMatchObject({ok:false,refusal:{code:'SANDBOX_CONTEXT_REQUIRED'}});expect(await registry.invoke(`external.materialize-${kind}`,{assetId:`asset:${kind}`,source,provenance:provenance(kind)},{sandboxId:'sandbox:v14'})).toMatchObject({ok:true,value:{kind:'canonical-scene',scene:{nodes:expect.any(Object)}}})}})
})
