import { describe,expect,it } from 'vitest'
import { createMotionScene,nodeBase } from '@sanverse/motion-graph'
import { createStoryboardV1,type KeyVisualStateV1,type OwnerApprovalV1 } from './contracts.ts'
import { applyAnimaticTransactionV1,approveAnimaticV1,buildAnimaticReviewModelV1,createAnimaticV1,runAnimaticQaV1 } from './animatic.ts'
import { diffStoryboardStatesV1 } from './storyboard-diff.ts'

const graph=(name='Hero')=>createMotionScene({componentId:'sanverse.animatic-proof',componentVersion:1,rootNodeId:'root',nodes:Object.freeze({root:Object.freeze({...nodeBase('root','Root',null),type:'group' as const,childIds:Object.freeze(['hero'])}),hero:Object.freeze({...nodeBase('hero',name,'root'),type:'group' as const,childIds:Object.freeze([])})}),semanticParts:Object.freeze([{id:'hero',label:'Hero',role:'content-group' as const,nodeIds:Object.freeze(['hero'])}]),exposures:Object.freeze([]),layout:Object.freeze({mode:'responsive' as const,ownership:Object.freeze([]),formatOverrides:Object.freeze([])}),supportedAspectRatios:Object.freeze(['16:9'])})
const state=(id:string,tick:number,name='Hero'):KeyVisualStateV1=>Object.freeze({schemaVersion:'sanverse.key-visual-state/v1',id,semanticPurpose:'custom',approximateTick:tick,presentationMode:'overlay',sourceTreatment:'normal',backgroundTreatment:'source-video',focusNodeIds:Object.freeze(['hero']),graphState:graph(name)})
const approvedStoryboard=()=>createStoryboardV1({id:'storyboard:approved',sourceRevision:1,setup:{schemaVersion:'sanverse.storyboard-presentation-setup/v1',sourceRegion:{startTick:0,endTick:2_880_000},communicationGoal:'Explain',presentationMode:'overlay',sourceTreatment:'normal',backgroundTreatment:'source-video',preserveSourceAudio:true,preserveSourceVideo:true,requiredCapabilities:Object.freeze([])},states:Object.freeze([state('a',0),state('b',1_440_000,'Payoff')]),status:'owner-approved',revision:3,ownerApprovalId:'approval:storyboard'})

describe('Batch 4 Animatic + Storyboard Diff',()=>{
  it('owns exact KVS timing, supports B1-style alignment operations, and round-trips through one inverse transaction',()=>{const sb=approvedStoryboard();const anim=createAnimaticV1({id:'animatic:1',storyboardId:sb.id,storyboardApprovedRevision:sb.revision,timings:Object.freeze([{stateId:'a',startTick:0,endTick:1_440_000},{stateId:'b',startTick:1_440_000,endTick:2_880_000}]),sourceAudioRef:{sourceId:'source:1'}},sb);const moved=applyAnimaticTransactionV1(anim,{transactionId:'tx:align',expectedRevision:1,operations:Object.freeze([{type:'animatic.align-to-source-phrase',stateId:'b',sourceStartTick:1_500_000,sourceEndTick:2_880_000}])});expect(moved.ok).toBe(true);if(!moved.ok)return;expect(moved.value.animatic.timings[1]).toMatchObject({startTick:1_500_000,endTick:2_880_000});const undo=applyAnimaticTransactionV1(moved.value.animatic,moved.value.inverse);expect(undo.ok).toBe(true);if(!undo.ok)return;expect(undo.value.animatic.timings[1]).toMatchObject({startTick:1_440_000,endTick:2_880_000})})
  it('separates deterministic QA from owner approval and exposes real source-audio + KVS-hold review controls',()=>{const sb=approvedStoryboard();const anim=createAnimaticV1({id:'animatic:1',storyboardId:sb.id,storyboardApprovedRevision:sb.revision,timings:Object.freeze([{stateId:'a',startTick:0,endTick:1_440_000},{stateId:'b',startTick:1_440_000,endTick:2_880_000}]),sourceAudioRef:{sourceId:'source:1'}},sb);const qa=runAnimaticQaV1(anim,sb,{minimumReadableHoldTicks:240_000,sourceRegion:sb.setup.sourceRegion});expect(qa.ok).toBe(true);const model=buildAnimaticReviewModelV1(anim,[{id:'comment:1',startTick:1_440_000,endTick:1_600_000,comment:'Hold this beat longer.'}]);expect(model.controls).toEqual(['play','pause','scrub','loop']);expect(model.sourceAudioRef?.sourceId).toBe('source:1');const approval:OwnerApprovalV1={schemaVersion:'sanverse.owner-approval/v1',id:'approval:animatic',scope:'animatic',subjectId:anim.id,subjectRevision:anim.revision,status:'owner-approved',approvedAt:'2026-08-26T07:30:00.000Z'};expect(approveAnimaticV1(anim,approval,qa)).toMatchObject({ok:true,value:{animatic:{status:'owner-approved'}}})})
  it('reports gaps/overlaps/bounds instead of silently fixing timing',()=>{const sb=approvedStoryboard();const anim=createAnimaticV1({id:'animatic:bad',storyboardId:sb.id,storyboardApprovedRevision:sb.revision,timings:Object.freeze([{stateId:'a',startTick:0,endTick:1_000_000},{stateId:'b',startTick:1_200_000,endTick:3_000_000}])},sb);const qa=runAnimaticQaV1(anim,sb,{minimumReadableHoldTicks:240_000,sourceRegion:sb.setup.sourceRegion});expect(qa.ok).toBe(false);expect(qa.findings.map((item)=>item.code)).toEqual(expect.arrayContaining(['GAP','SOURCE_BOUNDS']))})
  it('produces a structural diff with stable IDs and changed node properties for motion planning',()=>{const from=state('a',0),to=state('b',1_440_000,'Payoff');const diff=diffStoryboardStatesV1(from,to);expect(diff.fromStateId).toBe('a');expect(diff.toStateId).toBe('b');expect(diff.addedNodeIds).toEqual([]);expect(diff.changedNodes.find((item)=>item.nodeId==='hero')?.changedProperties).toContain('name')})
})
