import { describe,expect,it } from 'vitest'
import { evaluateScene } from '@sanverse/motion-graph'
import { inspectExternalMotionAssetV1,materializeExternalMotionAssetV1 } from './inspection.ts'
import type { ExternalMotionProvenanceV1 } from './provenance.ts'
const rights=(sourceKind:ExternalMotionProvenanceV1['sourceKind']):ExternalMotionProvenanceV1=>({schemaVersion:'sanverse.external-motion-provenance/v1',sourceKind,sourceName:'owner fixture',rightsClass:'owner-authored',attributionRequired:false,reusableLibraryAllowed:true,projectUseAllowed:true,aiModificationAllowed:true,restrictions:[]})
describe('V1.2 React/SVG + Remotion bridges',()=>{
  it('materializes a static owner-authored React/SVG tree to native Sanverse nodes and rejects runtime JS',()=>{const source=`export const Icon=()=> (<svg viewBox="0 0 100 100"><rect id="card" x="10" y="10" width="80" height="80" rx="8" fill="#111111"/><path id="mark" d="M 25 50 L 45 70 L 76 30" fill="none" stroke="#ffffff" strokeWidth="4"/></svg>)`;const inspection=inspectExternalMotionAssetV1({assetId:'asset:react:1',sourceKind:'react-svg',bytes:source,provenance:rights('react-svg')});expect(inspection).toMatchObject({ok:true,value:{materialization:'canonical-scene',directSeekSafe:true}});if(inspection.ok){const materialized=materializeExternalMotionAssetV1(inspection.value,source);expect(materialized).toMatchObject({ok:true,value:{kind:'canonical-scene'}})}const unsafe=`const X=()=>{useEffect(()=>fetch('/x'));return <svg><rect width="10" height="10"/></svg>}`;expect(inspectExternalMotionAssetV1({assetId:'asset:react:bad',sourceKind:'react-svg',bytes:unsafe,provenance:rights('react-svg')})).toMatchObject({ok:false,refusal:{code:'EXTERNAL_REACT_UNSUPPORTED_JS'}})})
  it('converts supported Remotion frame/Sequence/interpolate/spring-like timing to exact-tick graph values',()=>{const source=JSON.stringify({schemaVersion:'sanverse.remotion-subset/v1',fps:30,width:1920,height:1080,durationInFrames:90,layers:[{id:'title',type:'text',fromFrame:0,durationInFrames:90,text:'Direct seek',fill:'#ffffff',x:100,y:200,opacity:{from:0,to:1,fromFrame:0,toFrame:15},translateX:{from:-60,to:0,fromFrame:0,toFrame:15},springScale:{from:.85,to:1,fromFrame:0,toFrame:30,damping:.8,frequency:1.2}}]});const inspection=inspectExternalMotionAssetV1({assetId:'asset:remotion:1',sourceKind:'remotion',bytes:source,provenance:rights('remotion')});expect(inspection).toMatchObject({ok:true,value:{metadata:{durationTicks:4_320_000}}});if(!inspection.ok)return;const materialized=materializeExternalMotionAssetV1(inspection.value,source);expect(materialized.ok).toBe(true);if(!materialized.ok||materialized.value.kind!=='canonical-scene')return;const ctx={durationTicks:4_320_000,ticksPerSecond:1_440_000,composition:{width:1920,height:1080,fpsNumerator:30,fpsDenominator:1},reducedMotion:false};const a=evaluateScene(materialized.value.scene,{...ctx,localTicks:720_000}),b=evaluateScene(materialized.value.scene,{...ctx,localTicks:3_000_000}),c=evaluateScene(materialized.value.scene,{...ctx,localTicks:720_000});expect(a).toEqual(c);expect(a).not.toEqual(b)})
})
