import { creativeRefusal,creativeValidationOk,type CreativeValidationResultV1 } from '@sanverse/motion-contract'
import { constant,createMotionScene,keyframed,nodeBase,validateMotionScene,type Animatable,type MotionNodeV1,type MotionSceneV1 } from '@sanverse/motion-graph'
import { SANVERSE_TICKS_PER_SECOND } from '@sanverse/motion-primitives'

const record=(v:unknown):v is Record<string,unknown>=>Boolean(v)&&typeof v==='object'&&!Array.isArray(v)
const finite=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v)
const id=(v:unknown):v is string=>typeof v==='string'&&v.trim().length>0&&v.length<=160
export const normalizeReactSvgV1=(source:string):CreativeValidationResultV1<string>=>{
  if(/\b(useState|useEffect|useLayoutEffect|fetch|XMLHttpRequest|WebSocket|setTimeout|setInterval|requestAnimationFrame|window\.|document\.|Date\.|performance\.|Math\.random)\b/u.test(source)||/\son[A-Z][A-Za-z]*\s*=/u.test(source))return creativeRefusal('EXTERNAL_REACT_UNSUPPORTED_JS','React/SVG V1 refuses runtime hooks, I/O, timers, DOM globals, event handlers and nondeterministic APIs.')
  if(/[{}]/u.test(source.replace(/<svg[\s\S]*<\/svg>/u,'')))return creativeRefusal('EXTERNAL_REACT_UNSUPPORTED_JS','React/SVG V1 supports a static SVG JSX return only; surrounding dynamic expressions are rejected.')
  const match=/<svg\b[\s\S]*<\/svg>/iu.exec(source);if(!match)return creativeRefusal('EXTERNAL_ASSET_INVALID','React/SVG V1 requires one static <svg>…</svg> tree.')
  let svg=match[0]
  if(/\{[^}]+\}/u.test(svg))return creativeRefusal('EXTERNAL_REACT_UNSUPPORTED_JS','React/SVG V1 refuses dynamic JSX expressions inside SVG.')
  svg=svg.replace(/strokeWidth=/gu,'stroke-width=').replace(/fillRule=/gu,'fill-rule=').replace(/clipRule=/gu,'clip-rule=')
  return creativeValidationOk(svg)
}

export interface RemotionSubsetLayerV1 { readonly id:string; readonly type:'text'|'shape'; readonly fromFrame:number; readonly durationInFrames:number; readonly text?:string; readonly shape?:'rectangle'|'rounded-rectangle'|'ellipse'; readonly width?:number; readonly height?:number; readonly fill:string; readonly x:number; readonly y:number; readonly opacity?:Readonly<{from:number;to:number;fromFrame:number;toFrame:number}>; readonly translateX?:Readonly<{from:number;to:number;fromFrame:number;toFrame:number}>; readonly translateY?:Readonly<{from:number;to:number;fromFrame:number;toFrame:number}>; readonly springScale?:Readonly<{from:number;to:number;fromFrame:number;toFrame:number;damping:number;frequency:number}> }
export interface RemotionSubsetDocumentV1 { readonly schemaVersion:'sanverse.remotion-subset/v1'; readonly fps:number; readonly width:number; readonly height:number; readonly durationInFrames:number; readonly layers:readonly RemotionSubsetLayerV1[] }
export const parseRemotionSubsetV1=(source:string):CreativeValidationResultV1<RemotionSubsetDocumentV1>=>{
  let parsed:unknown;try{parsed=JSON.parse(source)}catch{return creativeRefusal('EXTERNAL_ASSET_INVALID','Supported Remotion bridge input must be valid sanverse.remotion-subset/v1 JSON.')}
  if(!record(parsed)||parsed.schemaVersion!=='sanverse.remotion-subset/v1'||!finite(parsed.fps)||parsed.fps<=0||!finite(parsed.width)||parsed.width<=0||!finite(parsed.height)||parsed.height<=0||!Number.isSafeInteger(parsed.durationInFrames)||Number(parsed.durationInFrames)<=0||!Array.isArray(parsed.layers))return creativeRefusal('EXTERNAL_REMOTION_UNSUPPORTED','Remotion V1 supports the declared frame/Sequence/interpolate subset only.')
  for(const raw of parsed.layers as unknown[]){if(!record(raw)||!id(raw.id)||!['text','shape'].includes(String(raw.type))||!Number.isSafeInteger(raw.fromFrame)||!Number.isSafeInteger(raw.durationInFrames)||Number(raw.durationInFrames)<=0||!finite(raw.x)||!finite(raw.y)||typeof raw.fill!=='string')return creativeRefusal('EXTERNAL_REMOTION_UNSUPPORTED','Remotion layer is outside the supported deterministic Sequence/text/shape subset.');if(raw.type==='text'&&typeof raw.text!=='string')return creativeRefusal('EXTERNAL_REMOTION_UNSUPPORTED','Supported Remotion text layer requires static text.');if(raw.type==='shape'&&(!['rectangle','rounded-rectangle','ellipse'].includes(String(raw.shape))||!finite(raw.width)||!finite(raw.height)))return creativeRefusal('EXTERNAL_REMOTION_UNSUPPORTED','Supported Remotion shape layer requires a basic shape and finite dimensions.');for(const key of ['opacity','translateX','translateY'] as const){const value=raw[key];if(value!==undefined&&(!record(value)||!finite(value.from)||!finite(value.to)||!Number.isSafeInteger(value.fromFrame)||!Number.isSafeInteger(value.toFrame)||Number(value.toFrame)<=Number(value.fromFrame)))return creativeRefusal('EXTERNAL_REMOTION_UNSUPPORTED',`${key} must use deterministic interpolate-style frame mapping.`)}if(raw.springScale!==undefined){const s=raw.springScale;if(!record(s)||![s.from,s.to,s.damping,s.frequency].every(finite)||!Number.isSafeInteger(s.fromFrame)||!Number.isSafeInteger(s.toFrame)||Number(s.toFrame)<=Number(s.fromFrame))return creativeRefusal('EXTERNAL_REMOTION_UNSUPPORTED','springScale must be a bounded deterministic spring descriptor.')}}
  return creativeValidationOk(parsed as unknown as RemotionSubsetDocumentV1)
}
const frameTick=(frame:number,fps:number)=>Math.round(frame/fps*SANVERSE_TICKS_PER_SECOND)
const kf=(idPrefix:string,from:number,to:number,fromFrame:number,toFrame:number,fps:number)=>keyframed([{id:`${idPrefix}:0`,tick:frameTick(fromFrame,fps),value:from,interpolation:'linear'},{id:`${idPrefix}:1`,tick:frameTick(toFrame,fps),value:to,interpolation:'linear'}])
export const materializeRemotionSubsetV1=(assetId:string,doc:RemotionSubsetDocumentV1):CreativeValidationResultV1<MotionSceneV1>=>{
  const rootId=`${assetId}::root`,nodes:Record<string,MotionNodeV1>={},childIds:string[]=[]
  for(const layer of doc.layers){const nodeId=`${assetId}::${layer.id}`,base=nodeBase(nodeId,layer.id,rootId),positionX=layer.translateX?kf(`${nodeId}:x`,layer.translateX.from+layer.x,layer.translateX.to+layer.x,layer.translateX.fromFrame,layer.translateX.toFrame,doc.fps):constant(layer.x),positionY=layer.translateY?kf(`${nodeId}:y`,layer.translateY.from+layer.y,layer.translateY.to+layer.y,layer.translateY.fromFrame,layer.translateY.toFrame,doc.fps):constant(layer.y),opacity=layer.opacity?kf(`${nodeId}:opacity`,layer.opacity.from,layer.opacity.to,layer.opacity.fromFrame,layer.opacity.toFrame,doc.fps):constant(1);let scale:Animatable<number>=constant(1);if(layer.springScale){const s=layer.springScale;const samples=[] as {id:string;tick:number;value:number;interpolation:'linear'}[];const span=Math.max(1,s.toFrame-s.fromFrame);for(let f=0;f<=span;f+=1){const p=f/span;const value=s.to+(s.from-s.to)*Math.exp(-s.damping*p*5)*Math.cos(s.frequency*p*Math.PI*2);samples.push({id:`${nodeId}:spring:${f}`,tick:frameTick(s.fromFrame+f,doc.fps),value,interpolation:'linear'})}scale=keyframed(samples)}const transform=Object.freeze({...base.transform,positionX,positionY,scaleX:scale,scaleY:scale});if(layer.type==='text')nodes[nodeId]=Object.freeze({...base,type:'text',transform,opacity,text:constant(layer.text!),fillColor:constant(layer.fill),fontFamily:'Inter',fontSize:constant(48),fontWeight:constant(700),textAlign:'left'});else nodes[nodeId]=Object.freeze({...base,type:'shape',shape:layer.shape!,transform,opacity,width:constant(layer.width!),height:constant(layer.height!),fillColor:constant(layer.fill),strokeColor:constant('transparent'),strokeWidth:constant(0),radius:constant(layer.shape==='rounded-rectangle'?16:0)});childIds.push(nodeId)}
  nodes[rootId]=Object.freeze({...nodeBase(rootId,'Remotion materialized root',null),type:'group',childIds:Object.freeze(childIds)})
  const scene=createMotionScene({componentId:`external.${assetId}`,componentVersion:1,rootNodeId:rootId,nodes:Object.freeze(nodes),semanticParts:Object.freeze(childIds.map((nodeId,i)=>Object.freeze({id:`${assetId}:part:${i}`,label:nodes[nodeId]!.name,role:'decoration' as const,nodeIds:Object.freeze([nodeId])}))),exposures:Object.freeze([]),layout:Object.freeze({mode:'manual' as const,ownership:Object.freeze([]),formatOverrides:Object.freeze([])}),supportedAspectRatios:Object.freeze(['16:9','9:16','1:1','4:5'])});const valid=validateMotionScene(scene);return valid.ok?creativeValidationOk(valid.value):creativeRefusal('EXTERNAL_MATERIALIZATION_INVALID','Remotion subset produced an invalid MotionSceneV1.',valid.issues)
}
